### ISSUE TITLE
No more EF Core 3 support on last version

### ISSUE THREAD

**Issue by kevinfr06** [ErikEJ/EFCorePowerTools#1487] opened 2022-08-16 09:49 UTC
Hello,
Visual studio 2022 has just updated my EFCorePowerTools to version 2.5.1082 and there is no more EF Core 3 support for SQL Server.
Is it still available in last version ?
How can I download the previous version of EFCorePowerTools with EF Core 3 support ?
Regards,
Kevin

**Comment by ErikEJ** [comment] 2022-08-16 10:07
Please share your  csproj file.

I added some logic to.limit list of choices but it is broken for you so let's get it fixed.

**Comment by kevinfr06** [comment] 2022-08-16 10:11
[Rgpd.Entities.csproj.txt](https://github.com/ErikEJ/EFCorePowerTools/files/9349753/Rgpd.Entities.csproj.txt)

**Comment by ErikEJ** [comment] 2022-08-16 10:46
I implemented a fix for this in the latest daily build, would be grateful if you could try it out.

**Comment by kevinfr06** [comment] 2022-08-16 11:02
I can see Ef Core 3 now :
![image](https://user-images.githubusercontent.com/98339151/184863756-40c16bbc-baf0-4632-bbd5-c97ff3934b55.png)

But there is an error after : 
```
System.InvalidOperationException: Reverse engineer error: Unable to launch 'dotnet' version 7.0. Do you have the runtime installed? Check with 'dotnet --list-runtimes'
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas, bool mergeDacpacs)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetDacpacTablesAsync(string dacpacPath, CodeGenerationMode codeGenerationMode)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)
```
I have never had this before

**Comment by ErikEJ** [comment] 2022-08-16 11:19
Did you pick EF Core 3 or EF Core 7 ??

**Comment by kevinfr06** [comment] 2022-08-16 11:27
Et core 3

⁣
Kevin Debeil
***@***.***
06 63 02 26 33​

Le 16 août 2022 à 13:19, à 13:19, Erik Ejlskov Jensen ***@***.***> a écrit:

**Comment by kevinfr06** [comment] 2022-08-16 11:28
I tried twice to be sure

⁣
Kevin Debeil
***@***.***
06 63 02 26 33​

Le 16 août 2022 à 13:19, à 13:19, Erik Ejlskov Jensen ***@***.***> a écrit:

**Comment by ErikEJ** [comment] 2022-08-16 11:41
Hmm.. I am unable to reproduce this - try top delete all your %temp%\efreveng folders.

**Comment by ErikEJ** [comment] 2022-08-16 11:44
What is the value of this in your efpt.config.json file?

    "CodeGenerationMode":

**Comment by ErikEJ** [comment] 2022-08-16 11:58
Able to repro now!

**Comment by ErikEJ** [comment] 2022-08-16 12:21
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out. (Build .1087 or later)

**Closed** 2022-08-16 12:42 UTC
Labels: bug, reveng

**Comment by kevinfr06** [comment] 2022-08-16 12:47
Works fine  :)
Thanks a lot.
Kevin

**Comment by ErikEJ** [comment] 2022-08-16 12:50
Sorry for the disruption!
