### ISSUE TITLE
Context Menus not showing up

### ISSUE THREAD

**Issue by SunilSahasrabuddhe** [ErikEJ/EFCorePowerTools#1029] opened 2021-06-20 19:45 UTC
The EF Core Context menus wont appear when i right click on the project. I have this issue only with EF Core Power Tools version 2.5.688 and Visual Studio 2019.10.2. 
I don't have this issue with EF Core Power Tools version 2.5.665 and Visual Studio 2019.10.1.

### Steps to reproduce
1. Open Visual Studio 2019
2. Ensure  EF Core Power Tools aren't installed. 
2. Install the EF Core Power Tools - I got 2.5.688 today.
3. Open the solution containing the projects where you want to use EF Core Power Tools
4. Add the Microsoft.EntifyFrameworkcore.SqlServer Nuget Package (I have Version 5.0.7) to the project where EF Core will be used
5. Right Click on the project referred above.

### Further technical details
EF Core Power Tools version: (2.5.688)

Database engine: (SQL Server 2019 Developer Edition)

Visual Studio version: (e.g. Visual Studio 2019 16.10.2)

**Comment by ErikEJ** [comment] 2021-06-20 19:52
I will try to repro tomorrow

**Comment by ErikEJ** [comment] 2021-06-21 04:37
Duplicate of #1030 with a better error report

**Closed by ErikEJ** 2021-06-21 04:37 UTC

**Comment by SunilSahasrabuddhe** [comment] 2021-06-21 13:56
Thank you, its working now with the updated version.
