### ISSUE TITLE
could not load assembly efreveng60.dll

### ISSUE THREAD

**Issue by Tksi2021** [ErikEJ/EFCorePowerTools#1173] opened 2021-11-12 06:50 UTC
steps:
new console project
reverse engineer

v 6.2.5.815
VS2019 16.11.6
either EF 5 or EF 6preview

System.Exception: Table list error: 
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Users\joshm\AppData\Local\Temp\efreveng6.2.5.815.0\efreveng60.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Users\joshm\AppData\Local\Temp\efreveng6.2.5.815.0\efreveng60.dll'

   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)

**Comment by ErikEJ** [comment] 2021-11-12 11:34
Most likely duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/1141#issuecomment-945709906

**Closed** 2021-11-13 07:18 UTC
