### ISSUE TITLE
using schemes in MS SQL

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#1693] opened 2023-02-15 07:57 UTC
Hi 

I am using schemes in SQL and I created the following tables 

- lookup.ProductType
- product.detail
- order.detail

When using the tool I tried without scheme folder option and with scheme folder option. It create the class with name as follows "detail" and "detail1"

Would it be possible to create the class with the scheme name and the table with a separation?
**Example** 
- product_detail
- order_detail

**Comment by ErikEJ** [comment] 2023-02-15 08:00
I assume it is to avoid clashes, as all Detail classes are in the same namespace. Seems like a duplicate of #1075

**Comment by smarteez17** [comment] 2023-02-15 08:09
Hi @ErikEJ  - thanks for this reading the linked ticket do we have an eta for this enhancement?

**Comment by ErikEJ** [comment] 2023-02-15 08:19
@smarteez17 Are you very interested in this, feel free to sponsor me or do a PR, but please do not ask for ETAs.

**Closed by ErikEJ** 2023-02-15 08:19 UTC
