### ISSUE TITLE
EF Core 7 does not product default DBContext constructor

### ISSUE THREAD

**Issue by dylanbarquilla** [ErikEJ/EFCorePowerTools#1687] opened 2023-02-09 09:10 UTC
When I try to use EF Core Power Tools with the option of the first window on the down left "EF Core 7" instead of "EF Core 6", there is no constructor in generated code. There is an option in the advanced settings "Remove default DbContext constructor", which is disabled. I tried to enable it just to check, and no changement. 

But if I choose "EF Core 6", everything act normal. Please notice that my project use Dotnet 7, with every last version packages. My extension is up to date with the last version. I do not know since when I have this problem.

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1277

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

If you need any other information I'd be glad to give it to you.
Thanks in advance,

**Comment by ErikEJ** [comment] 2023-02-09 13:40
Please share a code sample showing the difference.

Why do you need the default constructor? You can create it in a partial class if you must have it.

**Comment by dylanbarquilla** [comment] 2023-02-09 14:17
Old code : 
`
namespace Ecofip.PartDieu.Commercial.Application.Queries.Models
{
    public partial class AgenceEquipe
    {
        public AgenceEquipe()
        {
            AgenceEquipeAssistants = new HashSet<AgenceEquipeAssistant>();
        }

        public Guid Id { get; set; }

        public virtual ICollection<AgenceEquipeAssistant> AgenceEquipeAssistants { get; set; }
    }
}
`

New code : 
`
namespace Ecofip.PartDieu.Commercial.Application.Queries.Models;

public partial class AgenceEquipe
{
    public Guid Id { get; set; }

    public virtual ICollection<AgenceEquipeAssistant> AgenceEquipeAssistants { get; } = new List<AgenceEquipeAssistant>();
}
`

I think I was wrong, the issue is not the presence of a constructor or not. I think it is the fact that ICollections does not have a setter generated. When I add it manually it works fine. 

Is it normal?

_For instance, the issue that I have is while using the HotChocolate (Chilly Cream) library, when I try to read children of an element._

**Comment by ErikEJ** [comment] 2023-02-09 14:20
Duplicate of #1587 @bricelam FYI

**Closed** 2023-02-09 14:20 UTC

**Comment by bricelam** [comment] 2023-02-15 20:54
> For instance, the issue that I have is while using the HotChocolate (Chilly Cream) library, when I try to read children of an element.

@dylanbarquilla Can you create a new issue on [dotnet/efcore](https://github.com/dotnet/efcore/issues/new/choose) showing the HotChocolate code and exception message?

**Comment by ErikEJ** [comment] 2023-02-16 07:23
A fix for this [is considered](https://github.com/dotnet/efcore/issues/30286#issuecomment-1431244084) by the EF Core team, and I have included the fix in the latest daily (if you use T4 templates)

**Comment by ErikEJ** [comment] 2023-04-13 06:02
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
