### ISSUE TITLE
Selecting stored procedures randomly selects/unselects other procedures after scrolling

### ISSUE THREAD

**Issue by flamecrow** [ErikEJ/EFCorePowerTools#646] opened 2020-12-09 15:16 UTC
When choosing database objects, checking stored procedures randomly checks/unchecks other procedures after scrolling.

![2020-12-09-07-04-51](https://user-images.githubusercontent.com/20115963/101647894-1f983300-39ee-11eb-957c-8a0b157ed538.gif)

### Steps to reproduce
1.  Right click project > EF Core Power Tools > Reverse Engineer
2.  Select Database from dropdown (must have many stored procedures)
3.  Check "Use EF Core 5", click OK
4.  Under "Stored Procedures > dbo", select any stored procedure
5.  Scroll down until selections are out of view, select any additional stored procedures
6.  Scroll back up and notice previous selections have been unselected and/or other random stored procedures are selected

### Further technical details
Version 2.5.378.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Server

Visual Studio version: 
Microsoft Visual Studio Community 2019
Version 16.8.3

**Comment by ErikEJ** [comment] 2020-12-09 15:37
Thanks for the video, possible duplicate of #645

@sm15455 FYI

**Comment by ErikEJ** [comment] 2020-12-09 18:13
I was able to replicate, once I had many stored procedures. I have attached a script to generate many stored procedures.

[ManySprocs.sql.txt](https://github.com/ErikEJ/EFCorePowerTools/files/5667803/ManySprocs.sql.txt)

**Comment by sm15455** [comment] 2020-12-09 20:51
Got it. It's a TreeView virtualization problem. I'll disable it while looking for a better solution.

**Comment by ErikEJ** [comment] 2020-12-10 06:58
@flamecrow This is fixed in the latest daily build, would be grateful if you could verify

**Closed by ErikEJ** 2020-12-10 06:58 UTC

**Comment by ErikEJ** [comment] 2020-12-10 11:33
![image](https://user-images.githubusercontent.com/4169187/101766977-df1ae100-3ae3-11eb-864a-2bc4d010a81b.png)

**Comment by flamecrow** [comment] 2020-12-10 13:25
> @flamecrow This is fixed in the latest daily build, would be grateful if you could verify

Tested and verified working fix, awesome!

**Comment by ErikEJ** [comment] 2020-12-10 13:31
@flamecrow Thanks a lot for your heads up
