### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by David-Galugis** [ErikEJ/EFCorePowerTools#454] opened 2020-08-11 10:19 UTC
System.Exception: Table list error: Unable to launch external process: 
   à ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildTableResult(String output) dans C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:ligne 159
   à ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) dans C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:ligne 57
   à ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetDacpacTables(String dacpacPath) dans C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:ligne 27
   à ReverseEngineer20.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) dans C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:ligne 30
   à EFCorePowerTools.Handlers.ReverseEngineerHandler.GetDacpacTables(String dacpacPath, Boolean useEFCore5) dans C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:ligne 339
   à EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() dans C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:ligne 92

Error with the last version (used on VS 2019, version 16.3.6)

A comment??

### Steps to reproduce
After choose of data base connection

### Further technical details
EF Core Power Tools version: 2.4.140.0

Database engine: SQL Server

Visual Studio version: (e.g. Visual Studio 2019 16.3.6)
![2020-08-11_12h18_59](https://user-images.githubusercontent.com/54445551/89886404-dc0ef300-dbcc-11ea-8ec3-9f2ae0f87230.png)

**Comment by ErikEJ** [comment] 2020-08-11 10:21
Possible duplicate of this: https://github.com/ErikEJ/EFCorePowerTools/issues/452#issuecomment-671745432 - please try the latest daily build

**Comment by David-Galugis** [comment] 2020-08-11 10:55
How to get this build?

**Comment by David-Galugis** [comment] 2020-08-11 11:10
I installed 2.4.150.0 and still doesn't work

![2020-08-11_13h09_00](https://user-images.githubusercontent.com/54445551/89890583-e7195180-dbd3-11ea-922a-e26fe29fa4c6.png)
![2020-08-11_13h09_14](https://user-images.githubusercontent.com/54445551/89890612-f0a2b980-dbd3-11ea-997c-2066e7319c92.png)

0.0

**Comment by Danielhsc** [comment] 2020-08-11 11:45
Same problem here. But, I'm using VS 2017 (15.9.25) and EF Power Tools version 2.4.140.

**Comment by ErikEJ** [comment] 2020-08-11 11:56
@David-Galugis  Please try the debugging procedure here: https://github.com/ErikEJ/EFCorePowerTools/issues/452#issuecomment-671745432

@Danielhsc Exact same issue?? then pls try the debugging procedure here: https://github.com/ErikEJ/EFCorePowerTools/issues/452#issuecomment-671745432

**Comment by ErikEJ** [comment] 2020-08-11 11:56
Duplicate of #452

**Closed by ErikEJ** 2020-08-11 11:56 UTC
