### ISSUE TITLE
Create ICollection as  gets Only 

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#1702] opened 2023-02-24 09:54 UTC
In my db I have a Hotel table that links to a Roomtypes  the relationship is One to many. When I use the tool it creates the relationship as gets I need it to be both gets and sets. So I can assign and value to it 
public partial class Hotel
{
    [Key]
    public int HotelId { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    public int LocationId { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("Hotels")]
    public virtual Location Location { get; set; }

    [InverseProperty("Hotel")]
    **public virtual ICollection<RoomType> RoomTypes { get; } = new List<RoomType>();**
}

public partial class RoomType
{
    [Key]
    public int RoomTypeId { get; set; }

    [Required]
    [StringLength(10)]
    public string RoomCode { get; set; }

    [Required]
    [StringLength(255)]
    public string Room { get; set; }

    [Required]
    [StringLength(255)]
    public string BedSize { get; set; }

    public int AvailableNumber { get; set; }

    public int HotelId { get; set; }

    public bool Archived { get; set; }

    [ForeignKey("HotelId")]
    [InverseProperty("RoomTypes")]
    public virtual Hotel Hotel { get; set; }
}

**Comment by ErikEJ** [comment] 2023-02-24 10:00
Duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/1587#issuecomment-1432634881

**Closed by ErikEJ** 2023-02-24 10:00 UTC
