### ISSUE TITLE
Is there a way to download a working version of the tool for Visual Studio 2019

### ISSUE THREAD

**Issue by dukepug** [ErikEJ/EFCorePowerTools#1645] opened 2023-01-03 19:39 UTC
Hi, I am still using Visual Studio 2019 and was wondering if there is a way to download an older build that works on it.

Thank you.

**Comment by ErikEJ** [comment] 2023-01-04 06:58
Why do you still need VS 2019?

Duplicate of #1639

**Closed by ErikEJ** 2023-01-04 06:58 UTC
