### ISSUE TITLE
Tables do not appear in EF Core Power Tools to be selected and create references

### ISSUE THREAD

**Issue by lgomesroc** [ErikEJ/EFCorePowerTools#2028] opened 2023-12-01 17:59 UTC
Hello, how are you Erik? I ask you to look at the EF Core Power Tools extension that does not show the tables to be selected and create code to reference in Visual Studio. From version .NET 5.0 to version .NET 8.0. Please check as soon as possible. Thank you and hugs.

**Comment by ErikEJ** [comment] 2023-12-01 20:10
Duplicate of #2024 ??

**Comment by ErikEJ** [comment] 2023-12-02 15:37
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Closed by ErikEJ** 2023-12-02 15:37 UTC

**Comment by ErikEJ** [comment] 2023-12-05 09:39
@lgomesroc Ping?

**Comment by lgomesroc** [comment] 2023-12-31 11:25
Erik, everything is fine. Thank you for everything.
