### ISSUE TITLE
Using custom IDesignTimeService

### ISSUE THREAD

**Issue by Jochem-agro** [ErikEJ/EFCorePowerTools#632] opened 2020-12-04 13:13 UTC
Hello

I made an implementation of IDesignTimeService for adding my own handlerbarhelpers when scaffolding the model classes. This works fine when using the scaffolding command via PowerShell but when using EF Core Power Tools the implementation of IDesignTimeService does not get called. 

if you need more information please let me know.

### Steps to reproduce
1) Create Web project
2) Create .NET Core class library for holding models
3) Add implementation of IDesignTimeService to class library
4) Run the Reverse Enginieer option of EF Core Power Tools

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.277.0

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Visual Studio 2019 16.7.5

**Comment by ErikEJ** [comment] 2020-12-04 13:17
Duplicate of #427 - not something I plan to implement.

**Closed by ErikEJ** 2020-12-04 13:17 UTC

**Comment by Jochem-agro** [comment] 2020-12-04 13:23
I see we'll just stick to the command, thanks for the quick reply.

**Comment by ErikEJ** [comment] 2020-12-10 14:20
@Jochem-agro  Just curios: What exactly do you need that you cannot do with EF Core Power Tools bulit-in features?

**Comment by Jochem-agro** [comment] 2020-12-10 17:29
@ErikEJ Well, in it's essence it would be great if you we're able to add interfaces during generation of the model. We are using soft deletes marked by an interface so we can use Entity Frameworks Query Filters to omit the need of added an active query throughout the application.

Currently I'm pretty invested in using hbs files to configure the generation of the model so using those and `IDesignTimeServices` would be great as well but reading the original issue that would require some work.

**Comment by ErikEJ** [comment] 2020-12-10 17:37
Well, you could use the built-in HandleBars support combined with column exclusions.

But thanks for the info anyway.

**Comment by Jochem-agro** [comment] 2020-12-11 11:04
@ErikEJ I just noticed the existence of epft.config.json. I am wondering if the possibility exists of adding interfaces needed on the generated classes here?

**Comment by ErikEJ** [comment] 2020-12-11 11:12
No, but you can use the HandleBars support for that

**Comment by Jochem-agro** [comment] 2020-12-11 11:47
Okay I see now, looking at some code `IReverseEngineerScaffolder` of Microsoft.EntityFrameworkCore.Scaffolding is used to generate the files. The thing is that only a few of the generated classes should have the interface, but yes handlebars is the way to go. thnx for you time anyways.
