### ISSUE TITLE
The required column 'Col0' was not present in the results of a 'FromSql' operation.

### ISSUE THREAD

**Issue by ducman** [ErikEJ/EFCorePowerTools#1233] opened 2021-12-22 21:06 UTC
Executing a stored procedure resulted in the following exception:
_System.InvalidOperationException: The required column 'Col0' was not present in the results of a 'FromSql' operation._

The stored procedure in question returns a result with no column name (`dbo.sp_describe_first_result_set` shows `null` for name). It seems the reverse engineering is automatically adding in "Col{index}" to the result. 

I was expecting an empty partial result class.

PS: it is an easy fix for the developer to provide a column name in the stored procedure but unfortunately this database is read-only (developer lacking schema change permission).

### Steps to reproduce
Create a stored procedure like so:
```sql
CREATE PROCEDURE dbo.Test()
AS
BEGIN 
	DECLARE @Id INT = 0
	SELECT @Id
END
```

Reverse engineer the above-stored procedure and notice the generated result class to have a property called `Col0`. When executing the stored procedure the exception is thrown.

### Further technical details

EF Core version in use: 5

EF Core Power Tools version: 2.5.866

Database engine: SQL Server 2019

Visual Studio version: Visual Studio 2019 16.11.8

**Comment by ErikEJ** [comment] 2021-12-23 06:06
Sounds like a regression due to recent changes to support multiple result sets.

**Comment by ErikEJ** [comment] 2021-12-23 07:38
Fixed in latest daily (actually not a regression)

**Closed** 2021-12-23 07:38 UTC

**Comment by ErikEJ** [comment] 2021-12-24 08:28
Please let me know if that fixes your issue

**Comment by ducman** [comment] 2022-01-06 00:06
It did fix the issue. 

I did notice that it still creates the `Result` class which isn't referenced at all. Below are the changes I see as an example:

Before:
```cs
public virtual async Task<List<TestResult>> TestAsync(...) { ... }
```

After:
```cs
// notice it returns an int but the TestResult.cs is still generated (empty class, no longer has the Col0 property)
public virtual async Task<int> TestAsync(...) { ... }
```

**Comment by ErikEJ** [comment] 2022-01-06 06:00
Does Test sproc actually return anything? Can you provide a repro sproc?

**Comment by ducman** [comment] 2022-01-07 19:42
The example sproc in the 1st post does `SELECT @Id`. I read that there is no way for EF to get back this data. The only way to get the data is to alter the sproc to give it a column name (i.e.  `SELECT @Id AS Id`).

I think that is why the `TestResult` is still generated; just that it couldn't find any columns so the class is empty. Btw, I left out the guts of the method that you can find below.

Before:
```cs
public virtual async Task<List<TestResult>> TestAsync(...) 
{ 
  // parameters setup
  var _ = await _context.SqlQueryAsync<TestResult>(...);
  return _;
}
```
After:
```cs
public virtual async Task<int> TestAsync(...)
{
  // parameters setup
  var _ = await _context.Database.ExecuteSqlRawAsync(...);
  return _;
}
```
Everything is fine for me.
