### ISSUE TITLE
calling Stored Procedure doesn't return anything when calling it sync

### ISSUE THREAD

**Issue by rasoul-tiebreak** [ErikEJ/EFCorePowerTools#2291] opened 2024-04-24 07:04 UTC
generated code for Stored Procedures are in async manner using SqlQueryAsync. is there anyway to generate it sync. my program/my method is not async and considered sometimes calling the SP like below example doesn't return anything.
during debugging I considered that the execution enter the method but didn't exit. it seems hanging internally.

context.Procedures.GetXXXAsync(A1, A2).Result;
OR
context.Procedures.GetXXXAsync(A1, A2).GetAwaiter().GetREsult();
OR
Task.Run( async () => await  context.Procedures.GetXXXAsync(A1, A2));

running profiler it seems the sp is executed against database.

**Comment by TimKras** [comment] 2024-05-02 11:24
@ErikEJ 
Is there a reason why the tool doesn't generate the 'Sync' and 'Async' methods always?
The ObjectContext also have both 'SaveChanges' and 'SaveChangesAsync'. Depending where you use the code, you can chose the correct one.

If there are any reasons to not generate them both, I would like to suggest the possibility to configure it through the 'efpt.config.json' settings file, in stead of a general setting.

**Comment by ErikEJ** [comment] 2024-05-02 11:41
Other than code bloat I see no reason - but asking for non-Async is kind of obsolete these days?

**Comment by TimKras** [comment] 2024-05-02 11:51
@ErikEJ For new projects, maybe yes. But for maintaining older projects I can understand the use of 'non-Async'.

But this is even another reason to be able to define it in the project config file. Because otherwise you have to change the general setting depending on the project.

**Comment by ErikEJ** [comment] 2024-05-02 12:13
How about making it an option in the config file then, and remove the global option?

**Comment by ErikEJ** [comment] 2024-05-02 12:13
@TimKras  Default to Async of course

**Comment by ErikEJ** [comment] 2024-05-02 12:35
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment] 2024-05-02 12:36
@TimKras I have updated the wiki with docs on the new option

**Closed** 2024-05-02 12:35 UTC
Labels: question

**Comment by TimKras** [comment] 2024-05-02 12:43
I will do a test tomorrow.
Much appreciated already.

**Comment by TimKras** [comment] 2024-05-03 08:44
Confirmed it is working in the latest daily build.
Thanks a lot!

**Comment by ErikEJ** [comment] 2024-05-03 09:01
Great, and thanks for confirming

**Comment by rasoul-tiebreak** [comment] 2024-05-07 07:14
we are migrating an old project and for time being it is needed to call the non async one.it will be great  if the tool can generate both sync and async side by side and to have choice to call the proper one. Thank u very much

**Comment by ErikEJ** [comment] 2024-05-07 07:27
@rasoul-tiebreak That is not something I plan to implement, but you could run the tool twice, and rename som classes and methods  after first run
