### ISSUE TITLE
Addon and Questions

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#432] opened 2020-07-27 07:37 UTC
Hi I watch your Watch **"demo from EF Core Community Standup"** and found it helpfully . Firstly I would like to say thank you. I have a few questions and maybe request to add on my options 

1. Currently the only an option to bring in Tables, can the following be brought in as well
    1.1 Views 
    1.2 Store Procs
    1.3 Functions ( both table and scalar )  

2. Having a Interface for the context file that extends IDisposable

3. With regards to separation of concerns have folders for ( I not sure if the tool can do some of them already )
   3.1 Configuration 
   3.2 Interface 

4. In my database I have a parent Table and a child table one-to-one relationship so in the child table I dont have a Primary key 
the tool is giving me warning

**Comment by ErikEJ** [comment] 2020-07-27 07:57
re 1: tables and views are currently supported, stored procedures is #18 (which I am working on now for SQL Server) - if you need functions support, please create an issue describing a design proposal (for generated code)

re 2: you can do this using Handlebars templates, see the wiki

re 3: duplicate of #423 (the tool never creates Interfaces)

re 4: Please post an issue with more details for reproduction, if you think this is a bug

**Closed by ErikEJ** 2020-07-27 07:57 UTC
