### ISSUE TITLE
Reverse Engineer forces the user to choose minimum 1 table

### ISSUE THREAD

**Issue by jjoergensen** [ErikEJ/EFCorePowerTools#1041] opened 2021-07-05 12:45 UTC
When I choose Reverse Engineer I intend to derive code for Stored Procedures from a database-server, but I am forced to also choose a table, even when no table access is required.

I do not expect to use table access at all.

### Steps to reproduce

1. Right click on a project and choose "EF Core Power Tools"
2. In the window "Choose Database Connection" just choose OK.
3. In the window "Choose Database Objects" point to ONLY stored procedures. Choose minimum 1.
4. Make sure no "Tables" are chosen.

The problem shows as the "OK" button being disable, so that I'm unable to click it.

### Further technical details
EF Core Power Tools version: 2.5.692.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.10.3

**Comment by ErikEJ** [comment] 2021-07-05 12:53
Duplicate of #1002 and #713

The underlying EF Core code generation framework requires at least 1 selected table in order to work.

**Comment by ErikEJ** [comment] 2021-07-05 12:53
Workaround is to map to a dummy table and remove it after code generation

**Comment by ErikEJ** [comment] 2021-07-05 13:01
Update the docs with that limitation

**Comment by jjoergensen** [comment] 2021-07-05 13:04
Thanks. Sorry I didn't find the duplicate.

I also had luck with a temp table and removing it afterwards. But for the "next" developer, this has to be maintained every time it is updated. But we could create a permanent dummy table in the database.

**Comment by ErikEJ** [comment] 2021-07-05 14:05
Let me check again if some Hack is possible..

**Comment by ErikEJ** [comment] 2021-07-06 05:20
OK: Adding a non-existing table to the tool config file enables the tooling to succeed creating an empty DbContext. 
I will try to implement the HACK.

**Comment by ErikEJ** [comment] 2021-07-06 13:19
I attempted a fix/hack in the latest daily

**Closed** 2021-07-06 13:18 UTC
