### ISSUE TITLE
Odd field setting when BIT, not Null and a Default Value

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#1302] opened 2022-03-03 20:45 UTC
I have a table that has 2 BIT fields, Disposed and Available. Both are set to NOT NULL with Disposed set with a default of 0 and Available with a default of 1.

When I run EFCorePowerTools on the database and table, the Disposed field sets as 
public bool Disposed { get; set; }

and the Available field sets as 
[Required]
        public bool? Available { get; set; }

If I set Available to have a Default Value of 0, the bool? becomes bool and the [Required] is removed.

### Steps to reproduce
Have a table with 2 field, designed as BIT, Not Null and set a default value. For example with a table called Radio_Equipment

ALTER TABLE [dbo].[Radio_Equipment] ADD  CONSTRAINT [DF_Radio_Equipment_Disposed]  DEFAULT ((0)) FOR [Disposed]
GO

ALTER TABLE [dbo].[Radio_Equipment] ADD  CONSTRAINT [DF_Radio_Equipment_Available]  DEFAULT ((1)) FOR [Available]
GO

Check the Radio_Equipment.cs file and the fields will be:
        public bool Disposed { get; set; }
        [Required]
        public bool? Available { get; set; }

Change the Default for Available to 0 and Radio_Equipment.cs will contain:
        public bool Disposed { get; set; }
        public bool Available { get; set; }

### Further technical details

EF Core version in use: EF Core 6

Is Handlebars used: no

EF Core Power Tools version: Version 2.5.926.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment] 2022-03-04 06:29
This is a duplicate of many issues, and [by design](https://github.com/ErikEJ/EFCorePowerTools/issues/160#issuecomment-453286573) - and there is an [advanced option](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-advanced-options) to work around it.

**Closed by ErikEJ** 2022-03-04 06:29 UTC
