### ISSUE TITLE
Error with retrieving multi result sets during reverse engineering.

### ISSUE THREAD

**Issue by DavidCAllenMI** [ErikEJ/EFCorePowerTools#1325] opened 2022-04-05 15:43 UTC
I am now getting these two errors below with the current daily build. I was not able to test yesterday as the vsis gallery was done.  It is complaining about a custom type in our DB which is defined as:

CREATE TYPE [dbo].[TVP_SOFA_DEPENDENT] AS TABLE(
	[DEPL_ID] [UNIQUEIDENTIFIER] NOT NULL,
	[SOFA_COUNTRY_QUESTION_ID] [UNIQUEIDENTIFIER] NOT NULL,
	[DEPENDENT_NAME] [VARCHAR](100) NULL,
	[DOB] [DATETIME] NULL,
	[PASSPORT_NMBR] [VARCHAR](20) NULL,
	[SOFA_DEPEND_RELATIONSHIP_ID] [UNIQUEIDENTIFIER] NULL,
	[PASSPORT_COUNTRY_ID] [UNIQUEIDENTIFIER] NULL,
	[SOFA_DEPL_PERSON_DEPENDENT_ID] [UNIQUEIDENTIFIER] NULL
)
GO

Unable to get result set shape for PROCEDURE 'dbo.SOFA_QUESTION_CREATE_EF'
Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: nvarchar is incompatible with TVP_SOFA_DEPENDENT
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 84
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 105
ClientConnectionId:9f50a6a5-f8f6-4fc6-bd31-2ce562d713d6
Error Number:206,State:2,Class:16

Unable to get result set shape for PROCEDURE 'dbo.SOFA_QUESTION_UPDATE_EF'
Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: nvarchar is incompatible with TVP_SOFA_DEPENDENT
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 84
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 105
ClientConnectionId:9f50a6a5-f8f6-4fc6-bd31-2ce562d713d6
Error Number:206,State:2,Class:16

**Comment by ErikEJ** [comment] 2022-04-05 16:43
Duplicate of #1243

**Comment by DavidCAllenMI** [comment] 2022-04-05 17:29
I may be dense here but where do I set the fmt only switch at? Is that in the db?

**Comment by ErikEJ** [comment] 2022-04-05 18:50
That is the stored procedure discovery method used when multiple result sets are enabled, but there are done limitations with this that must be fixed before it can become the default discovery method. That is what #1243 is about

**Closed** 2022-04-06 11:47 UTC

**Comment by DavidCAllenMI** [comment] 2022-04-06 13:09
I am at my wits end trying to figure out how to call a stored proc with multiple results coming back.

my normal method is like this but it fails with a dapper error complaining the reader is closed.

                var result = await _context.Procedures.USER_CHECK_EXISTS_PERSON_EFAsync(
                    p_user_id: requestVO.EntityIdentifier,
                    p_session_id: SessionId);

can you give me an idea. Sorry to respond on a closed issue, but I do not know how to just ask a question.

**Comment by DavidCAllenMI** [comment] 2022-04-06 13:33
traced the error to this line:                 _ = ((await reader.ReadAsync<USER_CHECK_EXISTS_PERSON_EFResult1>()).ToList(), (await reader.ReadAsync<USER_CHECK_EXISTS_PERSON_EFResult2>()).ToList());

as soon as it tries to execute it gives this error: "The reader has been disposed; this can happen after all data has been consumed\r\nObject name: 'Dapper.SqlMapper+GridReader'."

Is this an issue I need to create?

**Comment by DavidCAllenMI** [comment] 2022-04-06 13:42
I figured out how to mark for help now so I created a new one.

**Comment by CorsairRO** [comment] 2022-04-06 17:43
Hello @ErikEJ 

As i have already told you before i had a stripped version of your nice tool.
And there the FIRST change i made is to put back SP to use FMTONLY instead of sp_describe_first_resultset.

I have ALSO removed any dapper dependency and stuff.

How i approached it was to call the proc with FMTONLY ON, and just use FIRST Resultset from there and it works like i said in 100% cases of my SP, as opposite to 10% with describe stuff.

If you want i can try to look there and make another PR trying to help.

**Comment by ErikEJ** [comment] 2022-04-06 17:46
@CorsairRO This issue is closed and resolved, thanks.

How does your implementation of FMTONLY work with TVP parameters?

**Comment by CorsairRO** [comment] 2022-04-06 17:49
@ErikEJ : ok, i didnt know that is closed, sorry.
I will investigate the TVP parameters in the code and let you know right away.

**Comment by ErikEJ** [comment] 2022-04-06 17:50
@CorsairRO Thanks, if you can solve that, I will switch to using FMTONLY, as described in #1243

**Comment by CorsairRO** [comment] 2022-04-06 18:11
Hello @ErikEJ 👍 

I have tested now with a dummy sp and it is like this:
Returning a TVP from a SP => No problem
Passing a TVP to a SP => Get the following error in output:
Unable to get result set shape for PROCEDURE 'dbo.sp_test_tvp'
Operand type clash: nvarchar is incompatible with DBValidationResult

BUT, if i go to SSMS and call SET FMTONLYON AND run the SP then i have the result as i want there.
SO i think it is just to debug to see how execute in SSMS is different then in the tool ( in SP Scaffolder )

I will look there right away and let you know when i have fixed it.

**Comment by ErikEJ** [comment] 2022-04-06 18:14
@CorsairRO thanks, I know what the issue is. Looking for a solution...

**Comment by CorsairRO** [comment] 2022-04-06 18:18
@ErikEJ : OK, i will look there ASAP and let you know if i manage to find. Because of my stripped version there i can run it in no time and test different things until i am happy ( in the experimental instance and stuff )
