### ISSUE TITLE
Table Data Attribute in views

### ISSUE THREAD

**Issue by andreamorello93** [ErikEJ/EFCorePowerTools#1420] opened 2022-06-07 09:39 UTC
Is possible to add the Table Data Attribute in classes generated from Views during the scaffolding process?

 having that information inside the poco class and not only in the DbContext?

**Comment by ErikEJ** [comment] 2022-06-07 10:42
What have you tried?

**Comment by andreamorello93** [comment] 2022-06-07 10:48
in Db First, i've created a view and tried to scaffold the db with data attributes enabled. the poco classes generated for the tables are fine, they all contains the table attribute with schema. views seems not to have it in any cases. i've figured out that view name and schema are encapsulated inside the DbContext in the fluent API. 

What's strange about it is that EF code first allows you to creaate view poco class with table attribute. scaffold is omitting it.

**Comment by ErikEJ** [comment] 2022-06-07 12:02
It is by design, not needed for Keyless entities: https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs#L167

**Comment by andreamorello93** [comment] 2022-06-07 12:15
it would be wonderful to have it also inside the view. because that would permit to use the poco classes outside EF itself with other libraries or ORMs. all the classes bout Tables have it and i don't understand why "by design" EF Code First allows it and DB FIrst no. it's quite confusing. 

Aare you agree with me? it would be possible to implement this feature or not? thank you!

**Comment by ErikEJ** [comment] 2022-06-07 12:18
A view is not a table !?

**Comment by andreamorello93** [comment] 2022-06-07 12:24
yes but EF core doesn't make difference. it would be perfect if we could have an attribute for like View from EF but it uses Table atrtibute in any cases. For the view is optional. with this feature Power Tools could generate completely detached POCO classes from EF because it would contain all the informations

**Comment by ErikEJ** [comment] 2022-06-07 12:39
But why do you need the attribute?

**Comment by andreamorello93** [comment] 2022-06-07 15:15
because i'm using those classes with Dapper. and i'm using the poco classes to identify tables and schemas to query

**Comment by ErikEJ** [comment] 2022-06-13 12:23
@andreamorello93 I am having a closer look at this.

I noticed that Table attribute is only added if needed for normal entities - are you also asking for them to be always generated for those?

And do you also not need the constructor and the navigation properties?

And what about [Column()] atttribute - also only included now if the column property name does not match the database column name.

(I am think about creating "umbrella" plain POCO option that will cover all these requirements)

Bascially, pls share an example of how you would like you POCO classes to look.

**Comment by andreamorello93** [comment] 2022-06-13 20:31
it would be awesome to have all these features with an option in **Advanced** options and also for **Views** entities.

I would expecting something like this:

`
    [Keyless]
    [Table("viewPersons", Schema = "viewSchema")]
    public partial class ViewPersons
    {
        [Column("Id")]
        public int Id { get; set; }
        
        [Column("Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name{ get; set; }
        
        [Column("Surname")]
        [StringLength(50)]
        [Unicode(false)]
        public string Surname{ get; set; }
       
    }
`

**Comment by andreamorello93** [comment] 2022-06-13 21:15
The keyless attribute is generated automatically for views entities, that's why i've added it.

Yes of course it could be shorter! maybe **F.E.D.A.**  😁😁😁 i don't know
  
How a view could have any navigation props without FKs?... constructor could be useful too.

**Comment by ErikEJ** [comment] 2022-06-14 05:21
Could you show me an example of a table class?

**Comment by andreamorello93** [comment] 2022-06-14 05:30
```
    [Table("tbProducts", Schema = "awesomeSchema")]
    public partial class TbProducts
    {
        public TbProducts()
        {            
        }

        [Key]
        [StringLength(4)]
        [Unicode(false)]
        [Column("Code")]
        public string Code { get; set; };

        [StringLength(250)]
        [Unicode(false)]
        [Column("Description")]
        public string Description{ get; set; };
        
    }
```

**Comment by ErikEJ** [comment] 2022-06-18 12:12
Why do you need the empty constructor?

**Comment by andreamorello93** [comment] 2022-06-18 12:50
sorry, my fault. not needed

**Comment by ErikEJ** [comment] 2022-07-10 13:58
Moving to the backlog. Needs more design for a full solution for Dapper. Design proposal most welcome. @andreamorello93 @mikependon

**Closed** 2022-07-10 14:00 UTC
Labels: enhancement, reveng, blocked

**Comment by ErikEJ** [comment] 2022-12-30 12:44
@andreamorello93  @mikependon I have created an EF Core 7 t4 template, that implements some of the requirements above:
https://github.com/ErikEJ/EFCorePowerTools/blob/master/test/Ef7Playground/Ef7Playground/POCO/CodeTemplates/EFCore/EntityType.t4 - it can be updated to be "smarter" of course

**Comment by ErikEJ** [comment] 2023-02-26 15:46
@andreamorello93 The POCO template is now an option in the tool
