### ISSUE TITLE
EF Core Package did not load correctly

### ISSUE THREAD

**Issue by talley** [ErikEJ/EFCorePowerTools#1080] opened 2021-08-24 16:57 UTC
I am using the latest vs 2022 preview,i installed the package but vs does not load it correctly.
See attachment.
Thank You
![EFCorePowerToolsPackage did not load correctly](https://user-images.githubusercontent.com/6354720/130658345-da9acbae-d301-4005-a80c-064d7b68af9a.png)

![DbContextPakcage did not load](https://user-images.githubusercontent.com/6354720/130658383-4006f380-0c57-4197-970a-ef33e90b613e.png)

**Comment by ErikEJ** [comment] 2021-08-24 17:14
Please share your Activity log files, and a list of your installed extensions.

**Comment by aikidoshi** [comment] 2021-08-25 06:13
Hi Eric, I'm still having this trouble with the latest version on VS2022 Preview latest, but it works fine in VS2019 Preview, if that helps.
Regards,
Steve

**Comment by ErikEJ** [comment] 2021-08-25 06:16
@aikidoshi it does not, as I am unable to repro. Please share your Activity log files, and a list of your installed extensions.

**Comment by ErikEJ** [comment] 2021-08-25 06:31
Duplicate of #1046 I assume

**Comment by aikidoshi** [comment] 2021-08-25 07:49
[ActivityLog.xml.log](https://github.com/ErikEJ/EFCorePowerTools/files/7044862/ActivityLog.xml.log)
![Screenshot 2021-08-25 174714](https://user-images.githubusercontent.com/16281791/130749319-4653ab5f-27a6-4d8d-b4b7-921e5d23472f.png)

Sorry for the delay.

**Comment by aikidoshi** [comment] 2021-08-25 07:56
Yes, i just added more info to that ticket.

BTW: FYI - couldn't function without EF Core Power Tools! I love it.

 I work primarily on legacy systems or simple systems that mean I am always doing DB First, I have no choice.

Regards,

Steve
________________________________

**Comment by ErikEJ** [comment] 2021-08-25 11:03
@madskristensen Any suggestion for how to repro/troubleshoot this?

**Closed by ErikEJ** 2021-08-25 11:03 UTC
