### ISSUE TITLE
Latest version 2.5.1088 doesn't respect uppercase column names

### ISSUE THREAD

**Issue by rallets** [ErikEJ/EFCorePowerTools#1489] opened 2022-08-16 23:13 UTC
With the latest version 2.5.1088 a column with some uppercase chars is converted to camel case.
The previous version (2.5.1082?) kept the uppercase part unchanged.
I'am also using efpt.renaming.json

Thank you

### Provide steps to reproduce

Using a efpt.renaming.json

```
[
   {
      "ColumnPatternReplaceWith": "",
      "ColumnRegexPattern": "^(tbl)",
      "SchemaName": "dbo",
      "TablePatternReplaceWith": "$0Table",
      "TableRegexPattern": "^.+$",
      "Tables": [ ],
      "UseSchemaName": false
   }
]
```
and a DDL
```
CREATE TABLE [dbo].[Test](
	[ThisIsUPPERCASE] [nvarchar](7) NOT NULL
)
```
I expect to get 
Tablename: TestTable => OK
Column: ThisIsUPPERCASE => I get ThisIsUppercase

```
public partial class TestTable
    {
        public string ThisIsUppercase { get; set; } = null!;
    }
```

The only flag checked is `Use nullable reference types`.

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1088.0

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 17.3.1

**Comment by ErikEJ** [comment] 2022-08-17 05:17
Duplicate of #1486

**Comment by ErikEJ** [comment] 2022-08-17 05:29
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Closed by ErikEJ** 2022-08-17 05:29 UTC

**Comment by rallets** [comment] 2022-08-17 07:34
Hi @ErikEJ , just tried the daily build and I can confirm now it works as before. Thank you for a so fast support.
