### ISSUE TITLE
Method parameters for function and stored procedure calls are being renamed, creating code that doesn't compile

### ISSUE THREAD

**Issue by Ven-C** [ErikEJ/EFCorePowerTools#1622] opened 2022-12-19 21:13 UTC
In the generation of the *Context.Functions.cs and *Context.Procedures.cs files, the method parameter names are being renamed and no longer match the function or stored procedure parameter names when EF Core 7 is selected from the "Choose Database Connection" window.

### Provide steps to reproduce

Make sure that EF Core 7 is chosen from the "Choose Database Connection" window (seemingly maps to "CodeGenerationMode": 3 in the efpt.config.json).

Add a database function that has parameters with underscores in their names in the "Choose Database Objects" window.

Parameters of the generated methods for functions and stored procedures are being renamed (in my case, the underscores in the parameter names are being removed). 

The usages of the parameters are renamed for stored procedure calls, but not for functions, so the code does not compile for the functions. Whether the parameter names in the Action passed into DbContext.FromExpression need to match the database would probably decide whether it's better to (A) not rename the method parameters at all, or (B) also rename the usages to match the generated parameter names. 

Here's an example of a generated method for a database function where the parameter name is renamed, but the attempted usage is not:

```
[DbFunction("fnc_test", "dbo")]
public IQueryable<fnc_testResult> fnc_test(string modulename)
{
    return FromExpression(() => fnc_test(module_name));
}
```

Here's the efpt.config.json file used (minus the UiHint field):

```
{
   "CodeGenerationMode": 3,
   "ContextClassName": "EfTestContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": "Data",
   "OutputPath": "Data\/Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "EFCoreTest",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "[dbo].[fnc_test]",
         "ObjectType": 2
      }
   ],
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": true,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoConstructor": false,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": false,
   "UseSpatial": false,
   "UseT4": false
}
```

### Provide technical details

- EF Core version in use: EF Core 7.0.1

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1234.0

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment] 2022-12-20 06:34
This is caused by an annyoing bug in EF Core 7: https://github.com/dotnet/efcore/issues/29450 

I will try to implement a hotfix while waiting for a proper fix in 7.0.3

**Comment by ErikEJ** [comment] 2022-12-20 07:34
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Closed** 2022-12-20 07:34 UTC

**Comment by Ven-C** [comment] 2022-12-20 08:12
I just downloaded and tested the daily build and that worked perfectly for my config. My review for the tools should be up now as well - I greatly appreciate the quick fix and your work on the tools in general!
