### ISSUE TITLE
Postgres bool column reverse engineered to Nullable<bool>

### ISSUE THREAD

**Issue by gaborkalmar78** [ErikEJ/EFCorePowerTools#994] opened 2021-05-25 15:40 UTC
Describe what is not working as expected.
When a NOT NULL BOOL column has default TRUE value, it is reverse engineered to bool? instead of bool. 

### Steps to reproduce
CREATE TABLE a.t (
	column1 bool NOT NULL,
	column2 bool NOT NULL DEFAULT true,
	column3 bool NOT NULL DEFAULT false
);
Result:
public partial class T
    {
        public bool Column1 { get; set; }
        public bool? Column2 { get; set; }
        public bool Column3 { get; set; }
    }

EF Core Power Tools version: 2.5.649.0
Database engine: Postgres
Visual Studio version: Visual Studio 2019 16.9.5

**Comment by ErikEJ** [comment] 2021-05-25 17:12
Duplicate of #160 ? - just use the advanced option https://github.com/ErikEJ/EFCorePowerTools/issues/160#issuecomment-748051295

**Comment by gaborkalmar78** [comment] 2021-05-26 06:41
Yes, it is. Thank you.

**Comment by gaborkalmar78** [comment] 2021-05-26 07:07
The "Remove default constraint from bool columns" setting disappeared, may be this one is the same:
![image](https://user-images.githubusercontent.com/41337145/119615685-f6365c80-bdff-11eb-9382-4ff5fa15e77c.png)

Checked with the option, but EFPT still creating bool? properties.
may be BIT and BOOL columns are different.

Suggestion:
ReverseEngineerRunner line 195 from
.Where(column => column.StoreType == "bit"
to
.Where(column => (column.StoreType == "bit" || column.StoreType == "bool")

**Comment by ErikEJ** [comment] 2021-05-26 07:16
Interested in doing a PR?

**Comment by gaborkalmar78** [comment] 2021-05-26 07:48
Never wrote an extension, still trying to test my suggestion...
It would take me days to try.
If you have a test env and be able to test the change, please do it.

**Comment by ErikEJ** [comment] 2021-05-26 07:50
No worries I will do a PR

**Comment by gaborkalmar78** [comment] 2021-05-29 20:24
Successfully tested and corrected. Pls see [PR 998](https://github.com/ErikEJ/EFCorePowerTools/pull/998)

**Closed** 2021-05-30 05:52 UTC
