### ISSUE TITLE
[Feature Request] Reverse Engineer Re-run

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#89] opened 2018-08-26 23:54 UTC
In a DB-First development workflow, the **Reverse Engineer** function to run again and again when DB Schema changes.  Here are some feature requests to make this more awesome:

1. Provide an option to overwrite existing file when running **Reverse Engineer**.
2. Re-run **Reverse Engineer** without GUI support when right click on `efpt.config.json` file in the Solution Explorer.
3. Re-run **Reverse Engineer** in the  `efpt.config.json` when right click on the Text Editor.

### Further technical details
EF Core Power Tools version: 
```
Version 1.0.643.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes


SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes
```

Database engine: **SQL Server 2016 LocalDB**

Visual Studio version: **Visual Studio 2017 15.8.1**

**Comment by ErikEJ** [comment] 2018-08-27 16:17
Issue 1 looks like a duplicate of #38 

Problem with 2 and 3 is, that the data source information is not saved in the json file

**Comment by ErikEJ** [comment] 2018-09-25 17:46
Looks like there is nothing to do here, so closing

**Closed by ErikEJ** 2018-09-25 17:46 UTC
