### ISSUE TITLE
buttons don't appear

### ISSUE THREAD

**Issue by rakewell** [ErikEJ/EFCorePowerTools#1731] opened 2023-03-10 01:17 UTC
see comment for explanantion

**Comment by rakewell** [comment] 2023-03-10 01:51
Even setting font size to standard and Display Settings to 100% doesn't fix the issue: 

![image](https://user-images.githubusercontent.com/35868094/224202719-265ab21f-fc73-4580-9a3f-1523f694485b.png)

![image](https://user-images.githubusercontent.com/35868094/224202739-5c0c553f-77c6-4f6c-a83d-677654fb3611.png)

**Comment by ErikEJ** [comment] 2023-03-10 04:47
Duplicate of #1721

**Comment by ErikEJ** [comment] 2023-03-10 05:12
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Closed** 2023-03-10 05:12 UTC

**Comment by rakewell** [comment] 2023-03-10 05:32
thanks heaps, buttons are now there. One thing I notice is that the advanced tickbox doesn't pickup the saved setting so even though I untick it, next time I reverse engineer it is ticked:

![image](https://user-images.githubusercontent.com/35868094/224231880-53fa756e-1501-44ba-adeb-d56669e1d89f.png)

**Comment by ErikEJ** [comment] 2023-03-10 06:40
>>  next time I reverse engineer it is ticked:

New semi-breaking feature - see #1726 - you can disable via Tools/Options. Why would you not want to use DateOnly and TimeOnly?

**Comment by rakewell** [comment] 2023-03-10 22:48
Good point, there's no reason so I'll leave it on. Cheers!
