### ISSUE TITLE
How do I rename all tables ending with Data?

### ISSUE THREAD

**Issue by THammond9** [ErikEJ/EFCorePowerTools#255] opened 2019-09-06 15:50 UTC
The current pluralizer renames to Datum which I don't want but the legacy pluralizer has some issues as well. I see that there is a renaming file I can use but is seems that I have to put in every table that I want renamed. Not good when you want to add a table and forget about this extra steps that needs done (also we have a lot of tables that end in Data and I expect that trend to continue). So I was wondering if it is supported where we can say that a table with the name `*Data = Data`? Define a general rule rather than a specific rule.

**Comment by ErikEJ** [comment] 2019-09-06 15:52
I am not going to make any changes to the offered pluralizers. Have you tried the latest daily build (which uses Humanizer) ?

**Comment by ErikEJ** [comment] 2019-09-18 16:08
Please try the latest daily build, closing as duplicate of #251

**Closed by ErikEJ** 2019-09-18 16:08 UTC

**Comment by ErikEJ** [comment] 2022-12-26 10:51
Datum issue fixed in latest daily build
