### ISSUE TITLE
Change namespace of stored procedure generation

### ISSUE THREAD

**Issue by davidhendrickmb** [ErikEJ/EFCorePowerTools#1318] opened 2022-03-29 11:45 UTC
Hi,
Would it be possible to change the namespace of the stored procedures class? I have currently hard coded the namespaces I want in the DbContext.hs file and then models are in a Models subclass/folder. When I try to add a stored procedure, it's dropped into the Models namespace also and some references don't work.

Thanks,
David

**Comment by ErikEJ** [comment] 2022-03-29 13:04
Is this a duplicate of #1300 ?

**Comment by davidhendrickmb** [comment] 2022-03-29 13:11
It seems similar for sure. Even keeping the procedures in the same namespace as the DbContext would be helpful.

**Comment by ErikEJ** [comment] 2022-03-29 13:15
I think I need a small repro to fully understand your requirement, so I can get the implementation right

**Comment by ErikEJ** [comment] 2022-03-31 05:38
Ping?

**Comment by davidhendrickmb** [comment] 2022-03-31 08:33
Sorry. So in the DbContext.hbs if you hard code the name and then in the EntityTypes path set it to Data, the stored procedures file will create under the Data namespace and throw errors.

![image](https://user-images.githubusercontent.com/18259436/161012593-e63ec1c5-32ee-4edb-be10-a274ce4ab292.png)
![image](https://user-images.githubusercontent.com/18259436/161012774-ce91b30a-5dcc-4dca-be4d-bec3c2ba59ac.png)

**Comment by ErikEJ** [comment] 2022-03-31 08:50
I see "Models" in your screenshot. Should that be "Data" ?

**Comment by davidhendrickmb** [comment] 2022-03-31 09:03
Models is where are the normal data models for each entity go. So the namespace for those is MyProject.Data.Models. The namespace for the DB context is MyProject.Data and then the namespace for the stored procedures generated is MyProject.Data.Models, so they then have issues in finding functions etc.

**Comment by ErikEJ** [comment] 2022-03-31 09:10
I really need  a repro and explanation of desired namespaces and folder structure.

 Why do you hardcode the namespace in the hbs file  - Power Tools has no knowledge of that.

**Comment by davidhendrickmb** [comment] 2022-03-31 14:50
Hi Erik,

Please see solution attached. Let me know if you need sql schema.
My code refers to just the top level namespace, in this case MeetingsbookerSessionContext and all of the models are then in the models sub namespace.
You can see then in the MeetingsbookersessionContext.cs the OnModelCreatingGeneratedProcedures function can't resolve.

Let me know if there's a better way of structuring this.

[TestEfCoreApp (3).zip](https://github.com/ErikEJ/EFCorePowerTools/files/8390529/TestEfCoreApp.3.zip)


Thanks,
David

**Comment by ErikEJ** [comment] 2022-04-06 11:54
I see two MeetingsbookersessionContext.cs files and no call to  OnModelCreatingGeneratedProcedures in the supplied repro !?

**Comment by ErikEJ** [comment] 2022-04-08 15:37
Ping?

**Comment by ErikEJ** [comment] 2022-04-12 05:42
Closing this as a duplicate since no additional information was supplied

**Comment by davidhendrickmb** [comment] 2022-04-12 08:32
Hi @ErikEJ ,

Sorry about that, I think I uploaded the wrong copy and was out of the office. Please see the correct version attached here.
[TestEfCoreApp.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8471147/TestEfCoreApp.zip)

Thanks,
David

**Comment by ErikEJ** [comment] 2022-04-24 06:10
Changing the hardcoded namespace to TestEfCoreApp.Models solves everything !?

**Closed by ErikEJ** 2022-04-24 06:10 UTC

**Comment by davidhendrickmb** [comment] 2022-04-25 08:31
Hi @ErikEJ,
Yes, but I wanted to have the DBContext in the main namespace and keep all models in the Models namespace?

Thanks,
David

**Comment by ErikEJ** [comment] 2022-04-25 08:50
OK. That will work when #1300 is fixed, I think
