### ISSUE TITLE
bit not null created as bool?

### ISSUE THREAD

**Issue by mike-upshon** [ErikEJ/EFCorePowerTools#160] opened 2019-01-09 02:48 UTC
When a table has column with type bit not null EFCore PowerTools generates as bool? instead of bool

### Steps to reproduce
Create table with bit not null column and reverse engineer

### Further technical details
EF Core Power Tools version: 2.2.2.0

Database engine: SqlServer

Visual Studio version: Visual Studio Ent 2017 15.9.5

**Comment by ErikEJ** [comment] 2019-01-09 07:41
Hmmm. That should have been fixed in 2.2 - can you please share a CREATE TABLE script, thanks

**Comment by mike-upshon** [comment] 2019-01-10 22:40
Sorry for the delay have been travelling.
`
USE [Test]
GO

/****** Object:  Table [dbo].[Test]    Script Date: 11-Jan-19 11:37:32 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Test](
	[ID] [int] NOT NULL,
	[TestBool] [bit] NOT NULL,
 CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Test] ADD  CONSTRAINT [DF_Test_TestBool]  DEFAULT ((1)) FOR [TestBool]
GO


`

Test.cs
`
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EFBitTest.Model
{
    [Table("Test")]
    public partial class Test
    {
        [Column("ID")]
        public int ID { get; set; }
        [Required]
        public bool? TestBool { get; set; }
    }
}`


efpt.config.json
`
{
  "ContextClassName": "TestContext",
  "DefaultDacpacSchema": null,
  "IdReplace": true,
  "IncludeConnectionString": true,
  "OutputPath": "Model",
  "ProjectRootNamespace": "EFBitTest",
  "SelectedToBeGenerated": 0,
  "Tables": [
    {
      "HasPrimaryKey": true,
      "Name": "dbo.Test"
    }
  ],
  "UseDatabaseNames": false,
  "UseFluentApiOnly": false,
  "UseHandleBars": false,
  "UseInflector": true
}
`

**Comment by bricelam** [comment] 2019-01-10 22:50
``` sql
TestBool bit NOT NULL DEFAULT 1
```
This is by-design in EF Core. If the CLR property wasn't nullable, there would be now way to store a value of `false`.

Property type | SaveChanges when `null` | `false` | `true`
--- | --- | --- | ---
bool | (won't compile) | 1 (from DEFAULT) | 1
bool? | 1 (from DEFAULT) | 0 | 1

**Comment by bricelam** [comment] 2019-01-10 22:53
Note, if you remove the `HasDefaultValueSql()` configuration, you can make the property non-nullable.

**Comment by ErikEJ** [comment] 2019-01-11 06:37
Closing as by design

**Comment by ErikEJ** [comment] 2020-12-18 12:08
@rationalmonkey  @mike-upshon @smatvienko @rcfearn @StefanFalz  @roopeshkumar 

Fixed in latest daily build (two years in the making) 😄 

![image](https://user-images.githubusercontent.com/4169187/102612864-d0f74100-4131-11eb-8ef8-9a27dc4e1304.png)

**Closed** 2020-12-18 12:07 UTC
Labels: enhancement, reveng

**Comment by Mimis40** [comment] 2021-02-12 17:46
@ErikEJ - Would you be willing to add "Remove default constraint from bool columns" as a cli option?

**Comment by ErikEJ** [comment] 2021-02-12 17:48
To what CLI??

**Comment by Mimis40** [comment] 2021-02-12 17:50
We currently run this tool from the cli via the following command:
dotnet ef dbcontext scaffold

Listed here: [https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#generate-poco-classes-derived-dbcontext-and-mapping-for-an-existing-database](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#generate-poco-classes-derived-dbcontext-and-mapping-for-an-existing-database)

**Comment by Mimis40** [comment] 2021-02-12 17:53
Our specific use case for this flag comes into play with EF Migrations. When you add a bit column to a table with existing data, you need to provide a sql default. Every time we create a new migration, we run this tool to update our POCOs, but it keeps converting our columns to nullable booleans.

**Comment by ErikEJ** [comment] 2021-02-12 19:49
The repository is not that tool, that tool is in the official EF Core repository.

Suggest you post the request there, feel free to refer to this issue!

**Comment by Mimis40** [comment] 2021-02-12 19:59
Ah, apologies, I came from the EF Core repo, but didn't realized I had switched repos.

**Comment by ErikEJ** [comment] 2021-02-12 20:04
No worries, be aware that this feature is available in EF Core Power Tools
