### ISSUE TITLE
EF Core 6 Reverse engineer - Table list error

### ISSUE THREAD

**Issue by tomasfil** [ErikEJ/EFCorePowerTools#1209] opened 2021-12-07 15:23 UTC
Describe what is not working as expected.

NET5 works fine. I have ported everything to NET6 and now I am trying to run ReverseEngineer, but I am getting this error:
```
System.Exception: Table list error: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at ServiceProvider RevEng.Core.ServiceProviderBuilder.Build(ReverseEngineerCommandOptions options) in C:/Code/EFCorePowerTools/src/GUI/RevEng.Core/ServiceProviderBuilder.cs:line 198
   at new RevEng.Core.TableListBuilder(int databaseType, string connectionString, SchemaInfo[] schemas) in C:/Code/EFCorePowerTools/src/GUI/RevEng.Core/TableListBuilder.cs:line 35
   at int efreveng.Program.Main(string[] args) in C:/Code/EFCorePowerTools/src/GUI/efreveng/Program.cs:line 28

   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)
```

Please include a complete description that I can redo to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 5)
EF Core 6 

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.832.0

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
Oracle

Visual Studio version: (e.g. Visual Studio 2019 16.11)
Visual Studio 2019 16.11.7

**Comment by ErikEJ** [comment] 2021-12-07 15:40
Oracle support for EF Core 6 is not yet available, will be available in the latest daily build quite soon. Duplicate of #1106

**Closed by ErikEJ** 2021-12-07 15:40 UTC

**Comment by ErikEJ** [comment] 2021-12-07 16:27
@tomasfil Added to latest daily build

**Comment by tomasfil** [comment] 2021-12-07 16:37
@ErikEJ Awesome, going to download Nightly

**Comment by tomasfil** [comment] 2021-12-07 16:43
@ErikEJ  Still doesnt work:
![image](https://user-images.githubusercontent.com/34779382/145070038-9a1572fb-28c8-4b87-952f-665f5787b479.png)
![image](https://user-images.githubusercontent.com/34779382/145070108-45b022bb-c2da-482d-990e-ceb175711d25.png)
```
System.Exception: Table list error: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at ServiceProvider RevEng.Core.ServiceProviderBuilder.Build(ReverseEngineerCommandOptions options) in C:/Code/EFCorePowerTools/src/GUI/RevEng.Core/ServiceProviderBuilder.cs:line 212
   at new RevEng.Core.TableListBuilder(int databaseType, string connectionString, SchemaInfo[] schemas) in C:/Code/EFCorePowerTools/src/GUI/RevEng.Core/TableListBuilder.cs:line 35
   at int efreveng.Program.Main(string[] args) in C:/Code/EFCorePowerTools/src/GUI/efreveng/Program.cs:line 28

   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
```
![image](https://user-images.githubusercontent.com/34779382/145070230-ddba4c44-e9ae-4609-9800-23bbf4ce9d00.png)
![image](https://user-images.githubusercontent.com/34779382/145070266-2447ae26-22b3-4f33-a490-f9f81bacd566.png)
![image](https://user-images.githubusercontent.com/34779382/145070310-90ff9de8-7644-47dd-8e9f-7c5b4cf94c28.png)

**Comment by ErikEJ** [comment] 2021-12-07 17:00
I had a build failure, you need .856 or later, working on it

**Comment by ErikEJ** [comment] 2021-12-07 17:02
What you have installed in your project is irrelevant, btw

**Comment by ErikEJ** [comment] 2021-12-07 17:06
Build .857 is up now
