### ISSUE TITLE
Request - Add support for configuring file structure by schema

### ISSUE THREAD

**Issue by chassq** [ErikEJ/EFCorePowerTools#772] opened 2021-02-13 11:43 UTC
I would like to add another request to add support for configuring file structure by schema. We have hundreds of files (between model and configuration files) but because we cannot seem to designate a custom file structure (e.g. by schema) we currently have to reverse engineer to one project and move the changes manually to our actual DAL layer. This is fine when changes are light but when we have numerous DB changes or when EF Core Power Tools changes touch every file the process become super laborious. We want to organize by schema as it makes our DAL layer far more organized due to the large number of tables our DB contains.

If we had this feature we think we could simply target our DAL layer with EF Core Power Tools and not have to go through this tedious and time consuming process. If there is another way to do this we are all ears outside of writing some specialized VS plug-in.

Thanks for your consideration.

**Comment by ErikEJ** [comment] 2021-02-13 11:57
Do you really need all the tables in a single context? Why not split per schema, and have a config file per DbContext?

If not, this is duplicate of #158 which I just reopened.

**Comment by chassq** [comment] 2021-02-13 12:17
How would we run transactions across DB Context?

**Comment by ErikEJ** [comment] 2021-02-13 12:23
You have a lot of technical debt with that design, but it is certainly possible: https://docs.microsoft.com/en-us/ef/core/saving/transactions#cross-context-transaction

**Closed** 2021-02-13 12:24 UTC

**Comment by chassq** [comment] 2021-02-13 12:29
Yeah. Agreed. We probably do not want the technical debt of multi context.

**Comment by ErikEJ** [comment] 2021-02-13 12:32
Yeah, now you have the technical debt of a huge DbContext instead.

**Comment by chassq** [comment] 2021-02-13 12:36
Yeah but we have tables joined across schema. There are about 15 schemas too. So darned if we do and darned if we don't I guess. :-(. Maybe the EF Core team needs to think about this one? It would really be helpful for us on how best to approach this.

**Comment by ErikEJ** [comment] 2021-02-13 12:39
You should start over from scratch with 15 databases!

**Comment by chassq** [comment] 2021-02-13 12:41
Ha!
