### ISSUE TITLE
Fails to Generate DB Context over Large SQL Database

### ISSUE THREAD

**Issue by StephenNixey** [ErikEJ/EFCorePowerTools#620] opened 2020-11-28 11:48 UTC
Reverse Engineering fails with minimum details:
It does generate most of the code, fails to generate the DB Context Class.
Seems to have issues with some 'duplicates' and duplicates some field names on the generated entities.

The database is a large SQL server project.

Generated Message-box does not show.

This could be a DB issues causing the Generation to Crash so I will delve further into the database to see what I can remove to isolate this issue.

Stack Trace:
System.Exception: Reverse engineer error: 
System.InvalidOperationException: The foreign key {'UpdateById'} cannot be added to the entity type 'FeedBackTypes' because a foreign key on the same properties already exists on entity type 'FeedBackTypes' and also targets the key {'UserId'} on 'Users'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.Validate(IReadOnlyList`1 properties, Key principalKey, EntityType declaringEntityType, EntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey..ctor(IReadOnlyList`1 dependentProperties, Key principalKey, EntityType dependentEntityType, EntityType principalEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddForeignKey(IReadOnlyList`1 properties, Key principalKey, EntityType principalEntityType, Nullable`1 componentConfigurationSource, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddForeignKey(IReadOnlyList`1 properties, IMutableKey principalKey, IMutableEntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 114
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 68

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 27
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 112
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 51
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 264

### Steps to reproduce
Selections were:
'Models' in the Entity Types Path.
Include Connection String checked.
Install EF Core checked. 

### Further technical details
EF Core Power Tools version:
Version 2.5.277.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Server
Visual Studio version: Visual Studio 2019 16.8 using EFCore5.0

**Comment by ErikEJ** [comment] 2020-11-28 11:51
This is because you have a duplicate foreign key, as stated in the error message.

**Comment by ErikEJ** [comment] 2020-11-28 12:12
Duplicate of #594 /cc @smitpatel - yet another customer affected

**Closed by ErikEJ** 2020-11-28 12:12 UTC

**Comment by StephenNixey** [comment] 2020-11-28 16:47
Thank you for this, I will action at DB level to sort and re-run the rev-eng.
:-)
