### ISSUE TITLE
Reverse Engineer for EF Core 7 Crash

### ISSUE THREAD

**Issue by Rawheadrex** [ErikEJ/EFCorePowerTools#1627] opened 2022-12-22 16:08 UTC
Hi and thanks for your nice tooling !

So, my problem when I tried to Reverse Engineer upgrade on EF 7 (It's work fine with EF 6) , I have this error message : 

> System.InvalidOperationException: Reverse engineer error: 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at string Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.TransformText()
>    at string Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpModelGenerator.ProcessTemplate(ITextTransformation transformation)
>    at ScaffoldedModel Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
>    at ScaffoldedModel RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(string connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, bool removeNullableBoolDefaults, bool excludeNavigations, bool dbContextOnly, bool entitiesOnly, bool useSchemaFolders) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs:line 385
>    at SavedModelFiles RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List<string> schemas, string outputContextDir, string modelNamespace, string contextNamespace, string projectPath, string outputPath) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs:line 103
>    at ReverseEngineerResult RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/ReverseEngineerRunner.cs:line 88
>    at async Task<int> EfReveng.Program.Main(string[] args) in C:/Code/Github/EFCorePowerTools/src/GUI/efreveng/Program.cs:line 69
>    at ReverseEngineerResult EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(string output)
>    at async Task<ReverseEngineerResult> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetOutputAsync()
>    at async Task<ReverseEngineerResult> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunnerAsync(ReverseEngineerOptions options, CodeGenerationMode codeGenerationMode, Project project)
>    at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GenerateFilesAsync(Project project, ReverseEngineerOptions options, Tuple<bool, string> containsEfCoreReference, bool onlyGenerate)
>    at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)

### Provide steps to reproduce

I Use this setting : 
- Generate EntityTypes & DbContext
- Use Table name from DB option
- Use DataAnnotation option
- Advance: Nullable reference.
- Advance: Use many to many entity

I use the same setting with EF6 mode and it's work fine, but with EF7 is crash.
I use this setting with 2 others DB for EF7 and it's work fine.

I hope this informations will help you

### Provide technical details

- EF Core version in use:  **EF Core 7**

- Is Handlebars used: **no**

- Is T4 used: **no**

- Is .dacpac used: **no**

- EF Core Power Tools version:  **2.5.1236**

- Database engine: **SQL Server**

- Visual Studio version: **2022 17.4.3**

**Comment by ErikEJ** [comment] 2022-12-22 19:50
Duplicate of #1523

**Comment by Rawheadrex** [comment] 2022-12-22 23:34
Sorry my bad, I am not remove is:open filter. I'm looking at this other issue. Thanks

**Comment by ErikEJ** [comment] 2022-12-23 06:17
No problem. The related issue has some workarounds

**Closed** 2022-12-23 07:01 UTC
Labels: question
