### ISSUE TITLE
Bool types are generated as nullable

### ISSUE THREAD

**Issue by roopeshkumar** [ErikEJ/EFCorePowerTools#564] opened 2020-11-06 19:39 UTC
Hi,
    When I reverse engineer the models from the database, datatype (bit) not null in the database is being generated as Nullable(?) in the models. Am using EF Core power tools version  2.4.217.0

Thanks
Roopesh

**Comment by ErikEJ** [comment] 2020-11-07 05:12
Duplicate of #245

**Closed** 2020-11-07 05:12 UTC
