### ISSUE TITLE
Some issues were discovered during reverse engineering, consider addressing them:

### ISSUE THREAD

**Issue by fsoysall** [ErikEJ/EFCorePowerTools#2198] opened 2024-02-29 13:50 UTC
( So Good Tool )
how can edit running "your visual studio extension (EFCorePowerTools) " with "your source codes (EFCorePowerTools-master.zip) " ?
thx

Some issues were discovered during reverse engineering, consider addressing them:

System.NullReferenceException: Object reference not set to an instance of an object.
   at RevEng.Core.ReverseEngineerScaffolder.AppendSchemaNamespaceToDbcontext(String code, HashSet`1 codeFileNamespaces) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 370
   at RevEng.Core.ReverseEngineerScaffolder.AppendSchemaFoldersAndNamespace(IModel databaseModel, ScaffoldedModel scaffoldedModel, Boolean useSchemaFolders, Boolean useSchemaNamespaces, IEnumerable`1 schemas) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 345
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 506
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 86

**Comment by ErikEJ** [comment] 2024-02-29 13:54
In need more repro details? Maybe a duplicate of this: https://github.com/ErikEJ/EFCorePowerTools/issues/2110

**Comment by ErikEJ** [comment] 2024-03-03 13:34
Ping?

**Closed** 2024-03-04 07:10 UTC
Labels: question
