### ISSUE TITLE
New bug in version 2.6.632 in semantics of dbcontext procedures

### ISSUE THREAD

**Issue by tsoriano64** [ErikEJ/EFCorePowerTools#2671] opened 2024-11-27 11:48 UTC
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

The problem appears when reengineering from a SQL Server 2019 database where stored procedures are used.
In this scenario, the tool generates a partial class that does not semantically match the general dbContext.

This is a image of class dbContext general.
![image](https://github.com/user-attachments/assets/8197feed-ba4e-42a4-9b26-047d598c1253)

In this image you see a difference fron old version at a new version generated.
![image](https://github.com/user-attachments/assets/d801a400-153e-471e-957e-3a8dfb0959ff)

This change causes it not to compile properly.

Thanks.

### Provide technical details

- EF Core Power Tools version: 2.6.632

- Exact Visual Studio version: Visual Studio 2022 17.12.2

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment] 2024-11-27 12:15
@tsoriano64 Duplicate of #2644 - fixed in the latest daily build. (Plan to release to MarketPlace "soon")

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment] 2024-11-27 12:17
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Closed** 2024-11-27 12:16 UTC
Labels: bug, duplicate
