### ISSUE TITLE
Cannot reverse engineeer core2.1

### ISSUE THREAD

**Issue by gmmHls** [ErikEJ/EFCorePowerTools#138] opened 2018-11-28 23:31 UTC
Describe what is not working as expected.

System.Data.SqlClient.SqlException (0x80131904): 'CONCAT' is not a recognized built-in function name.
...
at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 158

### Steps to reproduce
standard Core 2.1 console app ( standard Visual Studio 2017 15.9.3 Core Console app template),
Right click on project, 
select Reverse Engineer in EF core Power tools
[ConsoleApp3.zip](https://github.com/ErikEJ/EFCorePowerTools/files/2626961/ConsoleApp3.zip)

Thanks for your help.
Gerhard
Gerhardm@olcentral.com

connect to DB, 
select some tables click OK
leave Entity types & DbContext selected
Include connection string & install EF Core provider is checked
click OK
and I get the error immediately in the output window. 

### Further technical details
Version 1.0.664.0

SQL Server Compact 4.0 in GAC - Yes - 4.0.8854.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQL Server 2008R)

Visual Studio version: (Visual Studio 2017 15.9.3)

**Comment by ErikEJ** [comment] 2018-11-29 09:31
Duplicate of #9

**Closed by ErikEJ** 2018-11-29 09:31 UTC
