### ISSUE TITLE
Handlebar templates does not work when target is "EF Core 6 (preview)"

### ISSUE THREAD

**Issue by jonnybee** [ErikEJ/EFCorePowerTools#1130] opened 2021-10-04 08:12 UTC
Handlebar template code gen are not used when target is EF Core 6.
I Suppose this should work as expected in VS 2022. 

### Steps to reproduce
Reverse enginer EF model from existing database. 

TargetFramework: net6.0 
"EF Core 6 (preview)" is target 
and check "Customize code using Handlebar templates" 

EF Core: v6.0.0-rc.1.21452.10 is referenced in project

Generated code should not have a default constructor when using Handlebar templates. 

If I change to target "EF Core 5" the Handlebar templates as used. 

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
Database engine: SQL Server
Visual Studio version: Visual Studio 2022 preview 4.1
EF Core PT: 2.5.786   (latest from nightly build)

There is no messages/compiler error for HBS templates in "Output" - "Extensions".

**Comment by ErikEJ** [comment] 2021-10-04 09:28
Duplicate of #1106

**Closed by ErikEJ** 2021-10-04 09:28 UTC
