### ISSUE TITLE
Separate handlebars project

### ISSUE THREAD

**Issue by alexgalie** [ErikEJ/EFCorePowerTools#1159] opened 2021-11-02 12:18 UTC
Hi, we have a large microservice-based project. We use EF Core as ORM but we have some QA settings enforced which prevent us from using the "reverse engineer" option out of the box (for example all of our classes are internal by default). 

I saw the handlebars feature which does the job but I would like to be able to share these templates among all services which use EF. The original handlebars project has [an "embedded templates" feature](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#embedded-templates) which doesn't seem to work with EF Core Power Tools (followed the steps from the original project but EFCPT does not apply any customization). 

Furthermore, if it worked it would be great if the `IDesignTimeServices` implementation could be read from the same templates project. This way, it could be packed as a nuget and used anywhere without further steps.

### Further technical details

EF Core 5

EF Core Power Tools version: 2.5.774.0

Database engine: SQL Server

Visual Studio version: 16.11.5

**Comment by ErikEJ** [comment] 2021-11-03 09:44
EF Core Power Tools does not interact with your project, this is by design - it is a standalone file generator.

That being said, the templates in use are currently loaded from a .zip file included with Power Tools, so maybe a tweak could be to let you (via efpt.config.json) specify the template .zip location.

**Comment by ErikEJ** [comment] 2021-11-05 07:44
@alexgalie Thoughts?

**Comment by alexgalie** [comment] 2021-11-05 09:49
Thanks for the reply, I understand now. This could work.

My scenario is a little complicated, we have multiple teams working on multiple repos. The standard way of sharing for us is nuget packages and the only solution I see right now is to have a build task which copies (or links) the templates to the project.

On the other hand, with the solution your proposed we could just put the templates in the root of each repo and point EFCPT to that location. My only concern in this case is that we'd have to share the config file in source control which wouldn't be a problem except for the server connection property.

I will leave this up to you if you think the effort is worth the value, this is not really a blocker for us.

**Comment by ErikEJ** [comment] 2021-11-05 12:56
I will make storing of UiHint optional via a general setting, thanks for the feedback on that!

I will leave this open, and see if more people need it.

**Comment by ErikEJ** [comment] 2021-11-06 13:13
Fixed in latest daily, also added option to not persist Ui Hint

**Closed** 2021-11-06 13:12 UTC
