### ISSUE TITLE
Unable to generate dacpac (and therefore entities/DB contexts) from SSDT project - suggestions for debugging?

### ISSUE THREAD

**Issue by IanKemp** [ErikEJ/EFCorePowerTools#1477] opened 2022-08-10 13:38 UTC
When attempting to generate entities from an SSDT project (`.sqlproj`) that produces a dacpac, an exception is thrown:

```
System.InvalidOperationException: Dacpac build failed, please pick the file manually
   at async Task<string> EFCorePowerTools.Extensions.EnvDteExtensions.BuildSqlProjAsync(string sqlprojPath)
   at async Task<DatabaseConnectionModel> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetDatabaseInfoAsync(ReverseEngineerOptions options)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)
```

As the database in question is a proprietary one, I obviously cannot provide it to allow you to debug. As such I would appreciate information/suggestions on how to debug this myself, so that I can provide more information as comments here to help you fix it and/or potentially submit a PR to resolve it.

### Provide steps to reproduce

Unable as this is a proprietary database.

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5

- Database engine: MSSQL 2017

- Visual Studio version: VS 2022

**Comment by ErikEJ** [comment] 2022-08-10 13:43
Does the project build without warnings when you build manually?

As the error message says, you can simply point to the .dacpac file on your disk:

    Dacpac build failed, please pick the file manually

**Comment by IanKemp** [comment] 2022-08-10 14:07
> Does the project build without warnings when you build manually?

There are three SQL71558 warnings; does the build fail unless there are neither errors nor warnings?

> As the error message says, you can simply point to the .dacpac file on your disk:
> 
> ```
> Dacpac build failed, please pick the file manually
> ```

Yes, this is not blocking me in any way, but the problem there is that every time a team member clones our repo into a different directory and runs the EF Core reverse engineering, the `UiHint` in the `efpt.config.json` changes, and then that file shows up as changed in source control and gets checked in.

We don't want to `.gitignore` that file because there are cases where someone adds a new entity and the file **should** be checked in, but conversely we don't want it to get checked in if it's only modified by the generator itself.

**Comment by ErikEJ** [comment] 2022-08-10 14:48
You can  disable the UI hint via Tools/Options.

And you should definitely add this file to source control.

**Comment by ErikEJ** [comment] 2022-08-10 14:49
Have you tested getting rid of the warnings?

**Comment by ErikEJ** [comment] 2022-08-11 05:46
Ping?

**Comment by ErikEJ** [comment] 2022-08-11 06:45
I had a closer look at the code, there could be some pitfalls (due to lack of programmatic control of database projects) - I will see if I can make this better

```csharp
            var searchPath = Path.Combine(Path.GetDirectoryName(project.FullPath), "bin");

            var files = Directory.GetFiles(searchPath, "*.dacpac", SearchOption.AllDirectories)
                .Where(f => !f.EndsWith("\\msdb.dacpac", StringComparison.OrdinalIgnoreCase)
                    && !f.EndsWith("\\master.dacpac", StringComparison.OrdinalIgnoreCase))
                .ToList();

            if (!await VS.Build.ProjectIsUpToDateAsync(project))
            {
                var ok = await VS.Build.BuildProjectAsync(project, BuildAction.Rebuild);

                if (!ok)
                {
                    throw new InvalidOperationException("Dacpac build failed");
                }
            }

            if (files.Count == 1)
            {
                return files[0];
            }

           throw new InvalidOperationException("Dacpac build failed, please pick the file manually");
```

**Comment by ErikEJ** [comment] 2022-08-11 06:58
Good news, I was able to reproduce locally!

**Comment by ErikEJ** [comment] 2022-08-11 06:59
Workaround is to clean the bin folder

**Comment by ErikEJ** [comment] 2022-08-11 09:00
I implemented a fix for this in the latest daily build, would be grateful if you could try it out.

I would be very grateful for a rating or review on Visual Studio Marketplace.

**Closed** 2022-08-11 08:59 UTC

**Comment by IanKemp** [comment] 2022-08-15 10:49
I can confirm that using the DACPAC works correctly in the latest nightly (2.5.1082), thank you - and you have your well-deserved review.
