### ISSUE TITLE
Using efpt.renaming.json for multiple tables only renames the first

### ISSUE THREAD

**Issue by BiggT76** [ErikEJ/EFCorePowerTools#354] opened 2020-03-16 17:45 UTC
We are using a database first approach which has duplicated table names across different schemas (i.e. `dbo.Jobs` vs `stg.Jobs`).  This is to store relevant data for SSIS staging vs the data itself.

I've configured the renaming file to rename these duplicated tables in the stg schema to `stg_{tablename}` (so `stg.Jobs` becomes `stg_Jobs`).  The issue is that only the first entry in the renaming file is actually being renamed.  Anything after that simply overwrites the default entity generated by EF Core with the data from the stg schema.

I've double checked the syntax based on this link [https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/efpt.renaming.json](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/efpt.renaming.json) and everything appears correct.

My renaming file (started with two just to test):

```
[
  {
    "UseSchemaName": false,
    "SchemaName": "stg",
    "Tables": [
      {
        "Name": "DeliveryAddress",
        "NewName": "stg_DeliveryAddress"
      }
    ]
  },
  {
    "UseSchemaName": false,
    "SchemaName": "stg",
    "Tables": [
      {
        "Name": "Jobs",
        "NewName": "stg_Jobs"
      }
    ]
  }
]
```

In this configuration my Jobs entity goes from:
```
 public partial class Jobs
    {
        public Jobs()
        {
            JobAddress = new HashSet<JobAddress>();
            OrderHeader = new HashSet<OrderHeader>();
        }

        [Key]
        [Column("JobID")]
        public int JobId { get; set; }
        [Column("LocationID")]
        public int? LocationId { get; set; }
        ...
```
to

```
    [Table("Jobs", Schema = "stg")]
    public partial class Jobs
    {
        [Column("id")]
        public long Id { get; set; }
        [Column("LogID")]
        public long LogId { get; set; }
        ...
```

Reordering the file will create the stg_Jobs entity correctly and overwrite DeliveryAddress.

### Further technical details
EF Core Power Tools version: 2.4.0

Database engine: SQL Server
Visual Studio version: 2019 - 16.5.0 Preview 5.0

**Comment by ErikEJ** [comment] 2020-03-16 18:21
Have you tried with useSchemsnsme as True?

**Comment by BiggT76** [comment] 2020-03-16 18:42
Yes, that seemed to work (sort of).  It would rename both tables following the `{schema}{entity}` format and ignore what I had in `"Tables"` section.

What was odd is once again, it was based on the setting from the first grouping.  When I updated first entry in the renaming file to `"UseSchemaName": true` I would end up with the following:
```
StgJobs
StgDeliveryAddress
```
even if I left that setting false for the subsequent tables.  That's why I made sure to double check my syntax because that was the first thing that came to mind.

**Comment by ErikEJ** [comment] 2020-03-16 18:45
I am not sure I understand - if anything is still not working, please provide CREATE TABLE scripts and your corresponding renaming,json file, and I will have a look.

**Comment by BiggT76** [comment] 2020-03-16 18:51
[ScriptsAndRenamingFile.zip](https://github.com/ErikEJ/EFCorePowerTools/files/4339866/ScriptsAndRenamingFile.zip)


Thanks for looking into this.

**Comment by ErikEJ** [comment] 2020-03-16 18:52
Thanks -  I will have a look - and could you clarify what is not working as expected?

**Comment by BiggT76** [comment] 2020-03-16 19:01
I'll try.  :)

Only the first entry in the renaming file gets created correctly when reverse engineering the models.  It's as if the second entry is either ignored or EF is getting confused by the duplicate table names.

**Comment by ErikEJ** [comment] 2020-03-17 19:19
It was a bug, thanks for helping me get to the root cause. I believe this is fixed in the latest daily build.

**Comment by ErikEJ** [comment] 2020-03-19 17:06
@BiggT76 Did you manage to verify the fix?

**Comment by BiggT76** [comment] 2020-03-19 17:40
Hmmm...I installed the nightly (v2.4.1) and now I'm getting this message when trying to scaffold:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at ReverseEngineer20.ReverseEngineer.ReplacingCandidateNamingService.<>c__DisplayClass3_0.<GenerateCandidateIdentifier>b__2(TableRenamer c)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ReverseEngineer20.ReverseEngineer.ReplacingCandidateNamingService.GenerateCandidateIdentifier(DatabaseColumn originalColumn)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.<GetPropertyName>b__17_1(DatabaseColumn c)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpNamer`1.GetName(T item)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpUniqueNamer`1.GetName(T item)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.GetPropertyName(DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumn(EntityTypeBuilder builder, DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumns(EntityTypeBuilder builder, ICollection`1 columns)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 235
```

**Comment by ErikEJ** [comment] 2020-03-19 17:46
with the exact renaming.json you shared?

I would be very grateful for a repro!

**Comment by BiggT76** [comment] 2020-03-19 17:51
I had went ahead using `"UseSchemaName": true`, so I recreated the file.  It should be the same though:
```
[
  {
    "UseSchemaName": false,
    "SchemaName": "stg",
    "Tables": [
      {
        "Name": "Jobs",
        "NewName": "stg_Jobs"
      }
    ]
  },
  {
    "UseSchemaName": false,
    "SchemaName": "stg",
    "Tables": [
      {
        "Name": "DeliveryAddress",
        "NewName": "stg_DeliveryAddress"
      }
    ]
  }
]
```

Perhaps I should mention that the project containing the models DOES NOT have EF installed.  Not sure if that has any bearing on the issue.

I can try and pair the system down to bare bones and send a copy if that will help.

**Comment by ErikEJ** [comment] 2020-03-19 17:53
I will try to repro and let you know

**Comment by BiggT76** [comment] 2020-03-19 17:56
FYI, tried scaffolding the context (which resides in the project containing EF) and I received the exact same error:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at ReverseEngineer20.ReverseEngineer.ReplacingCandidateNamingService.<>c__DisplayClass3_0.<GenerateCandidateIdentifier>b__2(TableRenamer c)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ReverseEngineer20.ReverseEngineer.ReplacingCandidateNamingService.GenerateCandidateIdentifier(DatabaseColumn originalColumn)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.<GetPropertyName>b__17_1(DatabaseColumn c)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpNamer`1.GetName(T item)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpUniqueNamer`1.GetName(T item)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.GetPropertyName(DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumn(EntityTypeBuilder builder, DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumns(EntityTypeBuilder builder, ICollection`1 columns)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 235
```

**Closed** 2020-03-19 19:53 UTC
