### ISSUE TITLE
Reverse Engineer - Temporal Tables: Entities missing Period start column/Period end column

### ISSUE THREAD

**Issue by steras9** [ErikEJ/EFCorePowerTools#1259] opened 2022-01-24 15:35 UTC
### Steps to reproduce

* Have a SQL Server database with temporal tables
* Do a reverse engineering with EF Core Power Tools, Entities only!
* Check that the colums named ValidFrom and ValidTo are generated to the entities
* Find that they are missing :-(
* BTW: Context generation works fine even renaming of these columns from standard.

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.877

Database engine: SQL Server

Visual Studio version: Visual Studio 2022 17.0.5

**Comment by ErikEJ** [comment] 2022-01-24 16:23
HIDDEN ?

So generation everything includes the columns?

Can you share the CREATE TABLE statement?

**Comment by steras9** [comment] 2022-01-25 08:08
Not hidden, but autogenerated:

```
CREATE TABLE [Note] (
    [Note_id]                           UNIQUEIDENTIFIER                            CONSTRAINT [DF_Note_NoteId] DEFAULT (newid()) NOT NULL,
    [Uuid]                              UNIQUEIDENTIFIER                            DEFAULT (newid()) NOT NULL,
    [NoteTitle]                     	NVARCHAR (255)                              NOT NULL,
    [NoteDescription]               	NVARCHAR (MAX)                              NULL,
    [NoteExpires]                   	DATETIME2 (7)                               NULL,
    [CreatedBySid]                      NVARCHAR (255)                              NOT NULL,
    [CreatedByLoginName]                NVARCHAR (255)                              NOT NULL,
    [CreatedAt]                         DATETIME2 (7)                               DEFAULT (getutcdate()) NOT NULL,
    [ModifiedBySid]                     NVARCHAR (255)                              NOT NULL,
    [ModifiedByLoginName]               NVARCHAR (255)                              NOT NULL,
    [ModifiedAt]                        DATETIME2 (7)                               DEFAULT (getutcdate()) NOT NULL,
    [ValidFrom]                         DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo]                           DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    [VerCol]                            ROWVERSION                                  NOT NULL,
    CONSTRAINT [PK_Note] PRIMARY KEY NONCLUSTERED ([Note_id] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[NoteHistory], DATA_CONSISTENCY_CHECK=ON));
```

When I create the DBContext (also by itself) fluent API is generated correctly. But I need the column ValidFrom in the entity.

BTW: Works with setting "EF Core 3" for entity generation.

Thank you for having a look at it.

**Comment by ErikEJ** [comment] 2022-01-25 10:06
Probably by design - @ajcvickers ?

**Comment by ajcvickers** [comment] 2022-01-25 10:10
Tracked by https://github.com/dotnet/efcore/issues/26463

**Comment by ErikEJ** [comment] 2022-01-25 17:06
Closing as external

**Closed by ErikEJ** 2022-01-25 17:06 UTC
