### ISSUE TITLE
Missing HasKey() for one table

### ISSUE THREAD

**Issue by TimKras** [ErikEJ/EFCorePowerTools#1256] opened 2022-01-22 16:15 UTC
We have table with a PK:
![image](https://user-images.githubusercontent.com/5257192/150646535-862bda09-13bf-4e65-9085-b3f2ea6f63fe.png)

The PK column is also 'renamed' (to preserve de uppercase of ID) [not sure if this is relevant]
![image](https://user-images.githubusercontent.com/5257192/150646581-2e40cdf0-2c46-454d-8de5-e791dd6828ab.png)

But in the modelbuilder there is no HasKey() record.
![image](https://user-images.githubusercontent.com/5257192/150646636-a1997e29-e17c-44c0-8114-41e788436bdd.png)

There should be one, because the name of de PK is not TableName+Id.

This is resulting in a runtime error. Fixed it temporary in the OnModelCreatingPartial method.

**Comment by ErikEJ** [comment] 2022-01-22 16:34
Are you using Handlebars?

**Comment by ErikEJ** [comment] 2022-01-22 16:41
Duplicate of #1250 ?

**Comment by TimKras** [comment] 2022-01-22 16:45
Indeed duplicate of #1250

**Closed** 2022-01-22 16:52 UTC

**Comment by ErikEJ** [comment] 2022-01-23 07:29
Fixed in latest daily
