### ISSUE TITLE
Tables with multi-line comments scaffold as uncompilable code.

### ISSUE THREAD

**Issue by KeyboardG** [ErikEJ/EFCorePowerTools#653] opened 2020-12-11 03:58 UTC
The entity scaffold template **class.hbs** templates table comments with the triple slash, but any table that has multi-line comments will then end up across an equal amount of lines in the resulting C# code with only the first line commented. This results in the comment text not inside a comment, but in the code resulting in classes that can not compile.

To get it working I've generally modified the templates to remove comments from the entities. There doesn't appear to be a way to keep them out of the generated context's OnModelCreating, but its just lines and lines of bloat there, not causing issues. Maybe a second request for that.

Thanks.

### Steps to reproduce
Scaffold from tables with a comment containing line breaks / several lines of text. This could be common when the database is generated from DBA / Design tools which include documentation.
![CommentError](https://user-images.githubusercontent.com/1760835/101860094-094bbd80-3b3b-11eb-9786-4fc85cc6d568.png)

### Further technical details
EF Core Power Tools version: 2.4.217.0

Database engine: Microsoft SQL Server

Visual Studio version: 2019 16.8.2

**Comment by ErikEJ** [comment] 2020-12-11 06:04
Duplicate of #643 - notice that this update will require new templates (so rename/delete your current codetemplates folder)

**Closed** 2020-12-11 06:04 UTC

**Comment by ErikEJ** [comment] 2020-12-11 06:27
Fixed in latest daily build, please let me know if that solves your issue

**Comment by KeyboardG** [comment] 2021-04-04 03:11
Finally got to upgrade the tooling at work and test this. Looks good! Thanks. While I edited the templates for entites to skip comments, there was no way to block them from being generated in the Context.OnModelCreating method. This lead us to ultimately strip comments from the development database.

**Comment by ErikEJ** [comment] 2021-04-04 05:29
Why did you end up removing comments, I do not understand, and cannot see how this relates to this issue.

**Comment by KeyboardG** [comment] 2021-04-06 13:12
It doesn't relate to this issue directly. 
I was just mentioning in case by chance it was something already being thought about, that comments in the database will end up in OnModelCreating(), in our case pages and pages of strings. If I wanted not to have comments from the database end up in the C#, I could prevent them from being in the individual entity classes by editing the handlebar templates, but no way to keep them out of the OnModelCreating() function. To solve that, I just stripped db comments out before generating.

Not sure if that is in the works, or if its worth creating a GH Issue for.

**Comment by ErikEJ** [comment] 2021-04-06 13:28
@KeyboardG "pages and pages of strings" ---  wow!

EF Core does not provide an opt-out of comments, and in EF Core 6, comments are always scaffolded as XML documentation.

So what you are asking for is basically to completely ignore any comments coming from MS_Description, as you have "pages and pages of strings" in them?

Suggest you create an issue for it, it is definitely possible to provide a PR to ignore them.

**Comment by KeyboardG** [comment] 2021-04-06 14:00
Thanks Erik, I'll put an item, even if its not big enough to warrant the effort. 
Our workflow is currently like this because our development database is generated from modelling tools from our DBA who has lots of explanation and business rules that generate out into the MS_Descriptions.
