### ISSUE TITLE
When using DataAnnotations, the primary key attribute is missing

### ISSUE THREAD

**Issue by calloncampbell** [ErikEJ/EFCorePowerTools#63] opened 2018-06-28 16:05 UTC
When using Data Annotations to reverse engineer, the primary key attribute is missing for the generated entities.

I had to add [Key] to my primary key properties to get my solution to work at runtime. 

### Steps to reproduce
1. Reverse engineer
2. Select tables
2. Enable "Use DataAnnotation attributes to configure the model
3. Press OK to generate the models

### Further technical details
EF Core Power Tools version: Version 1.0.604.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2017 15.7.x

**Comment by calloncampbell** [comment] 2018-06-28 16:36
Here is a sample model generated:


using System;

using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;

using System.ComponentModel.DataAnnotations.Schema;



namespace MyCompany.Entities.SqlServer

{

    [Table("GroupTier")]

    public partial class GroupTierEntity

    {

        public GroupTierEntity()

        {

            OrgGroups = new HashSet<OrgGroupEntity>();

        }



        [Key]

        [Column("GroupTierID")]

        public int GroupTierId { get; set; }



        [Column("OrganizationID")]

        public int OrganizationId { get; set; }



        public int TierLevel { get; set; }

    }

}

If I remove the [Key] attribute and run my sample app I get the following System.InvalidOperationException at tuntime:
"The entity type 'GroupTierEntity' requires a primary key to be defined.”

Callon

________________________________

**Comment by calloncampbell** [comment] 2018-06-28 16:41
I removed the [Key] attribute and renamed my property GroupTierId to just Id and ran my app and it worked. Next time I'll select the option to use 'ID' as my keys. I opted not to use this because it's in preview.

**Comment by ErikEJ** [comment] 2018-06-28 18:36
I need the table create script also..

**Comment by calloncampbell** [comment] 2018-06-28 20:31
CREATE TABLE [dbo].[GroupTier] (
    [GroupTierID]         INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OrganizationID]      INT           NOT NULL,
    [TierLevel]           INT           NOT NULL,
    [Name]                VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_GroupTier] PRIMARY KEY CLUSTERED ([GroupTierID] ASC) WITH (FILLFACTOR = 80)
);

**Comment by ErikEJ** [comment] 2018-07-02 16:41
The name of the class should be GroupTier - not **GroupTierEntity** - where does that come from??

Or  the key property must then be named: GroupTierEntityId

**Comment by calloncampbell** [comment] 2018-07-02 20:57
Yes originally the class name was GroupTier, but I then started to play around with the custom code templates included. I wanted my generated entities to be that, an entity. So it made sense to call the classes GroupTierEntity. Making this customization mostly works, but there were a few tweaks I needed to do after the code generation, but nothing major.

The issue of the name of the Id field was an issue prior to me using the templates as I tried both approaches.

Callon

________________________________

**Comment by ErikEJ** [comment] 2018-07-03 05:21
Given your original description, I am unable to reproduce (you did not mention any renaming of classes!) - so I would like you to provide a runnable project, that reproduces the issue.

**Comment by ErikEJ** [comment] 2018-07-04 18:33
Closing as no repro received, feel free to re-open if you can provide a repro

**Closed by ErikEJ** 2018-07-04 18:33 UTC

**Comment by EnricoReich** [comment] 2018-08-23 15:56
Hello,

Unfortunately, I have the same problem with the reverse engineer function.

- Windows 10 1803
- VS2017 15.8.1
- .Net core SDK 2.1.401
- MSSQL-Server 2017 Developer Edition
- EF Core PowerTools 1.0.644 (same problem with 1.0.643)
- Microsoft.EntityFrameworkCore.SqlServer 2.1.1 or 2.1.2

## Steps to reproduce
1. Create a simple .Net Core console application project in VS
2. Start sql server
3. SQL-Server: Create database 
4. SQL-Server: Create table:

```
CREATE TABLE Person (
    Id int IDENTITY(1,1) NOT NULL,
    Name nvarchar(60) NOT NULL,
    PRIMARY KEY (Id)
)
```

5. VS: reverse engineer the table into a model with EF Core Power Tools, select "EntityTypes only" and enable "Use DataAnnotation attributes to configure the model" on the 'Generate EF Core Model' Dialog

6. Hit OK

## Result (Class)
```
public partial class Person
    {
        public int Id { get; set; }
        [Required]
        [StringLength(60)]
        public string Name { get; set; }
    }
```
DataAnnotation attribute [KEY] is mising at **Id** but it is clearly a primary key.

**Comment by ErikEJ** [comment] 2018-08-23 16:10
@EnricoReich this is by design, as the Id property is the key by convention, so no attribute needed

**Comment by EnricoReich** [comment] 2018-08-23 16:51
Erik, you are absolutely right!
I did not think about this behavior anymore because normally I write code first and then migrate always using the [Key] attribute simply because of code consistency and understandability (to make it clear for other students which are not typical programmers).
Sorry, about that. :)

**Comment by yomer** [comment] 2019-02-13 21:16
Erik,
    I'm having this bug randomly when doing a reverse engineering on my DB. I have for example two tables with a Primary Key each. They are not named "Id", but after the process is complete, one entity has the [key] annotation and the other doesn't. It seems to be random. Checking other entities, the underscore in the name of the Primary Key doesn't seem to affect the outcome.

EFCorePowerTools: 2.2.12
Visual Studio 2017 v15.8.7
.NET Core 2.1.4

![capture20190213150924173](https://user-images.githubusercontent.com/1246242/52744181-9a829500-2fa1-11e9-9aa4-415a9d1233cf.png)
![capture20190213150957359](https://user-images.githubusercontent.com/1246242/52744182-9a829500-2fa1-11e9-9363-a9d41304f59c.png)
![capture20190213151024039](https://user-images.githubusercontent.com/1246242/52744183-9a829500-2fa1-11e9-886f-ba9f0dc844c8.png)
