### ISSUE TITLE
Run Reverse Engineer from cmd?

### ISSUE THREAD

**Issue by biiiipy** [ErikEJ/EFCorePowerTools#532] opened 2020-10-13 14:22 UTC
Is it possible to run the same reverse engineer that gets executed from Power Tools UI, but from command line or from nuget package lib? We would like to automate this stuff... 
In the docs I saw an example for reverse engineering from dacpac, but not regular DB.
I could use built in EF core CLI, but would like to keep compatibility with EF Core Power Tools, and also use advanced features of Power Tools. It should use settings from efpt.config.json.

**Comment by ErikEJ** [comment] 2020-10-13 15:00
What you saw in relation to .dacpac was for the EF Core CLI.

Duplicate of #340 , where I also [reveal some of the internals](https://github.com/ErikEJ/EFCorePowerTools/issues/340#issuecomment-670929754) of the documented EF Core Power Tools command line tool. the .config file format used is very similar to efpt.config.json, but with some additions.

**Closed by ErikEJ** 2020-10-13 15:00 UTC

**Comment by ErikEJ** [comment] 2023-03-27 06:54
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.

**Comment by ErikEJ** [comment] 2023-04-25 11:26
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)

**Comment by biiiipy** [comment] 2023-04-25 12:45
Fantastic!

**Comment by ErikEJ** [comment] 2023-04-25 13:32
@biiiipy Thanks - please give it a try and provide any comments and suggestions

**Comment by SethVanderZanden** [comment] 2023-12-08 15:05
Hey, @ErikEJ is there a plan to do a refresh as well? I love this tool but I use Rider IDE so I constantly relaunch Visual Studio to refresh. Big fan of the project!

**Comment by ErikEJ** [comment] 2023-12-08 15:11
@SethVanderZanden Not sure what you mean? New version?
