### ISSUE TITLE
Support PostgreSQL functions reverse engineer 

### ISSUE THREAD

**Issue by ignacioinnovo** [ErikEJ/EFCorePowerTools#902] opened 2021-04-03 14:28 UTC
First of all, let me congratulate for this great project!

I want to propose the addition of reverse engineer of the PostgreSQL functions as it can be done with MSSQL with the GUI assistant.

Perhaps you have been working on that so, please, update me with the news.

I have a little repository with some code to generate functions from a defined table (https://github.com/InnovoTecnologias/PostgresqlAutogeneration) but I can write some code to do the reverse engineer.

¡Thank you in advanced!

**Comment by ErikEJ** [comment] 2021-04-03 15:16
Start by having a look at how it is done here...

**Comment by ignacioinnovo** [comment] 2021-04-04 11:00
@ErikEJ, thank you for your response.

I have been diving into the code and I think I should create a NpgsqlServerFunctionScaffolder implementing IFunctionScaffolder and NpgsqlServerFunctionModelFactory implementing IFunctionModelFactory under RevEng.Core.50\Functions. Is this right? Is there any documentation or could anyone point me in the right direction?

**Comment by ErikEJ** [comment] 2021-04-04 14:04
That would work for scalar functions, which is probably a good place to start.

Does postgress support stored procedures?

**Comment by ignacioinnovo** [comment] 2021-04-04 15:06
Yes, since version 11.

**Comment by ErikEJ** [comment] 2021-04-10 14:11
Closing as duplicate of #697

**Closed by ErikEJ** 2021-04-10 14:11 UTC
Labels: enhancement, reveng
