### ISSUE TITLE
Make optional arguments for Stored Procedures optional in the generated .NET method

### ISSUE THREAD

**Issue by 0liver** [ErikEJ/EFCorePowerTools#1910] opened 2023-08-03 13:14 UTC
### Provide steps to reproduce

I have a stored procedure defined as follows:

```sql
create procedure dbo.SpMapGet(
	@NodeId int,
	@Debug int = null
) as begin
     // ...
end
```

When I create the model for this using the version detailed below, the generated method has the following signature:

```csharp
public virtual async Task<TResult> SpMapGetAsync(
    int? NodeId,
    int? Debug,
    OutputParameter<int> returnValue = null,
    CancellationToken cancellationToken = default)
{
    // ...
}
```

What I would like to see is `Debug` becoming an optional parameter there, too, just like in the SQL statement:

```diff
public virtual async Task<TResult> SpMapGetAsync(
    int? NodeId,
-    int? Debug,
+    int? Debug = null,
    OutputParameter<int> returnValue = null,
    CancellationToken cancellationToken = default)
{
    // ...
}
```

Is this something that you would consider implementing?

### Provide technical details

- Exact Visual Studio version: Visual Studio 2022 17.6.5

- EF Core Power Tools version: 2.5.1544

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: ?

**Comment by ErikEJ** [comment] 2023-08-03 13:48
Can I detect that the parameter is optional by looking at meta data?

**Comment by ErikEJ** [comment] 2023-08-03 14:40
Possible duplicate of #711

**Closed** 2023-08-03 18:16 UTC

**Comment by 0liver** [comment] 2023-08-08 12:34
Thanks for looking into this, @ErikEJ. It's a pitty, there's no info about this.

**Comment by ErikEJ** [comment] 2023-08-08 12:42
You are welcome.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
