### ISSUE TITLE
Bug when NOT NULL bit field with default value of 1

### ISSUE THREAD

**Issue by jaimestuardo** [ErikEJ/EFCorePowerTools#2004] opened 2023-11-16 12:22 UTC
**Steps to reproduce**

In SQL Server, create a table which contains a BIT NOT NULL field. Assign a default value of 1 and save the table.

Then, generate the model in Visual Studio (reverse engineer).

**Current result**

The BIT field become a nullable bool type (bool ?).

**Expected result**

The BIT field to become a bool type, not accepting nulls.

If I set the BIT Field as NOT NULL but with default value of 0 or no default value, model generation works as expected.

**Technical details**

- EF Core Power Tools version: 2.5.1648

- Exact Visual Studio version: Microsoft Visual Studio Community 2022 (64 bits) - Current Version 17.7.4

- Database engine: SQL Server

- EF Core version in use: EF Core 7.0.11

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment] 2023-11-16 13:05
Duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/160#issuecomment-453286573 - there is an advanced option to disabel this, see th wiki

**Closed by ErikEJ** 2023-11-16 13:05 UTC
