### ISSUE TITLE
EF Core Power Tools stopped working

### ISSUE THREAD

**Issue by hvilppu** [ErikEJ/EFCorePowerTools#962] opened 2021-05-05 18:06 UTC
EF Core Power Tools stopped working

### Steps to reproduce
Right-click project -> Ef Core Power Tool -> Reverse engineer --> Nothing happens, no errors
(Also other selections not work) 
I think auto-update broke this

### Further technical details
EF Core Power Tools version: 2.5.636

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2019 Version 16.8.4)

**Comment by ErikEJ** [comment] 2021-05-05 18:08
Duplicate of #960 ?

And thanks for using the daily build!

**Comment by ErikEJ** [comment] 2021-05-05 18:55
Ping?

**Comment by hvilppu** [comment] 2021-05-05 19:21
Yeh. That it was. But I did not got any errors. This can be closed now as duplicate

**Closed** 2021-05-05 19:27 UTC
