### ISSUE TITLE
UseDateOnlyTimeOnly = false seems to not be respected when reverse engineering

### ISSUE THREAD

**Issue by ilGianfri** [ErikEJ/EFCorePowerTools#2002] opened 2023-11-15 11:41 UTC
Hello,
I'm using the latest version with EF Core 8, I have set "UseDateOnlyTimeOnly": false in the efpt.config.json to avoid having DateOnly/TimeOnly for now.
When I run reverse engineering, it still uses DateOnly and TimeOnly.

### Provide steps to reproduce a bug

- Reverse engineering -> select .dacpac and EF Core 8
- Select Tables/Views etc
- Complete reverse engineering
- Notice it still used DateOnly/TimeOnly

### Provide technical details

- EF Core Power Tools version: 2.5.1678

- Exact Visual Studio version:  Visual Studio 2022 17.9 Preview 1

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: yes

**Comment by ErikEJ** [comment] 2023-11-15 11:52
@ilGianfri Please share a CREATE TABLE script for a relevant table

**Comment by ilGianfri** [comment] 2023-11-15 12:02
`CREATE TABLE [dbo].[INTERNO_CAMBIO_FASCIA] (
    [ID_CAMBIO_FASCIA] INT  IDENTITY (1, 1) NOT NULL,
    [LEG_PRATICA]      INT  NULL,
    [LEG_FASCIA]       INT  NULL,
    [DATA_START]       DATE NULL,
    [DATA_END]         DATE NULL,
    [LAST_VERSION]     BIT  NULL,
    PRIMARY KEY CLUSTERED ([ID_CAMBIO_FASCIA] ASC),
    CONSTRAINT [FK_INTERNO_CAMBIO_FASCIA_INTERNO_FASCE] FOREIGN KEY ([LEG_FASCIA]) REFERENCES [dbo].[INTERNO_FASCE] ([ID_FASCIA]),
    CONSTRAINT [FK_INTERNO_CAMBIO_FASCIA_PRATICA] FOREIGN KEY ([LEG_PRATICA]) REFERENCES [dbo].[PRATICA] ([CODICE_PRATICA])
);`

Here's a simple table where I see this happening. DATA_START and DATA_END are DateOnly once reverse engineering is done.

**Comment by ErikEJ** [comment] 2023-11-15 12:29
I am not able to reproduce... Can you provide a full repro (privately) ?

**Comment by ErikEJ** [comment] 2023-11-15 13:02
Ah - dacpac!

**Comment by ErikEJ** [comment] 2023-11-15 13:05
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Closed** 2023-11-15 13:04 UTC

**Comment by ilGianfri** [comment] 2023-11-15 14:24
I just tried build .1680 and I confirm it's fixed. Thanks!
