### ISSUE TITLE
[Question] Will EFCore PT get support for Firebird Sql too?

### ISSUE THREAD

**Issue by heischo** [ErikEJ/EFCorePowerTools#574] opened 2020-11-12 09:39 UTC
Hei Erik.
I use Firebird Sql, because I need the triggered event support in this database. At this time I only use Dapper MicroORM. 
There exists also a driver for EF Core - so in case your fantastic product will get support for Firebird Sql I wish to start using EF Core together with your Power Tools. 
Hilsen fra Norge :-) 
/Heiko

**Comment by ErikEJ** [comment] 2020-11-12 09:50
There are some challenges, but a PR would be accepted - duplicate of #288

**Closed by ErikEJ** 2020-11-12 09:50 UTC
