### ISSUE TITLE
Reverse Engineer and .net Core 5.0.1

### ISSUE THREAD

**Issue by dchillman123** [ErikEJ/EFCorePowerTools#642] opened 2020-12-08 18:37 UTC
Describe what is not working as expected.
I have a .net core application referencing version 5.0.1 of the entity framework. Suddenly, when I reverse engineer, random tables are some of selections are not engineered and a random selection of tables which were not selected are engineered - playing havoc with my models.
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
not exactly sure - all i really did was update the .net core nugets to 5.0.1 from 5.0
### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.377.9
Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server
Visual Studio version: (e.g. Visual Studio 2017 15.7)
Visual Studio 2019 16.7.7

**Comment by ErikEJ** [comment] 2020-12-08 18:41
Could you please try to use the official release?

And more details would be nice, so we can get the bug fixed.

**Comment by dchillman123** [comment] 2020-12-08 18:45
pardon my ignorance, but I am not sure what you mean by official release - I am using NuGet and Extensions from Visual Studio.

**Comment by ErikEJ** [comment] 2020-12-08 18:47
The version of the Power Tools you use is the latest daily build, not the official build from VS MarketPlace

**Comment by dchillman123** [comment] 2020-12-08 19:22
thank you for the quick response - using the official version resolved the issue.

**Comment by ErikEJ** [comment] 2020-12-08 19:28
I would be very grateful if you could provide details about the issue you encountered

**Comment by dchillman123** [comment] 2020-12-08 19:56
it seems to be related to selecting the "Use EF Core 5" option,  then selecting the "Use DataAnnotation attributes....".

If I first reverse engineer without those options, the model gets created as expected.  If I then reverse engineer with those options, all hell breaks loose and there is no telling which tables will be generated.  This occurs with the official version as well.

**Comment by ErikEJ** [comment] 2020-12-08 19:59
Thanks, I will try to replicate..

**Comment by ErikEJ** [comment] 2020-12-08 20:19
Are you seeing that some entities no longer appear in the Model creating code in your DbContext?

**Comment by dchillman123** [comment] 2020-12-08 20:35
yes, some entities disappear, and some entities that were not selected appear.
I have attached the efpt.config.json file for the initial reverse engineer, and after choosing the "use dataannotations ..." option.  the dbcontext matches the entities in the config file, but the entities in the config file do not match what was selected.

[efpt.config_initial.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5661749/efpt.config_initial.zip)

[efpt.config after.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5661769/efpt.config.after.zip)

**Comment by ErikEJ** [comment] 2020-12-08 20:54
Unable to repro...

**Comment by dchillman123** [comment] 2020-12-08 20:59
ok.  very reproducible on my side - as time permits I will try to create some db scripts for my db and send my solution.

**Comment by ErikEJ** [comment] 2020-12-08 21:01
That would be great!

**Comment by ErikEJ** [comment] 2020-12-09 19:53
Maybe a duplicate of #645 ?

**Comment by ErikEJ** [comment] 2020-12-10 06:57
Assuming this is a duplicate of #646 , then this is fixed in the latest daily build, would be grateful if you could verify

**Closed by ErikEJ** 2020-12-10 06:57 UTC

**Comment by dchillman123** [comment] 2020-12-10 15:28
Yes – the issue seems to have been resolved in the latest daily build.



Thanks



Dan



*From:* Erik Ejlskov Jensen <notifications@github.com>
*Sent:* Wednesday, December 9, 2020 11:58 PM
*To:* ErikEJ/EFCorePowerTools <EFCorePowerTools@noreply.github.com>
*Cc:* dchillman123 <dan.hillman@state.co.us>; Author <
author@noreply.github.com>
*Subject:* Re: [ErikEJ/EFCorePowerTools] Reverse Engineer and .net Core
5.0.1 (#642)



Assuming this is a duplicate of #646
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_646&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=Iw8sKSFlQAEJKnHZkw1fwJsQ9uDXywakhEOn3n13gYU&s=ySieTYaVXQYp2C41zyI1UEpdo4CFTzag9wXTfh4lcJI&e=>
, then this is fixed in the latest daily build, would be grateful if you
could verify

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_642-23issuecomment-2D742284511&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=Iw8sKSFlQAEJKnHZkw1fwJsQ9uDXywakhEOn3n13gYU&s=GGjw3Gt63rRgRIJBrWQd-9gofBsNxlm41wgl1NS0D9o&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJBVTL3QGZVGPSWNYLTSUBWPJANCNFSM4USLWJLQ&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=Iw8sKSFlQAEJKnHZkw1fwJsQ9uDXywakhEOn3n13gYU&s=-juZkgmB1Xf5ENrGYn9085toRIOdJbyvJMuQ_3J1vTo&e=>
.

**Comment by ErikEJ** [comment] 2020-12-10 15:35
Great news, thanks for confirming. 

@sm15455 FYI, I really appreciate your effort, these new features (better UI, column selection, table and colum rename) adds a lot of value to the tool over the built-in command line tooling.

**Comment by dchillman123** [comment] 2020-12-10 15:35
Incidentally, I like the stored procedure process.  I am not the best
programmer, so am not sure if I missed something in its use, but in a
console app I had to use a pattern like this to use it in a synchronous
fashion;



List<procNicheDORQueryResult> lstAccidentRecords = new
List<procNicheDORQueryResult>();

var procedures = new NichedorservicedbContextProcedures(_DORcontext);

Task<procNicheDORQueryResult[]> task =
procedures.procNicheDORQuery(TopNValue, cutoffDate);

   task.Wait();

    lstAccidentRecords = task.Result.ToList();



*From:* Erik Ejlskov Jensen <notifications@github.com>
*Sent:* Wednesday, December 9, 2020 11:58 PM
*To:* ErikEJ/EFCorePowerTools <EFCorePowerTools@noreply.github.com>
*Cc:* dchillman123 <dan.hillman@state.co.us>; Author <
author@noreply.github.com>
*Subject:* Re: [ErikEJ/EFCorePowerTools] Reverse Engineer and .net Core
5.0.1 (#642)



Assuming this is a duplicate of #646
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_646&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=Iw8sKSFlQAEJKnHZkw1fwJsQ9uDXywakhEOn3n13gYU&s=ySieTYaVXQYp2C41zyI1UEpdo4CFTzag9wXTfh4lcJI&e=>
, then this is fixed in the latest daily build, would be grateful if you
could verify

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_642-23issuecomment-2D742284511&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=Iw8sKSFlQAEJKnHZkw1fwJsQ9uDXywakhEOn3n13gYU&s=GGjw3Gt63rRgRIJBrWQd-9gofBsNxlm41wgl1NS0D9o&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJBVTL3QGZVGPSWNYLTSUBWPJANCNFSM4USLWJLQ&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=Iw8sKSFlQAEJKnHZkw1fwJsQ9uDXywakhEOn3n13gYU&s=-juZkgmB1Xf5ENrGYn9085toRIOdJbyvJMuQ_3J1vTo&e=>
.

**Comment by ErikEJ** [comment] 2020-12-10 15:42
You can make the  Main method async, so you don't need to do that!

**Comment by sm15455** [comment] 2020-12-10 15:51
> 
> 
> Great news, thanks for confirming.
> 
> @sm15455 FYI, I really appreciate your effort, these new features (better UI, column selection, table and colum rename) adds a lot of value to the tool over the built-in command line tooling.

@ErikEJ it was fun. I have some ideas for code customization regarding navigation properties name but have to reason about it.

**Comment by TamerElMorsi** [comment] 2020-12-24 04:46
**Solution**
upgrade your projetc to .net frame work to 5
upgrade all nugets to point to net core 5 version
then at reverse engineer only you need to check Use Ef Core5 
and uncheck use of data annotation option their
