### ISSUE TITLE
Option 'Compare DBContext to database' does not work with EF Core 6

### ISSUE THREAD

**Issue by Snappee** [ErikEJ/EFCorePowerTools#1411] opened 2022-05-31 23:41 UTC
Describe what is not working as expected.

### Provide steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by Snappee** [comment] 2022-05-31 23:42
Pretty simple, the option doesn't work. 

<img width="208" alt="2022-05-31_19-33-59" src="https://user-images.githubusercontent.com/9368303/171301155-b7c0c561-528a-4092-8035-764b4cdd6ba3.png">

**Comment by Snappee** [comment] 2022-05-31 23:46
Now, onto the good news . . . I'm a totally new user to both EF Core 6 and EF Power Tools!  One of my apprehensions related to switching over to EF Core 6 was the lack of some better ORM tools.   I used EFPT to reverse engineer an existing database and it saved me a TON of time creating the necessary entity classes and DBContext.  THANK YOU!

**Comment by ErikEJ** [comment] 2022-06-01 08:09
Thanks for the kind words - would be grateful for a rating on VS MarketPlace!

The issue is fixed in the latest daily build: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

**Closed by ErikEJ** 2022-06-01 08:09 UTC
