### ISSUE TITLE
Postgresql stored procedures generating 

### ISSUE THREAD

**Issue by deimspb** [ErikEJ/EFCorePowerTools#2395] opened 2024-06-13 14:59 UTC
Hi there!

I'll try to generate postgresql stored procedure in Reverse Engineering mode but without any success.

My store procedure:

```
CREATE OR REPLACE PROCEDURE public.sum_xy(IN _x integer, IN _y integer, INOUT _sum integer)
 LANGUAGE plpgsql
AS $procedure$
BEGIN
	_sum = _x + _y;
    RETURN;
END;
$procedure$
;
```
And i not see this procedure in this window:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/28717998/3870127e-86e5-4643-9a92-86546105ae9b)

Postgre version:
```
PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
```

efpt.config.json
```
{
   "CodeGenerationMode": 4,
   "ContextClassName": "NorthwindContext",
   "ContextNamespace": null,
   "FilterSchemas": false,
   "IncludeConnectionString": true,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "PostgresTester",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [
      {
         "Name": "public.Categories",
         "ObjectType": 0
      },
      {
         "Name": "public.CustomerCustomerDemo",
         "ObjectType": 0
      },
      {
         "Name": "public.CustomerDemographics",
         "ObjectType": 0
      },
      {
         "Name": "public.Customers",
         "ObjectType": 0
      },
      {
         "Name": "public.Employees",
         "ObjectType": 0
      },
      {
         "Name": "public.EmployeeTerritories",
         "ObjectType": 0
      },
      {
         "Name": "public.Order Details",
         "ObjectType": 0
      },
      {
         "Name": "public.Orders",
         "ObjectType": 0
      },
      {
         "Name": "public.Products",
         "ObjectType": 0
      },
      {
         "Name": "public.Region",
         "ObjectType": 0
      },
      {
         "Name": "public.Shippers",
         "ObjectType": 0
      },
      {
         "Name": "public.Suppliers",
         "ObjectType": 0
      },
      {
         "Name": "public.Territories",
         "ObjectType": 0
      },
      {
         "Name": "public.CustOrderHist",
         "ObjectType": 1
      },
      {
         "Name": "public.Employee Sales by Country",
         "ObjectType": 1
      },
      {
         "Name": "public.Sales by Year",
         "ObjectType": 1
      }
   ],
   "UiHint": null,
   "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": false,
   "UseDecimalDataAnnotationForSprocResult": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": true,
   "UsePrefixNavigationNaming": false,
   "UseSchemaFolders": false,
   "UseSchemaNamespaces": false,
   "UseSpatial": false,
   "UseT4": false
}
```

Can anyone explain me how  to add similar procedures in Reverse Engineering mode?

**Comment by ErikEJ** [comment] 2024-06-13 15:10
@deimspb Thanks for testing this feature, I think currently I only map row returning functions, not classic scalar stored procedures. 

Looks like a duplicate of #2338 

I hope to get round to it sometime soon.

**Closed** 2024-06-15 12:49 UTC
Labels: enhancement, reveng, reveng-cli

**Comment by ErikEJ** [comment] 2024-06-15 12:50
@deimspb 
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
