### ISSUE TITLE
Renamed column not effective for Context configuration

### ISSUE THREAD

**Issue by gaborkalmar78** [ErikEJ/EFCorePowerTools#1738] opened 2023-03-13 12:22 UTC
NewName for Column in efpt.property-renaming.json not effective for Context generation
(Model and context are in different project)

### Provide steps to reproduce

Tables:
```
CREATE TABLE session_slots (
 id int4 NOT NULL,
 user_id int4 NOT NULL,
 guid varchar NOT NULL,
 application_name varchar NOT NULL,
 CONSTRAINT pk_session_slots_id PRIMARY KEY (id),
 CONSTRAINT un_session_slots__guid UNIQUE (guid));

CREATE TABLE session_slot_data (
 id int4 NOT NULL,
 session_slot_guid varchar NOT NULL,
 "key" varchar NOT NULL,
 "data" bytea NOT NULL,
 CONSTRAINT pk_session_slot_data_id PRIMARY KEY (id),
 CONSTRAINT un_session_slot_data__session_slot_guid_key UNIQUE (session_slot_guid, key),
 CONSTRAINT fk_session_slot_data_session_slot_guid__ FOREIGN KEY (session_slot_guid) REFERENCES session_slots(guid) ON DELETE CASCADE);
```

efpt.property-renaming.json:
```
{
  "Classes": [
    {
      "Name": "SessionSlot",
      "Properties": [
        {
          "Name": "SessionSlotDatas",
          "NewName": "SessionSlotData"
        }
      ]
    },
    {
      "Name": "SessionSlotData",
      "Properties": [
        {
          "Name": "SessionSlotGu",
          "NewName": "SessionSlot"
        }
      ]
    }
  ]
}
```

Result in DbContext OnModelCreating:
```
 modelBuilder.Entity<SessionSlotData>(entity =>
            {
                entity.ToTable("session_slot_data", "xxx");

...

                entity.Property(e => e.SessionSlotGuid)
                    .IsRequired()
                    .HasColumnType("character varying")
                    .HasColumnName("session_slot_guid");

                entity.HasOne(d => d.SessionSlotGu)
                    .WithMany(p => p.SessionSlotDatas)
                    .HasPrincipalKey(p => p.Guid)
                    .HasForeignKey(d => d.SessionSlotGuid)
                    .HasConstraintName("fk_session_slot_data_session_slot_guid__");
            });
```

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: (2.5.1293)

- Database engine: (Postgres)

- Visual Studio version: (Visual Studio 2022)

**Comment by ErikEJ** [comment] 2023-03-13 14:23
I think this might be fixed for EF Core 7 in the latest extension version.

**Comment by ErikEJ** [comment] 2023-03-13 18:56
Have you tried just using normal renaming.json method?

**Comment by ErikEJ** [comment] 2023-03-15 14:07
Any news?

**Comment by ErikEJ** [comment] 2023-03-17 12:14
I am closing this, assume you are able to proceed? If not, feel free to re-open.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by gaborkalmar78** [comment] 2023-03-31 07:48
Hello, sorry for the late reply.

Yes, I tried the renaimng json method, but it tries to rename the model properties only.
Navigation properties are left alone this way.

**Comment by ErikEJ** [comment] 2023-03-31 07:50
@gaborkalmar78 Could you please show me the expected result (in addtion to the actula) and I will have a closer look.

**Closed** 2023-04-02 09:19 UTC
Labels: question

**Comment by Endre1980** [comment] 2023-04-21 10:23
We created a Test solution, so you can try the issue:
https://github.com/Endre1980/SessionSlotTest

Test.Core project:
The SessionSlotData has a SessionSlotGuid string property and a navigation property for SessionSlotData, which by default is generated with the name of SessionSlotGu.

The renaming in the efpt.property-renaming.json is affected by the generation and the navigation property will be renamed.

Test.DAL.EntityFramework:
In the TestContext the navigation property renaming is not affected and named as SessionSlogGu.

The efpt.property-renaming.json is not affected by the generation.


To bypass the issue we used the following method:
In the Test.Core project, in the efpt.property-renaming.json: The SessionSlotGu NewName is SessionSlotGuidNavigation.

In the Test.DAL.EntityFramework project:
- In the efpt.renaming.json the session_slot_guid (tablename) NewName is SessionSlotGuidLinkNavigation.
- efpt.postrun.cmd is created to rename SessionSlotGuidLinkNavigation and SessionSlotGuidLinkNavigationNavigation to a proper name.

**Comment by ErikEJ** [comment] 2023-04-21 12:38
@Endre1980 Thanks for the info, looks like a duplicate of #1769 - which is not something I currently plan to fix. Glad my tool features enabled you to work around this.
