### ISSUE TITLE
When constraint for default value is set to true, C# model is generated as nullable

### ISSUE THREAD

**Issue by flamecrow** [ErikEJ/EFCorePowerTools#790] opened 2021-02-17 16:51 UTC
When a **NOT NULL** bit column has a constraint for default value set to **TRUE (1)**, the C# model is generated as a nullable bool.

`ALTER TABLE SomeTableName
ADD CONSTRAINT DF_SomeTableName_SomeColumnName
DEFAULT 1 FOR SomeColumnName`

**Produces:**
public bool? SomeColumnName{ get; set; }

**Expected:**
public bool SomeColumnName{ get; set; }

If you set the default constraint to **FALSE (0)** it will produce the expected C# code.

### Steps to reproduce

1. Create a table
2. Add bit column with NOT NULL and default value of TRUE
3. Add bit column with NOT NULL and default value of FALSE
4. Use EF Power Tools to reverse engineer models
5. Observe the generated Null Conditional Operator in the column with default value of TRUE

### Further technical details
EF Core Power Tools version: 2.5.454.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019, version 16.8.4

**Comment by ErikEJ** [comment] 2021-02-17 17:00
Duplicate of #160 which was recently "fixed" with a new advanced option?

**Closed** 2021-02-17 17:18 UTC
