### ISSUE TITLE
Setter is not added to Entities created for EF Core 7 with .Net 6 for inverse properties that have list type.

### ISSUE THREAD

**Issue by inanfatih** [ErikEJ/EFCorePowerTools#1683] opened 2023-02-06 17:11 UTC
First of all, thank you very much for this great tool.

There are foreign keys in between tables which are one-to-many relationships. When I run the extension, an InverseProperty similar to the following one is created when I select EF Core 7. Please note that it does not have setter. However, it is added when I run the extension using EF Core 6 settings:
       ` public virtual ICollection<Table2> PayEntryBatchData { get; } = new List<Table2>();`

Missing the setter is causing the queries from Table1 to Table2 not to return any results. So, Table1.Table2 returns null.

Please let me know if you have any questions.

Here is the config file:
`{
   "CodeGenerationMode": 3,
   "ContextClassName": "AbcDbContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": "Context",
   "OutputPath": "Entities",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "ABC.Services.DS",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "[dbo].[Table1]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Table2]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Table3]",
         "ObjectType": 0
      }
   ],
   "UiHint": "namespaces",
   "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": true,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": true,
   "UseSchemaFolders": false,
   "UseSpatial": false,
   "UseT4": false
}`

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1277

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment] 2023-02-06 17:25
Duplicate of many issues here.

Can you share a sample query that fails?

@bricelam FYI

**Comment by ErikEJ** [comment] 2023-02-07 17:54
@inanfatih ping?

**Closed** 2023-02-08 07:42 UTC
Labels: question

**Comment by ErikEJ** [comment] 2023-04-13 06:02
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
