### ISSUE TITLE
Table list error - EF Core Power Tools version: 2.4.140

### ISSUE THREAD

**Issue by LeonardoRSilva** [ErikEJ/EFCorePowerTools#452] opened 2020-08-11 01:14 UTC
Describe what is not working as expected.

### Steps to reproduce
** 
The project has the .NET Core 2.1 version (the .NET Core 3.x version was also installed as requested at the link: https://github.com/ErikEJ/EFCorePowerTools/wiki)

I get the following error when running the reverse engineering option in the context menu (In the connection configuration step I was successful when clicking on the test conection option): 

System.Exception: Table list error: Unable to launch external process: 
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 159
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 57
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 33
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 30
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 345
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 92

![image](https://user-images.githubusercontent.com/13081442/89846069-944d8480-db56-11ea-8116-9784575a6bda.png)

### Further technical details
EF Core Power Tools version: 2.4.140

Database engine: SQL Server

Visual Studio version: Visual Studio 2017 15.9.15

**Comment by ErikEJ** [comment] 2020-08-11 06:01
What happens if you try to run:

    efreveng 3 "Data Source=.\SQLEXPRESS;Initial Catalog=Chinook;Integrated Security=True"

from the %temp%/efreveng folder ? (Replace with your own connection string, of course)

**Comment by Tabqwertus** [comment] 2020-08-11 08:45
I have the same problem. With a little bit more detail in the error message (from Visual Studio 2019  16.7.0): 

System.Exception: Table list error: **Unable to launch external process: Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.**
Result:
[
  _... Details of the database omitted ...._
]

   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildTableResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 159
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal(String arguments) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 57
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables(String connectionString, DatabaseType databaseType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 33
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions(Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\TableListBuilder.cs:line 30
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables(String connectionString, DatabaseType databaseType, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 345
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 92

**Comment by ErikEJ** [comment] 2020-08-11 09:28
@Tabqwertus It is not the same issue! Please try the latest daily build (2.4.148) - your issue should be fixed in that one.

**Comment by Danielhsc** [comment] 2020-08-11 12:15
@ErikEJ 
> What happens if you try to run:
> 
> ```
> efreveng 3 "Data Source=.\SQLEXPRESS;Initial Catalog=Chinook;Integrated Security=True"
> ```
> 
> from the %temp%/efreveng folder ? (Replace with your own connection string, of course)

I got the following error:
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files (x86)\dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.2.6 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
      2.2.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```
So I checked it had only just installed the .NET Core SDK for x64. After installing the x86 SDK, it worked!
Thanks!

**Comment by ErikEJ** [comment] 2020-08-11 12:24
@Danielhsc Fantastic - I will investigate how to improve the check for the presence of the x86 SDK/runtime, I just check that dotnet 3 is installed at th moment. Do you have any ideas - this is my current check:

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/EfRevEngLauncher.cs#L89

**Comment by ErikEJ** [comment] 2020-08-11 12:28
I have also updated https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering

**Comment by ErikEJ** [comment] 2020-08-11 12:41
I will change the runtime to x64 in the latest daily build

**Comment by ErikEJ** [comment] 2020-08-11 12:51
Latest daily build updated to use the x64 runtime/SDK

**Comment by dcanamares** [comment] 2020-08-11 13:11
After instaling 2.4.151.0 it's works again. I didn't need to install x86 versions.
Thanks.

**Comment by LeonardoRSilva** [comment] 2020-08-11 13:50
I executed the command requested and returned an error requesting version 3.1.0, I was with version 3.0 of .NetCore, I installed version 3.1.0 and it worked, thanks for your attention.

**Comment by ErikEJ** [comment] 2020-08-11 13:53
Thanks for the update!

**Closed** 2020-08-11 13:52 UTC

**Comment by zzurka** [comment] 2020-08-11 14:00
Are previous versions available to download? I need them because of .net core 2.2, since it is not working with the latest version. Thanks

**Comment by dcanamares** [comment] 2020-08-11 14:03
> 
> 
> Are previous versions available to download? I need them because of .net core 2.2, since it is not working with the latest version. Thanks

Install 2.4.151 and check if you have Net Core 3.1 SDK installed. It's works for me.

**Comment by ErikEJ** [comment] 2020-08-11 14:04
@zzurka Pls try the latest daily build - what exactly is not working?

**Comment by zzurka** [comment] 2020-08-11 14:11
I tried the latest version, and also the latest daily version. The problem is that the project I'm working on uses .net core 2.2. When I generate the model I have comments added to DbContext (e.g. entity.Property(e => e.PropertyName).HasComment("...comment...");). But .net core 2.2 doesn't support this method .HasComment().

**Comment by ErikEJ** [comment] 2020-08-11 14:17
@zzurka you are aware that .NET Core 2.2 is no longer supported? 

Look at the release notes page in the wiki, it has a link to an older version.

**Comment by zzurka** [comment] 2020-08-11 14:23
I'm aware. Thanks, I found the link.

**Comment by ErikEJ** [comment] 2020-08-11 14:25
@zzurka Feel free to raise an issue if you feel there is a need to bring back 2.2 reverse engineering support in the future

**Comment by zzurka** [comment] 2020-08-17 07:40
Well, if it's only me who needs it then I'll just use the old version. But there's a problem with the version I downloaded. The version in the wiki is 2.4.81 and it doesn't work. I found in my downloads folder version 2.4.51 and it works.

**Comment by ErikEJ** [comment] 2020-08-17 07:43
The version in the wiki should be 2.4.51 !?

**Comment by zzurka** [comment] 2020-08-17 08:28
I'm pretty sure it didn't work with the version I downloaded from wiki. Only when I installed the version I found in my downloads folder, it worked. I'm gonna have to check what version was that.

**Comment by ErikEJ** [comment] 2020-08-17 08:31
I just checked the wiki link, it is 2.4.51!

**Comment by zzurka** [comment] 2020-08-17 08:41
You're right, it is 2.4.51, I'm sorry. I just installed the version from the wiki and it works now. The last time I tried it didn't work, maybe I did something wrong. Sorry again.

**Comment by ErikEJ** [comment] 2020-08-17 08:54
No worries, happy you are unblocked!
