### ISSUE TITLE
ICollection (navigation collection property) is now unexpectedly read-only when EF Core 7 is selected in generator

### ISSUE THREAD

**Issue by janseris** [ErikEJ/EFCorePowerTools#1747] opened 2023-03-21 22:23 UTC
Describe what is not working as expected.

When EF Core 6 is selected in EF Core Power Tools, collections can be assigned to.
I have used that while mapping entities for insert.
When I select EF Core 7, collections are now readonly.
I have to change all mappers code to not assign to the collection `= (from x select map(x)).ToList()` but I will have to do something like `.AddRange()` everywhere.

```
public class FotoableInsertDTOMapper
{
    private readonly FotoInsertDTOMapper fotoMapper;
    public FOTOABLE Map(IFotoableInsertDTO data)
    {
        return new FOTOABLE
        {
            FOTO = (from p in data.Fotky
                      select fotoMapper.Map(p)).ToList()
        };
    }
}

```

Generated code using EF Core Power Tools with `EF Core 6` selected:

```
public partial class FOTOABLE
{
    public FOTOABLE()
    {
        FOTO = new HashSet<FOTO>();
    }

    public int ID { get; set; }

    public virtual ICollection<FOTO> FOTO { get; set; }
}
```

Generated code using EF Core Power Tools with `EF Core 7` selected:

```
public partial class FOTOABLE
{
    public int ID { get; set; }

    public virtual ICollection<FOTO> FOTO { get; } = new List<FOTO>();
}
```

### Provide technical details

- EF Core version in use: EF Core 7
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1338

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment] 2023-03-22 07:25
Duplicate of multiple issues here, you can use Add(Range), use the latest T4 templates from EF Core Power Tools or await a fix in a future version of 7.0 tooling, see #1687 (and multiple others)

**Closed** 2023-03-22 07:25 UTC
