### ISSUE TITLE
Data API scaffold builder fails 

### ISSUE THREAD

**Issue by jovball** [ErikEJ/EFCorePowerTools#2468] opened 2024-08-19 22:11 UTC
### How to cause the error

- Create a project using the ASP.NET Core Web API template. 
- Select the options for .NET 8.0 LTS, no authentication, HTTPS, Enable OpenAPI support and Use Controllers. 
- Create a connection to Northwind and confirm that I am able to generate the models and DBContext with that connection. 
- Using the context menu to select Data API Builder Scaffold results in this error in the Extensions output.

```
System.InvalidOperationException: Result error: 
Could not open options file: dabbuilder

   at string EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildDiagramResult(string output)
   at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetDiagramInternalAsync(string arguments)
   at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetDabConfigPathAsync(string optionsPath, string connectionString)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.DabBuilderHandler.GenerateFilesAsync(string optionsPath, string connectionString)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.DabBuilderHandler.BuildDabConfigAsync(Project project)
```

### Technical details
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.6.420

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
VS 2022 Enterprise 17.10.5

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server 

- EF Core version in use: (e.g. EF Core 7)
EF Core 8

- Is Handlebars templates used: no/yes
No
- Is T4 templates used: no/yes
No

- Is a SQL Server .dacpac used: no/yes
No

**Comment by ErikEJ** [comment] 2024-08-20 05:12
Duplicate of #2469

**Closed** 2024-08-20 05:13 UTC

**Comment by ErikEJ** [comment] 2024-08-27 05:34
I am unable to repro, but have added som additionl tracing to a efrevengparams.txt file in your temp folder to the latest daily build, could you give that a try?

**Comment by ErikEJ** [comment] 2024-08-27 12:32
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by jovball** [comment] 2024-08-30 01:08
I was away for a few days and still catching up. I was able to generate the dab-build.cmd file with the new build, 2.6.437. It will be a few days before I can also test the functionality.  Thanks for fixing this.

**Comment by ErikEJ** [comment] 2024-08-30 05:07
Thanks for the heads up and really looking forward to your feedback.
