### ISSUE TITLE
Setter removed from Entity for Child Entities in EF 7

### ISSUE THREAD

**Issue by ckashyap91** [ErikEJ/EFCorePowerTools#1587] opened 2022-11-16 10:40 UTC
Using EF Core power tools for EF core 7, Child entities converted into getter only.

EF 6
public virtual ICollection<x> X { get; set; }
vs 
EF 7
public virtual ICollection<x> X { get; } = new List<x>();

There are few places in our code that need to set this property explicitly.  
 Is there any workround for this?

**Comment by ErikEJ** [comment] 2022-11-16 11:10
Duplicate of #1582 - and you can use T4 to customize - but why do you need this? Can you share some example code?

**Comment by ckashyap91** [comment] 2022-11-16 12:17
We are creating explicit object of parent entity and for that we need to set collection.
var  object = new EntityA(){
	Prop1 = 123,
	Prop2 = new List<ChildEntityB>()
}

something like this.

**Comment by ckashyap91** [comment] 2022-11-16 12:33
Sorry 
but here we are initializing with new list which is not blank.

**Comment by ErikEJ** [comment] 2022-11-16 12:43
You could do:

   entity.Prop2.Add(new X())

Otherwise you must customize with T4

**Comment by ckashyap91** [comment] 2022-11-16 13:10
Yes that we can do. But there are many places in our project where we can apply this. 
Why we have change like this?

**Comment by ErikEJ** [comment] 2022-11-16 13:18
Just customize the T4 template

**Comment by ckashyap91** [comment] 2022-11-16 13:20
Thanks for update.
How to overwrite T4 template?

**Comment by ErikEJ** [comment] 2022-11-16 13:24
read the wiki:
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#customize-code-using-t4-templates
and I have a video here: https://www.youtube.com/watch?v=PUexkGWErNk

**Comment by ErikEJ** [comment] 2022-11-16 13:25
@bricelam FYI

**Closed by ErikEJ** 2022-11-16 13:24 UTC

**Comment by ckashyap91** [comment] 2022-11-16 13:44
Thanks for sharing

**Comment by ErikEJ** [comment] 2022-11-16 13:45
You are very welcome.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Comment by ErikEJ** [comment] 2022-11-16 13:46
>>  May I know reason for removing setter?

I do not know - that is why I am asking @bricelam from the EF Core team above.

**Comment by bricelam** [comment] 2022-12-09 21:48
Note, get-only properties can still be used with object initializers: (just remove `new List()`)

```cs
var obj = new EntityA() {
    Prop1 = 123,
    Prop2 = { new X(), new X() }
}
```

**Comment by ErikEJ** [comment] 2022-12-10 06:26
@bricelam Thanks a lot @bricelam !

**Comment by powermetal63** [comment] 2023-01-23 15:37
> > May I know reason for removing setter?
> 
> This code was a violation of rule [CA2227](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2227). (and the [design guidelines for collection properties](https://learn.microsoft.com/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values))

In other words, you care about some artificial warnings and guidelines (not mandatory at all) rather than the customers of your code? 
Also, speaking about rules and guidelines, aren't EF Core "entities" supposed to represent the data model, i.e. no OOP, no business logic etc., simple objects (POCO, DTO) with public property getters and setters representing columns and relationships?

Have anyone asked for this change? As well as changing navigation/string property "required" based on project NRT settings? I am totally disappointed with the whole Net Core ("modern") line of doing unnecessary breaking changes, because "you know, this is the right way, the previous was wrong and we need to force you to do it our way, no matter how additional work/cost it is for you". Won't be surprised if all these warnings and "guidelines" become non configurable mandatory compiler errors at some point.

P.S. The syntax you are suggesting does not work when someone needs to initialize collections with `Enumerable.Range(...).Select(...).ToList()` where selector might contain nested collection member initializers. This is commonly used for "seeding" test data.

I think you should return the setter by default, or at least make it `get; init;`}. ASAP.

**Comment by ErikEJ** [comment] 2023-01-23 15:43
@powermetal63 maybe you should post this in the EF Core repo?

**Comment by giarico** [comment] 2023-02-14 15:41
With get only collections, the blazor funzion GetFromJsonAsync does not serialize the related child collection. Is this correct??

**Comment by ErikEJ** [comment] 2023-02-14 17:53
@giarico suggest you as with some sample code in the EF Core repository

**Comment by giarico** [comment] 2023-02-14 18:22
@ErikEJ I've submitted the issue on EFCore github. I hope it is clear.

**Comment by ErikEJ** [comment] 2023-02-16 07:22
@giarico A fix for this [is considered](https://github.com/dotnet/efcore/issues/30286#issuecomment-1431244084) by the EF Core team, and I have included the fix in the latest daily (if you use T4 templates)

**Comment by giarico** [comment] 2023-02-16 07:28
Thank you so much for the quick update

**Comment by ErikEJ** [comment] 2023-02-16 07:46
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment] 2023-04-13 06:01
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
