### ISSUE TITLE
Firebird 3.0 not showing procedures

### ISSUE THREAD

**Issue by kevinvenclovas** [ErikEJ/EFCorePowerTools#1086] opened 2021-09-01 14:47 UTC
Describe what is not working as expected.

### Steps to reproduce
**- Add a Firebird 3.0 Connection with the ad hoc Connection
- Open Database Objects list
- No Procedure exists only Tables and Views**

![image](https://user-images.githubusercontent.com/7681603/131692385-5f6164a9-52a0-4ce8-8dcb-7caebc24b5db.png)

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
**EF Core Power Tools version - Version 2.5.692.0**
Project: .net core 5

Database engine: **Firebird 3.0**

Visual Studio version: (e.g. Visual Studio 2019 16.9)

**Microsoft Visual Studio Professional 2019
Version 16.9.1**

**Comment by ErikEJ** [comment] 2021-09-01 14:57
Duplicate of #697 - PRs accepted!

**Closed by ErikEJ** 2021-09-01 14:57 UTC
