### ISSUE TITLE
An error occurred：SetSite failed for package [EFCorePowerToolsPackage]Source: 'EFCorePowerTools' Description: 未能加载文件或程序集“EnvDTE,

### ISSUE THREAD

**Issue by kakalotte** [ErikEJ/EFCorePowerTools#1046] opened 2021-07-17 03:56 UTC
SetSite failed for package [EFCorePowerToolsPackage]Source: 'EFCorePowerTools' Description: 未能加载文件或程序集“EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
System.IO.FileNotFoundException: 未能加载文件或程序集“EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
文件名:“EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
   在 EFCorePowerTools.EFCorePowerToolsPackage.<InitializeAsync>d__11.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   在 EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
   在 Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   在 Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

EF Core Power Tools version:2.5.692

Visual Studio version: Microsoft Visual Studio Enterprise 2022 Preview (64 位)

**Comment by ErikEJ** [comment] 2021-07-17 05:55
What happens before you got this error??

**Comment by ErikEJ** [comment] 2021-07-17 06:16
Could you try the latest daily?

**Comment by kakalotte** [comment] 2021-07-17 14:44
[ActivityLog.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6834867/ActivityLog.zip)

**Comment by ErikEJ** [comment] 2021-07-17 15:12
No idea, could be a VS2022 issue/bug. 
Are you running VS 2022 preview 2?

What OS language and VS language?

**Comment by ErikEJ** [comment] 2021-07-17 15:12
I am not able to repro! @madskristensen ??

**Comment by kakalotte** [comment] 2021-07-17 15:17
All  Chinese

**Comment by madskristensen** [comment] 2021-07-17 16:47
Known bug in Preview 1 that was fixed in Preview 2 of VS2022

**Comment by ErikEJ** [comment] 2021-07-17 16:50
But @kakalotte claims to be running preview 2!

**Comment by kakalotte** [comment] 2021-07-18 05:18
> Known bug in Preview 1 that was fixed in Preview 2 of VS2022

Using a brand new computer, there is no problem after reinstall the win10 system and vs2022 preview  2 software.

**Comment by ErikEJ** [comment] 2021-07-18 07:41
Closing as external VS issue

**Comment by TimKras** [comment] 2021-08-12 09:50
> Known bug in Preview 1 that was fixed in Preview 2 of VS2022

Still not fixed in my version (using Preview 3 of VS2022).
Already completly uninstalled VS2022, but problem still exists.

**Comment by TimKras** [comment] 2021-08-12 09:50
See also: https://developercommunity2.visualstudio.com/t/Could-not-load-file-or-assembly-EnvDTE/1463536

**Comment by madskristensen** [comment] 2021-08-12 16:15
Did you get rid of all uses of DTE and replaced them with DTE2?

**Comment by ErikEJ** [comment] 2021-08-12 16:46
@madskristensen I intended to, but maybe I did it wrong?

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/Shared/Handlers/ProcessLauncher.cs#L73

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs#L70

**Comment by ErikEJ** [comment] 2021-08-12 16:49
@TimKras Can you share your activitylog? Or full error stack?

**Comment by madskristensen** [comment] 2021-08-12 16:50
Ok, i think i figured it out from having the same issue in one of my extensions. I was referencing the old Private Interop Assemblies for the EnvDTE. When I changed to using PackageReferences and the Microsoft.VisualStudio.SDK (or toolkit) package it worked. Or so it seems

**Comment by ErikEJ** [comment] 2021-08-12 16:52
But I am using PackageReferences already...

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/EFCorePowerTools.csproj

**Comment by ankitvarmait** [comment] 2021-08-12 17:49
By upgrading the package  
`<PackageReference Include="Microsoft.VisualStudio.SDK" Version="16.0.206" />`  to the latest should remove the dependency from `EnvDTE, Version=8.0.0.0`

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/EFCorePowerTools.csproj

**Comment by ErikEJ** [comment] 2021-08-12 18:17
@ankitvarmait Well spotted, thanks!

**Comment by ErikEJ** [comment] 2021-08-12 18:20
@TimKras @kakalotte I attempted a fix in the latest daily build, are you able to give that a try?

**Comment by ErikEJ** [comment] 2021-08-12 18:25
@ankitvarmait What if my extension also target VS 2017 (Using SDK 15.0.1) ?

**Comment by ErikEJ** [comment] 2021-08-13 05:26
@TimKras thanks!

I am going to wait and see, as I am not able to repro on my machine and according to @madskristensen publishing a mixed extension should be possible.

What other extensions do you have installed in VS 2022?

What other VS versions do you have installed?

**Comment by PeaStew** [comment] 2021-08-14 12:23
Oops I just posted the same issue, I really do think this is a config change though in my case because I actually used EFCPT successfully in a solution previously in VS2022, and there was no issue and then it appeared after I changed some things. It may be one of the preview features.

**Comment by PeaStew** [comment] 2021-08-17 17:58
Daily build is not solving it for me in VS22 (Preview 3.1), have quite a few extensions installed:

- **JetBrains Resharper 2021.2 EXP 01**
- **SQL Server Data Tools - Sql Editor**
- Visual Studio Intellicode
- Live Share
- Web Live Preview (Preview)
- Javascript project system
- Visual STudio Rich Navigation [Preview]
- ML.NET Model Builder (Preview)
- NuGetRecommender [Preview]

Happy to test anything out as you need it.

**Comment by aikidoshi** [comment] 2021-08-18 07:27
I'm having the same problem with a Web API with the same error shown above. Thinking it could be an issue with the project I started a new API project and now instead of getting the popup error, nothing happens at all.

**Comment by ErikEJ** [comment] 2021-08-18 07:51
@aikidoshi this extension is global to VS and does not relate to any projects.

**Comment by aikidoshi** [comment] 2021-08-18 08:07
Hi Erik, I meant 'solution'. No matter, when I removed the extension and added it back it fails with the popup as with the previous solution.

**Comment by ErikEJ** [comment] 2021-08-28 12:25
I have made another attempt to fix this in the latest daily build, would be grateful if you could try it out.

**Comment by aikidoshi** [comment] 2021-08-28 13:16
This www.vsixgallery.com page can’t be found

No webpage was found for the web address: https://www.vsixgallery.com/extensions/f4c4712c-ceae-4803-8e52-0e2049d5de9f/EF%20Core%20Power%20Tools%20v2.5.732.vsix

HTTP ERROR 404

Sorry, could not download latest daily build.
________________________________

**Comment by ErikEJ** [comment] 2021-08-28 13:24
@aikidoshi Fixed now!

**Comment by TimKras** [comment] 2021-08-28 14:40
Error at startup semes to be gone, but when trying to Reverse Engineer this error appears immediately.
![image](https://user-images.githubusercontent.com/5257192/131221664-7d616cbf-a5bf-421c-843b-268bfed87df8.png)

**Comment by ErikEJ** [comment] 2021-08-28 14:50
@TimKras After selecting the menu item?

**Comment by TimKras** [comment] 2021-08-28 14:56
> @TimKras After selecting the menu item?

Yes indeed.

**Comment by ErikEJ** [comment] 2021-08-28 16:12
@TimKras Thanks, I think I now understand what needs to change!

**Comment by ErikEJ** [comment] 2021-08-29 18:11
@TimKras and anyone else watching this: Made some major changes in latest daily build, that I hope will improve this, but as mentioned above, I have never been able to repro locally.

**Comment by TimKras** [comment] 2021-08-29 21:04
> @TimKras and anyone else watching this: Made some major changes in latest daily build, that I hope will improve this, but as mentioned above, I have never been able to repro locally.

Sorry, latest daily build is giving the same error when when clicking the menu item:
![image](https://user-images.githubusercontent.com/5257192/131265295-a62be2a9-c354-49e0-b5fe-fbaf0d401c64.png)

**Comment by aikidoshi** [comment] 2021-08-29 22:24
![Screenshot 2021-08-30 081849](https://user-images.githubusercontent.com/16281791/131267192-d68682eb-d401-4d38-ae28-c4fb90d649ae.png)
Can confirm that latest build still fails when Reverse Engineer is selected, and that it works perfectly on VS2019 Preview.
Note also that I am running the Dev Channel Windows 11 build, which may be why you can't reproduce it if you're on Windows 10 for example.

**Comment by ErikEJ** [comment] 2021-08-30 15:30
@TimKras  @aikidoshi An new build up, where I have removed even more traces of EnvDTE - would be grateful for your feedback.

**Comment by TimKras** [comment] 2021-08-30 16:13
> @TimKras @aikidoshi An new build up, where I have removed even more traces of EnvDTE - would be grateful for your feedback.

I have some days off. I can test again after next weekend.

**Comment by aikidoshi** [comment] 2021-08-30 20:49
I removed the previous build and installed the new build but it now does absolutely nothing. I can see it is installed but it is not in the menu so I can't test it.

Regards,

Steve
________________________________

**Comment by GlenHandke** [comment] 2021-08-30 21:36
Just another data point.  I had no problems at all until I opened my VS2019 options (by picking 'change' in the control panel app).  I didn't make any changes... was just showing a friend some selections I had enabled.  Closed the VS2019 installer and the problem appeared the next time I started VS2019 (16.11.2).  Ran the MEF cache cleaner, rebooted, all to no avail.  Had to remove the extension to get rid of the error.

**Comment by ErikEJ** [comment] 2021-08-31 04:34
@GlenHandke how does that relate to VS 2022 and the error message in this issue?

**Comment by aikidoshi** [comment] 2021-08-31 05:08
I find that it doesn't crash or anything at runtime, but there is no menu for EF Core Power Tools.

Regards,
Steve
________________________________

**Comment by ErikEJ** [comment] 2021-08-31 05:30
@aikidoshi Thanks for the support. Steve! It was a bug in the EnvDTE replacement library, just committed a work around (build 740 or later)

**Comment by aikidoshi** [comment] 2021-08-31 06:12
Hi Erik,

Glad to help mate, I love this tool (actually only ever used Reverse). I work with a lot of legacy DBs, never get to do code first.

Is EnvDTE something I should install separately, because now EF Core PT installed and has a menu, but when I select Reverse Engineer I get this in the Extensions Output console, even though I tried installing EnvDTE latest but it still complained about 8.0.0, so I Install-Package envdte -Version 8.0.0, but that did not help.

System.IO.FileNotFoundException: Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


regards,

Steve
________________________________

**Comment by ErikEJ** [comment] 2021-08-31 08:32
Do not install the EnvDTE package, it is not related to this.

Thanks for the stack trace, it enables me to go further.

**Comment by ErikEJ** [comment] 2021-08-31 08:48
@aikidoshi I have attempted another fix just now

**Comment by aikidoshi** [comment] 2021-08-31 10:30
Genius! 471 is working fine.

Well done, regards, Steve
________________________________

**Comment by ErikEJ** [comment] 2021-08-31 10:33
Amazing news.

Notice that automatic NuGet package install is broken.

**Comment by ErikEJ** [comment] 2021-08-31 13:33
@madskristensen Just FYI, looks like this was mainly caused by using the NuGet.VisualStudio v 5 package.

**Comment by Tim-Maes** [comment] 2022-08-18 11:54
Facing the same issue on my T4Executer extension. Headaches!

**Comment by ErikEJ** [comment] 2022-08-18 12:15
@Tim-Maes Feel free to reach out for any advice - I might have some tips

**Comment by Tim-Maes** [comment] 2022-08-24 07:35
I don't know where I can reach out to you exactly @ErikEJ, but my WIP is here https://github.com/Tim-Maes/T4Executer/pull/4

I'm not sure if I'm able to publish a VS2022 and a VS2019 VSIX file from one single solution

**Comment by ErikEJ** [comment] 2022-08-24 07:49
@Tim-Maes I publish a VS 2022 and VS 2019 VSIX from the same solution, so it can be done.

Look at my VSIX manifest file: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/source.extension.vsixmanifest#L22

The main point is to stop using EnvDTE and replace with methods from VS Community Toolkit version 16.

See for example: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/Shared/Extensions/ProjectExtensions.cs

**Comment by Tim-Maes** [comment] 2022-08-24 08:32
I removed all EnvDTE references, and install the Toolkit in both vsix projects, but the code that uses EnvDTE has been moved to a shared library (as by the official documentation example) which for some reason can't reference the toolkit and still needs EnvDTE to find 'Project' objects.  

There must be something I don't understand or completely miss at this moment

**Comment by ErikEJ** [comment] 2022-08-24 08:35
You do not actually need the shared project. But a shared project works fine for me with the Toolkit.

If you have a branch with the current code I am happy to take a look.

**Comment by Tim-Maes** [comment] 2022-08-24 08:48
WIP on this is right [here](https://github.com/Tim-Maes/T4Executer/tree/feature/update-to-2022). Thanks in advance.

**Comment by ErikEJ** [comment] 2022-08-24 08:57
Confused - I see two VSIX projects ?? And no references to the Toolkit ??

What should be the goal ? Get T4Executer project working in VS 2022 - or publish a dual target VSIX?

**Comment by ErikEJ** [comment] 2022-08-24 09:00
If goal is just "Get T4Executer project working in VS 2022" things become much simpler.

**Comment by Tim-Maes** [comment] 2022-08-24 12:09
According to the official docs I had to create a VSIX project that targets VS2022 and move all code to a shared library. When I build in release mode TTExecuter now generates an VSIX for VS2019 and T4Executer for VS2022. 
The goal is to have an working VSIX for VS2022 indeed.

**Comment by ErikEJ** [comment] 2022-08-24 13:42
You need to switch to the Community Toolkit events, they no longer work with DTE: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/63

**Comment by Tim-Maes** [comment] 2022-08-26 07:04
When installing the Toolkit NuGet I can never seem to use it anywhere in my project. 
![image](https://user-images.githubusercontent.com/91606949/186842575-5c3e4840-55bc-4e10-a463-efd0d79fbf9f.png)

I'm going to take a deep dive into it this weekend. Thanks for the replies (y)

**Comment by ErikEJ** [comment] 2023-07-12 14:59
@JosephWJMaxwell which exact VS version?

**Comment by tpumper** [comment] 2023-07-12 15:42
> @JosephWJMaxwell which exact VS version?

@ErikEJ I am getting the same issue in VS 2022

**Comment by ErikEJ** [comment] 2023-07-12 15:44
@tpumper sure, bit which version exactly ?? 17.x.x - check Help, About menu

**Comment by iivsimeonov** [comment] 2023-07-12 15:46
The same error and log file on my site. Version 2022 - 17.4.0

**Comment by tpumper** [comment] 2023-07-12 15:47
> @tpumper sure, but which version exactly ?? 17.x.x - check Help, About menu

@ErikEJ 17.4.1

**Comment by ErikEJ** [comment] 2023-07-12 16:01
Please Update to the latest version 17.5.6 and let me know the outcome

**Comment by tpumper** [comment] 2023-07-12 16:35
@ErikEJ That worked. Thank you for the guidance.

**Comment by ErikEJ** [comment] 2023-07-12 16:41
You are welcome, not sure what is going on here - @madskristensen any idea?

**Comment by madskristensen** [comment] 2023-07-12 16:51
@ErikEJ Looks like it can't find a method on the JTF or perhaps the JTF itself. That's odd. @aarnott any idea?

**Comment by ErikEJ** [comment] 2023-07-12 16:59
@madskristensen yes, and it seems to be an issue with 17.4 (and maybe earlier)  , not 17.5

**Comment by madskristensen** [comment] 2023-07-12 17:07
Are you using 17.0.x versions of the SDK NuGet packages and not 17.5.x or newer?

**Comment by ErikEJ** [comment] 2023-07-12 18:45
@madskristensen I am using the implicit reference via Community Toolkit. It is advisable to use 17.5 SDK explicitly?

**Comment by AArnott** [comment] 2023-07-12 20:10
Referencing EnvDTE 8.0.0.0 on VS 2022 is not supported. With the change to 64-bit, we made interop-incompatible changes to fix bitness issues in these assemblies and require everyone to recompile. While some extension authors find that they may get away without doing this, this may very well be one of those cases where it really is necessary. And we don't have capacity to offer help for a scenario that is officially unsupported.

**Comment by ErikEJ** [comment] 2023-07-13 05:05
@AArnott Thanks, I am not doing that, please read the last entries in this thread. I will add an explicit SDK ref

**Closed** 2023-07-13 05:52 UTC

**Comment by AArnott** [comment] 2023-07-14 04:59
Ah, it was a very long thread so I just read the description, you're right. But I see you've closed the issue too, so should I still read through everything?

**Comment by ErikEJ** [comment] 2023-07-14 08:01
@AArnott I am so sorry, someone hijacked this old unrelated thread, and I got confused.

[This thread](https://github.com/ErikEJ/EFCorePowerTools/issues/1874) is the current issue (and luckily much shorther). Looking at the VSIX now I can see that the SDK libraries are included as files - is that expected?

**Comment by AArnott** [comment] 2023-07-14 14:47
Awesome. That makes more sense. I'll hop over to that thread and reply.
