### ISSUE TITLE
Handlebars not working when reverse engineering using EF Core 6

### ISSUE THREAD

**Issue by whitwa** [ErikEJ/EFCorePowerTools#1126] opened 2021-09-28 15:30 UTC
Any customisations added to C# handlebars are not applied when using EF Core 6 but are when reverting back to EF Core 5.

Tested with latest version downloaded via VS (2.5.774) and daily build (2.5.783)

Database engine: SQL Express

Visual Studio version: 2019 and 2022

**Comment by ErikEJ** [comment] 2021-09-28 15:36
No Handlebars for EF Core 6 yet, duplicate of #1106

**Closed** 2021-09-28 15:36 UTC

**Comment by whitwa** [comment] 2021-09-30 12:57
Thanks Erik.

Any ideas when this support will be added? I'd like to use in a new project if possible.

**Comment by ErikEJ** [comment] 2021-09-30 13:03
You will have to ask the Handlebars library maintainer @tonysneed, but some time shortly after the release of EF Core 6 I would imagine

**Comment by tonysneed** [comment] 2021-09-30 13:34
I will update the Handlebars lib to EF Core 6 sometime before EF Core is released. You can track progress on this issue [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/181) .
