### ISSUE TITLE
Does it support MySql Stored Procedure as well?

### ISSUE THREAD

**Issue by DennisRodriguez** [ErikEJ/EFCorePowerTools#912] opened 2021-04-09 16:31 UTC
All I can see in the Choose Database Objects Window are Tables and Views with both 5.7 and 8.0.23. Am I missing something or MySql stored procedure is really not supported? If yes, any chance of supporting it in the future?

### Steps to reproduce
Standard procedure for Reverse Engineering

### Further technical details
EF Core Power Tools version: 2.5.612.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (MySql 5.7.33 and 8.0.23)

Visual Studio version: (Visual Studio 2019 16.9.3)

Thanks,
Dennis

**Comment by ErikEJ** [comment] 2021-04-09 17:15
No, it is not currently supported.

If someone steps up and implements it, it will be! @jespersh ?

**Comment by ErikEJ** [comment] 2021-04-10 14:11
Duplicate of #697

**Closed by ErikEJ** 2021-04-10 14:11 UTC

**Comment by jespersh** [comment] 2021-04-10 14:19
> No, it is not currently supported.
> 
> If someone steps up and implements it, it will be! @jespersh ?

I don't use stored procedures, so I wouldn't even know where to start and what result I should end up with
