### ISSUE TITLE
Navigation properties names

### ISSUE THREAD

**Issue by viktorszekeress** [ErikEJ/EFCorePowerTools#732] opened 2021-01-26 09:12 UTC
In our db, we don't use "Id" or "TableNameId" names for PK columns, but rather "TableNameGUID" names. After running the tool, I'm getting strange navigation property names:

Let's say we have:

* OrderLift table with
   * OrderLiftGUID
   * DriverGUID

* Driver table with
   * DriverGUID

This leads to generated OrderLift model having "DriverGu" navigation property, instead of "Driver". I tried to customize it with config.json, but that didn't work, since this is not a column in the db. I'm pretty sure this wasn't happening with EF6 or Linq2Sql.

Is there any way to customize navigation properties names?

**Comment by ErikEJ** [comment] 2021-01-26 09:51
Possible duplicate of #211 - also, EF Core is a new product, so expect little parity with EF6/LINQ to SQL

**Comment by ErikEJ** [comment] 2021-01-26 11:01
What would be your approach to this feature? A simple list of navigations with old name / new name? Added efpt.renaming.json.

**Comment by viktorszekeress** [comment] 2021-01-26 12:47
Yes, something similar to renaming the columns:
```
    "Tables": [
      {
        "Name": "OrderLift",
        "Navigations": [
          {
            "Name": "DriverGu",
            "NewName": "Driver"
          }
        ]
      }
    ]
```

**Comment by ErikEJ** [comment] 2021-01-26 15:06
Can you share a sample CREATE TABLE script?

**Comment by viktorszekeress** [comment] 2021-01-26 15:34
I cut some parts and modified some names, so hope it will be valid.

```
CREATE TABLE [Lift](
	[LiftGUID] [uniqueidentifier] NOT NULL,
	[DriverGUID] [uniqueidentifier] NULL,	
 CONSTRAINT [PK_Lift] PRIMARY KEY 
(
	[LiftGUID] ASC
)
)

CREATE TABLE [Driver](
	[DriverGUID] [uniqueidentifier] NOT NULL,	
 CONSTRAINT [PK_Driver] PRIMARY KEY 
(
	[DriverGUID] ASC
)
)

ALTER TABLE [Lift]  WITH NOCHECK ADD CONSTRAINT [FK_Lift_Driver] FOREIGN KEY([DriverGUID])
REFERENCES [Driver] ([DriverGUID])

```

**Closed** 2021-01-26 18:07 UTC

**Comment by ErikEJ** [comment] 2021-01-26 18:08
Implemented (experimental) in latest daily build, suggest you have a look at the PR to better understand usage.

**Comment by viktorszekeress** [comment] 2021-01-26 18:17
That looks very promising. 
I really appreciate your effort being super responsive and taking care of your product!

**Comment by ErikEJ** [comment] 2021-01-26 18:20
Interestingly, the original issue #211 was almost 2 years old, but your request made me rethink and realize that maybe it was less complex than expected! 😄
