### ISSUE TITLE
Error during reverse engineering: System.Exception: The library 'hostpolicy.dll' was not found

### ISSUE THREAD

**Issue by CSam1989** [ErikEJ/EFCorePowerTools#1219] opened 2021-12-16 11:46 UTC
When reverse engineering, I get following error:

System.Exception: Table list error: 
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\Sam\AppData\Local\Temp\efreveng3.2.5.832.0\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\Users\Sam\AppData\Local\Temp\efreveng3.2.5.832.0\efreveng.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\Users\Sam\AppData\Local\Temp\efreveng3.2.5.832.0\efreveng.runtimeconfig.json' file and specify the appropriate framework.

   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)

### Steps to reproduce

Reverse engineer, After Choose Database Connection selection popup.

### Further technical details

EF Core version 3 (Cannot upgrade since project needs to run on .NETStandard 2.0)

EF Core Power Tools version: v2.5.832

Database engine: SQL Server

Visual Studio version: Visual studio 2022 17.0.1 & Visual studio 2019 16.11.7

**Comment by ErikEJ** [comment] 2021-12-16 11:52
Duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/1141 ?

**Comment by CSam1989** [comment] 2021-12-16 12:00
Hi Erik, thanks for the quick response.

Checked my environment variables PATH:
![image](https://user-images.githubusercontent.com/48630068/146367824-1a0bf7ba-64eb-4b71-809f-82b2b76eb0da.png)

x86 dotnet is beneath dotnet path

**Comment by ErikEJ** [comment] 2021-12-16 12:02
try to remove the C:\Users\Sam\AppData\Local\Temp\efreveng3.2.5.832.0 folder

also: `dotnet list --runtimes`

**Comment by CSam1989** [comment] 2021-12-16 12:05
Removing the folder did the trick!

Thanks Erik!

**Closed** 2021-12-16 12:16 UTC
