### ISSUE TITLE
Multiple constructors in DbContext not allowed

### ISSUE THREAD

**Issue by SandroRiz** [ErikEJ/EFCorePowerTools#1014] opened 2021-06-07 06:45 UTC
In a Blazor Server Side project it is suggested to not use DbContext like in asp.net core (neither of the three AddSingleton/Scoped/Transient are ok) but instead use it with a Factory 

Doing so, the DbContext cannot have multiple constructor like the one auto-generated. Commenting the first ctor without parameters resolves the issue, but you have to do every time you redo the reverse engineering

### Steps to reproduce
Create Blazor server side solution adding the dbcontext in startup.cs with
services.AddDbContextFactory<MyDbContext>(options => options.UseSqlServer(cs));

Use it in a razor component with
[Inject] public IDbContextFactory<MyDbContext> ContextFactory { get; set; }
var MyRepoService = new MyRepoService (ContextFactory.CreateDbContext());

### Further technical details
EF Core Power Tools version: 2.5.665
Database engine: SQL Server

Visual Studio version: 2019 16.10

See error
[localhost-1623047631465.log](https://github.com/ErikEJ/EFCorePowerTools/files/6606407/localhost-1623047631465.log)

**Comment by ErikEJ** [comment] 2021-06-07 13:10
I think this is a bug, that is already fixed in EF Core 6 
@ajcvickers - maybe you can confirm?

**Comment by ErikEJ** [comment] 2021-06-17 18:22
Duplicate of #991 - will be fixed in 6.0

**Closed by ErikEJ** 2021-06-17 18:22 UTC

**Comment by ErikEJ** [comment] 2021-07-11 08:42
Fixed in latest daily buidl: https://github.com/ErikEJ/EFCorePowerTools/commit/b85c77de011ecc8e7a714938d840cff6bef7e66a
