### ISSUE TITLE
Unhandled Exception on EF core 6 Mssql & VS 2022

### ISSUE THREAD

**Issue by ngocnt1** [ErikEJ/EFCorePowerTools#1193] opened 2021-11-20 08:15 UTC
Describe what is not working as expected.
It got crashing on Reverse Engineer feature as below exception :
`System.Exception: Table list error: 
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Users\....\AppData\Local\Temp\efreveng6.2.5.832.0\efreveng60.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Users\....\AppData\Local\Temp\efreveng6.2.5.832.0\efreveng60.dll'

   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)`
### Steps to reproduce
- EF core power tools > Reverse Engineer
- Pick up an Db connection
- Choose EF core 6
- Press OK
- Result to the exception on the "Extensions" Ouput window.

### Further technical details

EF Core version in use: EF Core 6.0.0

EF Core Power Tools version: 2.5.832

Database engine: SQL Server 2017 (14.0.2037.2)

Visual Studio 2022 17.0.0

**Comment by ErikEJ** [comment] 2021-11-20 10:55
Duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/1141#issuecomment-945709906

**Closed by ErikEJ** 2021-11-20 10:55 UTC
