### ISSUE TITLE
no pop  'select database' window

### ISSUE THREAD

**Issue by yuittgithub0115** [ErikEJ/EFCorePowerTools#1604] opened 2022-12-02 15:39 UTC
vs2019 + MariaDB 
when i use EF Core Power Tools, Reverse Engineer ,there no pop window to select database,  throw an exception:
System.ArgumentNullException: ......null.
parameter name:provider
  at T Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(IServiceProvider provider)
  at TView EFCorePowerTools.EFCorePowerToolsPackage.GetView<TView>()
  at async Task.......................
  at async Task EFCorePowerTools.Handlers.ReverseEngineer..........

**Comment by ErikEJ** [comment] 2022-12-02 15:40
Which Power Tools version?

**Comment by ErikEJ** [comment] 2022-12-03 06:54
Ping?

**Comment by ErikEJ** [comment] 2022-12-03 12:30
I beleive this is fixed in the latest version of the tool - duplicate of #1580

**Closed by ErikEJ** 2022-12-03 12:30 UTC
