### ISSUE TITLE
Reference to master.dacpac breaks reverse engineering from VS database project in 2.4.20

### ISSUE THREAD

**Issue by dkovacs81** [ErikEJ/EFCorePowerTools#370] opened 2020-04-16 10:17 UTC
### Steps to reproduce
1. Create a Visual Studio Database project targeting Microsoft Azure SQL Database
2. Add reference to master system database
3. Try to reverse engineer using EF Core 3.x selected
4. The process fails with version 2.4.20, but works fine with 2.4.0

### Further technical details
EF Core Power Tools version: 2.4.20
Database engine: Visual Studio Database project targeting Azure SQL Database
Visual Studio version: Visual Studio 2019

I have discovered a reverse engineering related issue in the latest version 2.4.20.

I have a single Visual Studio Database project targeting "Microsoft Azure SQL Database". The project has a single reference to master.dacpac.
Then trying reverse engineering from the Visual Studio project with EF Core 3.0 checked I got an exception:

System.UnauthorizedAccessException: Access to the path 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\EXTENSIONS\MICROSOFT\SQLDB\EXTENSIONS\SQLSERVER\AZUREV12\SQLSCHEMAS\MASTER.DACPAC' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnFile(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess)
   at GOEddie.Dacpac.References.HeaderParser.GetCustomData()
   at ReverseEngineer20.DacpacConsolidate.DacpacConsolidator.GetAllReferences(String dacpacPath)
   at ReverseEngineer20.DacpacConsolidate.DacpacConsolidator.GetAllReferences(String dacpacPath)
   at ReverseEngineer20.DacpacConsolidate.DacpacConsolidator.Consolidate(String dacpacPath)
   at ReverseEngineer20.DacpacTableListBuilder.GetTableDefinitions()
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetDacpacTables(String dacpacPath) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 339
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 117

As a workaround I tried to grant permission, so I gave full permission to Everyone on master.dacpac then the exception changed, but the process still fails:

Microsoft.SqlServer.Dac.Model.DacModelException: Add or update objects failed due to the following errors: 
Error SQL46029: Unexpected end of file occurred.

   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.ThrowIfModelErrorsExist(String errorMessage)
   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.DoAddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.DoAddOrUpdateObjects(TSqlScript inputScriptAst, String sourceName, TSqlObjectOptions options)
   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.AddOrUpdateObjects(TSqlScript inputScriptAst, String sourceName, TSqlObjectOptions options)
   at ReverseEngineer20.DacpacConsolidate.DacpacMerger.Merge()
   at ReverseEngineer20.DacpacConsolidate.DacpacConsolidator.Consolidate(String dacpacPath)
   at ReverseEngineer20.DacpacTableListBuilder.GetTableDefinitions()
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetDacpacTables(String dacpacPath) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 339
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 117

Finally, I reverted back to 2.4.0, disabled automatic updates in Visual Studio for the extension, then the reverse engineering works again as expected.

**Comment by ErikEJ** [comment] 2020-04-16 10:22
Currently working on various fixes in this area. Could you maybe share the dacpac with me privately?

**Comment by ErikEJ** [comment] 2020-04-16 10:38
Potentially, the issue is solved in the latest daily build.

**Comment by ErikEJ** [comment] 2020-04-16 13:22
Thanks for reporting this, fixed in latest daily build

@Herdo FYI!

**Closed** 2020-04-16 13:22 UTC

**Comment by ErikEJ** [comment] 2020-04-16 16:47
@dkovacs81 Would be grateful if you could help verify the fix - then I can update the package in VS MarketPlace

**Comment by jli-lhm** [comment] 2020-04-16 18:21
@ErikEJ  Thanks for the fix! I've been banging my head on the computer all day before finding out it was my master.dacpac.

**Comment by ErikEJ** [comment] 2020-04-16 18:24
So the daily build works for you?

**Comment by jli-lhm** [comment] 2020-04-16 18:31
Yep, the daily build works for me now.

**Comment by dkovacs81** [comment] 2020-04-17 14:21
I wanted to share with you a sample project, but you are too fast. :) I can confirm that reverse engineering works fine again in the new 2.4.34 version. Thanks a lot for your support and for all the effort you are putting into this great extension!

**Comment by ErikEJ** [comment] 2020-04-17 14:35
Dont worry - I was able to reproduce your issue anyway!

If you like this tool, I would be garteful for a review on VS MarketPlace 😉
