### ISSUE TITLE
Reverse Engineering Error - Nightly Build 815

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#1167] opened 2021-11-09 14:58 UTC
When I start to Reverse Engineer, after selecting the config file and Connection, I receive the error:

System.Exception: Table list error: 
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Users\bart.lynn\AppData\Local\Temp\efreveng6.2.5.815.0\efreveng60.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Users\bart.lynn\AppData\Local\Temp\efreveng6.2.5.815.0\efreveng60.dll'

   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)

### Further technical details

EF Core version in use: 6.0.0

EF Core Power Tools version: 2.5.815
Database engine: SQL Server

Visual Studio version: Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.0.0

**Comment by ErikEJ** [comment] 2021-11-09 15:54
Most likely duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/1141#issuecomment-945709906 ?

**Comment by ErikEJ** [comment] 2021-11-10 06:44
Ping?

**Comment by KayakFisher205** [comment] 2021-11-10 14:18
When you mentioned "Make sure the x64 version of dotnet is the first one in your PATH", are you saying visual studio or the C:\Windows\Microsoft.NET\Framework64\v4.0.30319? I'm not sure which one you mean. It was just strange it was working, then stopped. Maybe it was when I updated to the release of 2022

**Comment by KayakFisher205** [comment] 2021-11-10 14:31
Ok, I think I figured out. I found a folder C:\Program Files\dotnet\ and one called C:\Program Files(x86)\dotnet
I moved the x64 bit one up aove the 32bit.

Just an FYI, make the change in Environment Variables, open an Elevated Command prompt, type set path=%path% and run that. Next run echo %path% and should see the new path. Exit the command line. 

This avoids the reboots.

**Closed** 2021-11-10 16:29 UTC
