### ISSUE TITLE
CLI rewriting tables array

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2100] opened 2024-01-16 21:14 UTC
### Provide steps to reproduce a bug

I am using efcpt to scaffold out a database.  Initially I ran the command and it generated the `efcpt-config.json` as expected.  I then edited it to change the tables to look something like this (changed the names of the tables from their real values):

```json
{
  "$schema": "https://raw.githubusercontent.com/ErikEJ/EFCorePowerTools/master/samples/efcpt-schema.json",
  "code-generation": {
    "enable-on-configuring": false,
    "type": "all",
    "use-database-names": true,
    "use-data-annotations": false,
    "use-nullable-reference-types": true,
    "use-inflector": true,
    "use-legacy-inflector": false,
    "use-many-to-many-entity": false,
    "use-t4": true,
    "t4-template-path": "CodeTemplates\\EFCore\\",
    "remove-defaultsql-from-bool-properties": false,
    "soft-delete-obsolete-files": false,
    "use-alternate-stored-procedure-resultset-discovery": false,
    "merge-dacpacs": false,
    "use-decimal-data-annotation-for-sproc-results": true,
    "remove-valuegeneratedonadd": false,
    "generate-mermaid-diagram": false
  },
  "names": {
    "root-namespace": "TestNamespace",
    "dbcontext-name": "TestContext",
    "dbcontext-namespace": null,
    "model-namespace": null
  },
  "file-layout": {
    "output-path": "Models",
    "output-dbcontext-path": null
  },
  "tables": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[TableA]"
    },
    { 
      "name": "[dbo].[TableB]"
    }
  ],
  "views": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "stored-procedures": [
    {
      "exclusionWildcard": "*"
    }
  ]
}
```

Based on the documentation, this should result in only the 3 tables "TableA", "TableB", and "TableC" from being generated.  However when I run ` efcpt "<connectionstring>" mssql` again, it instead just re-adds all the tables back to the `efcpt-config.json` and generates models for all of them.  It definitely reads from the config file because it uses many of the options I've put forth, but it seems bent on adding all the tables back.

### Provide technical details

- EF Core Power Tools version: efcpt.7 7.1.41+a4ba35549504ee4de50b3d23fa874f7ecbb5cb81

- Exact Visual Studio version: N/A (CLI)

- Database engine: Azure SQL

- EF Core version in use: 7.0.14

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment] 2024-01-17 06:33
This is by design, all tables are always listed. 

Think of the list as the first screen in the VS tool.

You can use include rather than exclude.

**Comment by ErikEJ** [comment] 2024-01-17 11:02
Try this, then only TableA and TableB will be generated.

Could you point out the docs that caused a misunderstanding?

```json
"tables": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[TableA]",
      "exclude": false
    },
    { 
      "name": "[dbo].[TableB]",
      "exclude": false
    },
    { 
      "name": "[dbo].[TableC]"
    }
  ],

```

**Comment by jwyza-pi** [comment] 2024-01-17 13:25
I missed the line in the docs that said it would always include all objects.  I made an incorrect assumption that the VS Plugin version of the config file and the CLI config file would work more or less the same way.  (and in fact I really wish they were just the same file so that folks using the VS plugin could work with folks using the CLI without having to have 2 entirely different files that work differently, as our org has a mix of VS users and VSC/Rider users.)

Unfortunately, not a huge fan of having to have all DB objects in the file as it now means that projects that only reference a very small subset of our DB have to have references to every object in the DB in every repo we might use this tool in :(.  I understand this is by design, but it might be enough to shy away from it. 

Thanks for the fast response though!

**Comment by ErikEJ** [comment] 2024-01-17 13:31
@jwyza-pi Thanks for the candid feedback. 

> and in fact I really wish they were just the same file so that folks using the VS plugin could work with folks using the CLI without having to have 2 entirely different files that work differently, as our org has a mix of VS users and VSC/Rider users.

I had to change the format for the CLI to to make it more human readable and work well in VS Code. Maybe I could make the VS plugin understand the new, improved format, would that solve your issues?

> that projects that only reference a very small subset of our DB have to have references to every object in the DB in every repo we might use this tool in

What do you suggest as an alternative to not including all tables - not including any up front? Or add an option to never refresh the list, so any future database changes musy be added by hand?

**Comment by jwyza-pi** [comment] 2024-01-17 13:41
> I had to change the format for the CLI to to make it more human readable and work well in VS Code. Maybe I could make the VS plugin understand the new, improved format, would that solve your issues?

That would definitely resolve the issue of having a mix of user types.  I realize that in many orgs you're likely to have all developers use 1 IDE and not doing so introduces exactly these issues.  So it's understandable if it's not a priority to change.  But being able to use either the VS Plugin IDE or the CLI with the same file would be preferable.

> What do you suggest as an alternative to not including all tables - not including any up front? Or add an option to never refresh the list, so any future database changes musy be added by hand?

That's a tough one.  I'd say up front, adding all tables is probably the right thing, but after that, hand adding them seems like the ideal.  If you're already using a CLI, you're likely used to the fact that you'll be editing the JSON file to control it. The fact that the control of the tables is so simple/easy and that there is a schema for the json means that doing so is trivially simple. If it was some sort of arcane/complicated thing to do, that'd be something else, but it's really easy (props for that!).

**Comment by ErikEJ** [comment] 2024-01-17 14:17
@jwyza-pi 

I have created https://github.com/ErikEJ/EFCorePowerTools/issues/2102 

Proposal for this issue:

new code-generation option:

"refresh-object-lists" (default to true)

Since the default is true, all objects will be included on first run.

If false, the list of objects will be left untouched.

**Comment by jwyza-pi** [comment] 2024-01-17 14:44
both of those sound great!  Thanks for the fast responses and dialog on these items.  Is this something that you'd tag as "help-wanted" or is is this something you plan to tackle?  If it'd fall under the "help-wanted" tag, I think it would be:

* Need to add the option to [CodeGeneration.cs](https://github.com/ErikEJ/EFCorePowerTools/blob/a798195be1089723519ee76f723c3dd7357e903d/src/GUI/RevEng.Shared/Cli/Configuration/CodeGeneration.cs), with a default  of true?
* And a check here to not update the object lists if false [here](https://github.com/ErikEJ/EFCorePowerTools/blob/a798195be1089723519ee76f723c3dd7357e903d/src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs#L113)?
* add a test to [here](https://github.com/ErikEJ/EFCorePowerTools/blob/a798195be1089723519ee76f723c3dd7357e903d/src/Core/NUnitTestCore/CliObjectListTest.cs)? (doesn't seem like TryGetCliConfig is currently tested anywhere)
* Add efcpt-config.json sample and add a note about it in the readme for the CLI?

**Comment by ErikEJ** [comment] 2024-01-17 16:11
Help highly appreciated, and your work suggestions seem correct.

I would also avoid calling TableListBuilder earlier if the option is false.

**Comment by jwyza-pi** [comment] 2024-01-17 16:17
Awesome, I'll take a crack at it.  Thanks.

**Comment by ErikEJ** [comment] 2024-01-17 17:04
Great. Let me know if you run into any roadblockers

**Comment by jwyza-pi** [comment] 2024-01-17 17:35
So, on the thought about avoiding calling `TableListBuilder` earlier.  Right now GetTablesAndViews is called before the TryGetCliConfig is called which means we don't have the config yet to determine if we should get the tables or not. 

Could change the `TryGetCliConfig` method to take in an `Func<List<TableModel>>`.  This would continue to keep the separation of concerns for the 2 classes nice and separate, but wanted to get your thoughts on it as an approach.  (other approaches could be that we basically have a 2 step config where it needs to get the config, return to the ScaffoldHostedService, check if we need to populate the tables, and if we do, grab them then call something back in the CliConfigMapper. That seemed overly complicated.)


Then the code would look like this:

```csharp
        public static bool TryGetCliConfig(string fullPath, string connectionString, DatabaseType databaseType, Func<List<TableModel>> objectGenerator, CodeGenerationMode codeGenerationMode, out CliConfig config)
        {
            if (File.Exists(fullPath))
            {
                config = JsonSerializer.Deserialize<CliConfig>(File.ReadAllText(fullPath, Encoding.UTF8));
            }
            else
            {
                config = new CliConfig
                {
                    Names =
                    {
                        DbContextName = GetDbContextNameSuggestion(connectionString, databaseType),
                        RootNamespace = GetRootNamespaceSuggestion(fullPath),
                    },
                };

                if (codeGenerationMode == CodeGenerationMode.EFCore8)
                {
                    config.TypeMappings = new TypeMappings
                    {
                        UseDateOnlyTimeOnly = true,
                    };
                }
            }

            if (config.CodeGeneration.RefreshObjectLists)
            {
                if (objectGenerator == null)
                {
                    throw new ArgumentNullException(nameof(objectGenerator));
                }

                var objects = objectGenerator.Invoke();
                config.Tables = Add(objects, config.Tables);
                config.Views = Add(objects, config.Views);
                config.StoredProcedures = Add(objects, config.StoredProcedures);
                config.Functions = Add(objects, config.Functions);
            }

#pragma warning disable CA1869 // Cache and reuse 'JsonSerializerOptions' instances
            var options = new JsonSerializerOptions { WriteIndented = true };
#pragma warning restore CA1869 // Cache and reuse 'JsonSerializerOptions' instances
            File.WriteAllText(fullPath, JsonSerializer.Serialize(config, options), Encoding.UTF8);

            return true;
        }
```

and in the ScaffoldHostedService.cs would be something like:

```csharp

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
    {
        if (!CliConfigMapper.TryGetCliConfig(
                scaffoldOptions.ConfigFile.FullName,
                scaffoldOptions.ConnectionString,
                reverseEngineerCommandOptions.DatabaseType,
                GetModels,
                Constants.CodeGeneration,
                out var config))
        {
            Environment.ExitCode = 1;
            return;
        }

// rest of method down to after the return:
   List<TableModel> GetModels()
   {
       var sw = Stopwatch.StartNew();
       var tableModels = GetTablesAndViews();
       GetProcedures(tableModels);
       GetFunctions(tableModels);
       sw.Stop();
  
       DisplayService.MarkupLine();
       DisplayService.MarkupLine($"{tableModels.Count} database objects discovered in {sw.Elapsed.TotalSeconds:0.0} seconds", Color.Default);
       return tableModels;
   }
```

**Comment by ErikEJ** [comment] 2024-01-17 20:28
Let's keep it...

**Comment by ErikEJ** [comment] 2024-01-18 07:12
Actually, I think the above is an OK approach - thanks!

**Closed** 2024-01-19 08:25 UTC
Labels: enhancement, help wanted, reveng-cli

**Comment by ErikEJ** [comment] 2024-01-19 08:33
@jwyza-pi Thanks a lot for this contribution, it should be available now in the latest nightly package on NuGet

dotnet tool update --global ErikEJ.EFCorePowerTools.Cli --version 8.1.49-nightly
