### ISSUE TITLE
Unique identifier default value field not being applied.

### ISSUE THREAD

**Issue by alexkyse1** [ErikEJ/EFCorePowerTools#502] opened 2020-09-13 17:16 UTC
Since latest extension update the reverse engineering does not preserve/add up the default unique identifier sql value from the fields, this implies empty guids at database.

### Steps to reproduce
Create the following table.

```sql
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Table_1
	(
	Id int NOT NULL,
	Identifier uniqueidentifier NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Table_1 ADD CONSTRAINT
	DF_Table_1_Identifier DEFAULT newid() FOR Identifier
GO
ALTER TABLE dbo.Table_1 ADD CONSTRAINT
	PK_Table_1 PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Table_1 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
```

Reverse engineer it, try to persist a fresh created object from c# layer without assigning any value to identifier field. It will get persisted as empty guid.

The cause:

![image](https://user-images.githubusercontent.com/10980733/93024290-98f1d680-f5f5-11ea-832f-04f3af9c8517.png)

### Further technical details
EF Core Power Tools version: 2.4.182

Database engine: Azure SQL Server

Visual Studio version: Microsoft Visual Studio Community 2019 - Version 16.7.3

Edited: rearranged version numbers

**Comment by ErikEJ** [comment] 2020-09-13 19:02
Was is the left and what is the right screen??

**Comment by alexkyse1** [comment] 2020-09-13 19:06
> Was is the left and what is the right screen??

Sorry, I should have specified it previously. Basically the overview is from a commit before and after the reverse engineering since the extension version update without changing the configuration of these columns at database.

At the left you can see the context with the previous default sql values binded at the unique identifier field.
At the right you can see the context without these values, resulting in a object persistence with not initialized guid string: "00000000-0000-0000-0000-000000000000"

**Comment by ErikEJ** [comment] 2020-09-13 19:11
Ok, I will try to replicate, wonder why no-one else has reported this. Are you 100% sure the defaults are present in the database you reverse engineer?

**Comment by alexkyse1** [comment] 2020-09-13 19:13
Cool!



> Ok, I will try to replicate, wonder why no-one else has reported this. Are you 100% sure the defaults are present in the database you reverse engineer?

Cool, thanks!

I guess there was not enough time to catch it up? 

Yes, I'm 100% sure, I did not apply any changes at database for these fields. Hopefully you can reproduce it with the provided information.

**Comment by ErikEJ** [comment] 2020-09-13 19:26
Unable to reproduce...

```csharp
            modelBuilder.Entity<Table1>(entity =>
            {
                entity.ToTable("Table_1");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Identifier).HasDefaultValueSql("(newid())");
            });

```

**Comment by ErikEJ** [comment] 2020-09-15 10:15
As I am unable to reproduce based on the provided script, I am closing this. Feel free to re-open if additional info appears.

**Closed by ErikEJ** 2020-09-15 10:15 UTC

**Comment by ErikEJ** [comment] 2020-09-26 12:16
@alexkyse1 Maybe related to #515 ?

**Comment by ErikEJ** [comment] 2020-09-30 13:00
I will add a check for the user being allowed to view definition, see #520
