### ISSUE TITLE
Table-valued functions not generated on reverse engineering.

### ISSUE THREAD

**Issue by freekwernas** [ErikEJ/EFCorePowerTools#1008] opened 2021-06-03 07:53 UTC
Hi Erik,

I just recently discovered I cannot reverse engineer Table-valued functions, is this something that is known or is it a feature that still has to be added?
![image](https://user-images.githubusercontent.com/18334535/120608306-586f0d00-c451-11eb-892f-09074b4c2c54.png)
(This is what is generated)

![image](https://user-images.githubusercontent.com/18334535/120608379-6d4ba080-c451-11eb-8bd0-48b25114bcee.png)
(These are the ones missing)

Further technical details
EF Core Power Tools version: 2.5.665

Database engine: SQL Server

Visual Studio version: Microsoft Visual Studio Proffesional 2019 Version 16.10.0

csproj file:
TargetFramework:net5.0
Microsoft.EntityFrameworkCore.Design Version="5.0.6"
Microsoft.EntityFrameworkCore.SqlServer Version="5.0.6"
Microsoft.EntityFrameworkCore.Tools Version="5.0.6"

**Comment by ErikEJ** [comment] 2021-06-03 08:17
Duplicate of #1006

**Closed by ErikEJ** 2021-06-03 08:17 UTC
