### ISSUE TITLE
Oracle connection not created

### ISSUE THREAD

**Issue by FerdinandoCavaliere** [ErikEJ/EFCorePowerTools#1199] opened 2021-11-25 07:34 UTC
Hi! I've a problem with oracle database connection.

I open "Choose database connection". I click on "Add" to create a connection to the Oracle 12c databse. I choose ".NET Framework Data Provider for Oracle" as my data provider. I enter the connection name, username and password in the tnsnames.ora file. I click on "Test Connection" and everything is fine but when I click on "Ok", the connection is lost and in "Choose database connection" there is no connection

EF Core version in use: 5

EF Core Power Tools version: 2.5.832.0

Database engine: Oracle 12c

Visual Studio version: Visual Studio 2019 16.11.6

**Comment by ErikEJ** [comment] 2021-11-25 08:05
I am not sure tnsnames.ora based connections work.

**Comment by ErikEJ** [comment] 2021-11-25 18:15
Duplicate of #1067

**Closed** 2021-11-25 18:15 UTC
