### ISSUE TITLE
EF Core 7 Reverse Engineer Changing ICollection to Read Only

### ISSUE THREAD

**Issue by MissyGH** [ErikEJ/EFCorePowerTools#1669] opened 2023-01-25 14:47 UTC
Reverse engineering using EF Core 6 defines my collection like this:

        public virtual ICollection<Programming> Programmings { get; set; }

Selecting EF Core 7, the same collection is defined like this:

    public virtual ICollection<Programming> Programmings { get; } = new List<Programming>();

These collections are in the Equipment model and refer to the Programming model.  The Programming table has a foreign key that references the PK in the Equipment Table.

### Provide steps to reproduce
 
Reverse engineer a table with a foreign key and it will crease a read only list now.

### Provide technical details

EF Core version in use: EF Core 7

Is Handlebars used: no

Is T4 used: no

Is .dacpac used: no

EF Core Power Tools version:  2.5.1277

Database engine: SQL Server

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment] 2023-01-25 16:26
Duplicate of #1587

**Closed by ErikEJ** 2023-01-25 16:26 UTC

**Comment by MissyGH** [comment] 2023-01-25 20:45
Thanks for pointing me to the solution and thanks for the awesome extension.  I left you a review :)

**Comment by ErikEJ** [comment] 2023-02-16 07:23
A fix for this [is considered](https://github.com/dotnet/efcore/issues/30286#issuecomment-1431244084) by the EF Core team, and I have included the fix in the latest daily (if you use T4 templates)
