### ISSUE TITLE
Inital migration needed for migration tool

### ISSUE THREAD

**Issue by psijkof** [ErikEJ/EFCorePowerTools#30] opened 2018-05-26 16:44 UTC
Opening the migrations tool without having a single migration yet results in error message.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

599

---------------------------
Microsoft Visual Studio
---------------------------
EF Core Power Tools

Error:

System.ArgumentException: Absolute path information is required.

Parameter name: path

   at System.Reflection.Assembly.LoadFile(String path)

   at ReverseEngineer20.EfCoreModelBuilder.GetOperations(String outputPath) in C:\Code\EFCorePowerTools\src\GUI\ReverseEngineer20\EFCoreModelBuilder.cs:line 83

   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\ReverseEngineer20\EFCoreModelBuilder.cs:line 34

   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 40

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
sql server (localdb)

Visual Studio version: (e.g. Visual Studio 2017 15.7)
15.7.2

It would be awesome to have the tool create a db context from a given model (namespace). I feel that is missing. Reverse engineering works very good. Just could use some help in code first scenario

**Comment by ErikEJ** [comment] 2018-05-26 16:53
>> System.ArgumentException: Absolute path information is required.
I am not able to reproduce, could you share a project that causes this issue to oocur?

**Comment by ErikEJ** [comment] 2018-05-26 16:53
>> It would be awesome to have the tool create a db context from a given model (namespace). I feel that is missing. Reverse engineering works very good. Just could use some help in code first scenario

Could you clarify this with an example, I do not understand this

**Comment by psijkof** [comment] 2018-05-26 17:13
[ConsoleApp1.zip](https://github.com/ErikEJ/EFCorePowerTools/files/2041817/ConsoleApp1.zip)

But basically what i did was, reverse engineer an existing database. build solution, use migration tool

**Comment by psijkof** [comment] 2018-05-26 17:15
As to code first: Maybe I'm missing something, but after I defined my model classes, I have to manually create a db context. It would be awesome to 'reverse engineer' the model classes and generate a dbcontext.

**Comment by ErikEJ** [comment] 2018-05-26 18:09
OK, this issue is just a bug (your test project is a .NET Core project, and I have not done enough testing with that project type)

**Comment by ErikEJ** [comment] 2018-05-26 18:12
Fixed in latest daily build, thanks for reporting this!

**Closed** 2018-05-26 18:11 UTC
