### ISSUE TITLE
Add support for Oracle

### ISSUE THREAD

**Issue by uurcakmak** [ErikEJ/EFCorePowerTools#225] opened 2019-06-13 08:47 UTC
Hello,

Since Oracle released it's provider (ManagedDataAccess.Core and EntityFramework.Core - beta4 as of today), is it possible to adapt the Power Tools to work with Oracle ? I can confirm that Scaffold-DbContext command works on pmc but when I try to add connection for Oracle in Power Tools, all I get is empty list or servers. Test connection is succesful though.

**Comment by ErikEJ** [comment] 2019-06-13 09:10
Yes, support needs to be added explicitly, like it was done recently for MySQL

**Comment by ErikEJ** [comment] 2019-06-13 09:11
But let's wait until it is no longer in beta

**Comment by TwentyFourMinutes** [comment] 2019-07-30 14:04
It seems that it is no longer in Beta, see [nuget](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/2.19.30). So any plans on adding support?

**Comment by ErikEJ** [comment] 2019-07-30 14:06
@TwentyFourMinutes  I will take a PR for this for sure, look at the PR here for inspiration https://github.com/ErikEJ/EFCorePowerTools/pull/182 - I do not have any Oracle knowledge og database server handy.

**Comment by ErikEJ** [comment] 2019-10-15 10:00
Duplicate of #288

**Comment by ErikEJ** [comment] 2020-04-04 13:05
https://github.com/ErikEJ/EFCorePowerTools/pull/182/files

**Comment by ErikEJ** [comment] 2020-04-04 13:06
Oracle components are now available:
https://www.oracle.com/database/technologies/dotnet-odtvsix-vs2019-downloads.html
https://www.nuget.org/packages/Oracle.ManagedDataAccess/

**Comment by ErikEJ** [comment] 2020-04-04 17:30
@gardner711 @kuldip1490  @uurcakmak @iformas @bricelam @davidcook-ms 
I have now created a PR that enables Oracle support - would be very grateful if one of you could try it out (in debug) - if you cannot do that, I can share a VSIX. https://github.com/ErikEJ/EFCorePowerTools/pull/361

**Comment by ErikEJ** [comment] 2020-04-08 10:01
Had to revert, as the Oracle EF Core provider was hardcoded to use EF Core 2.1.11 iso 2.2 😢

**Comment by uurcakmak** [comment] 2020-04-09 12:31
Hi,

Sorry for the delay, I can test it if you provide a version works with Microsoft.EntityFrameworkCore 3.1.3. Is it possible for you to provide a version which doesn't rely on hardcoded EFCore 2.x ?

**Comment by ErikEJ** [comment] 2020-04-09 12:37
Sorry, I had to roll back this. The Oracle provider only supports EF Core 2.1, and I need 2.2 support across the board for EF Core 2 support. You can most likely use EF Core 2 scaffolding with an EF core 3 project, but I cannot enable Oracle support before the Oracle EF Core provider has been updated to 2.2. feel free to contact Oracle support in order to ask for this!

**Comment by ErikEJ** [comment] 2020-04-18 17:15
Update: Oracle has stated they intend to release a 3.1 provider in May (presumably 2020)

**Comment by uurcakmak** [comment] 2020-05-30 09:02
Hi,
Oracle provided a beta for EF Core 3.1. Is it suffice for you to release a beta version of your extension which works with oracle now ?

**Comment by ErikEJ** [comment] 2020-05-30 09:04
@uurcakmak Link?

**Comment by ErikEJ** [comment] 2020-05-30 09:05
@uurcakmak And can you help with testing?

**Comment by uurcakmak** [comment] 2020-05-30 09:08
@ErikEJ Here is the link for beta:
https://www.nuget.org/packages/Oracle.EntityFrameworkCore/3.19.0-beta1

Yes, I can help you in testing.

**Comment by kuldip1490** [comment] 2020-06-05 12:36
Can you please provide me the guidelines? 
Still, I am getting ....

  
    On Tuesday, 2 June, 2020, 10:30:45 pm IST, Erik Ejlskov Jensen <notifications@github.com> wrote:  
 
 


Closed #225 via #397.

**Comment by ErikEJ** [comment] 2020-06-05 12:38
What are you still getting - it is now part of the latest daily build?

**Comment by ErikEJ** [comment] 2020-06-05 12:39
If you need help, please share screenshots and/or error messages/logs

**Comment by kuldip1490** [comment] 2020-06-05 12:44
is that latest version  ?



    On Friday, 5 June, 2020, 06:10:02 pm IST, Erik Ejlskov Jensen <notifications@github.com> wrote:  
 
 


If you need help, please share screenshots and/or error messages/logs

**Comment by ErikEJ** [comment] 2020-06-05 12:46
>> is that latest version  ?

Not sure what you are asking? It is in the latest daily build yes, but not in the latest version on VS Marketplace

**Comment by ErikEJ** [comment] 2020-06-05 12:47
If you are sharing screenshots, please do not reply to emails, but post your reply directly on Github.com, thanks.

**Comment by kuldip1490** [comment] 2020-06-05 12:55
EF Core Power Tools version: 2.4.67.0 and I downloaded  from the latest build.

    On Friday, 5 June, 2020, 06:18:01 pm IST, Erik Ejlskov Jensen <notifications@github.com> wrote:  
 
 


If you are sharing screenshots, please do not reply to emails, but post your reply directly on Github.com, thanks.

**Comment by ErikEJ** [comment] 2020-06-05 13:41
@kuldip1490  that's the correct build, but I still have no idea what issue you are facing, if any.

**Comment by kuldip1490** [comment] 2020-06-05 13:51
Still  I am getting empty drop-down  list after successfull connections 
Get Outlook for Android



On Fri, Jun 5, 2020 at 7:11 PM +0530, "Erik Ejlskov Jensen" <notifications@github.com> wrote:















@kuldip1490  that's the correct build, but I still have no idea what issue you are facing, if any.

**Comment by ErikEJ** [comment] 2020-06-05 13:54
Do you use the Oracle Visual Studio Tools ? (Or DevArt) - you must use the Oracle Tools as described in the wiki.

**Comment by kuldip1490** [comment] 2020-06-05 14:01
I used it. But nothing happened 
Get Outlook for Android



On Fri, Jun 5, 2020 at 7:24 PM +0530, "Erik Ejlskov Jensen" <notifications@github.com> wrote:















Do you use the Oracle Visual Studio Tools ? (Or DevArt) - you must use the Oracle Tools as described in the wiki.

**Comment by ErikEJ** [comment] 2020-06-05 14:10
Does the connection appear in Server Explorer?

**Comment by kuldip1490** [comment] 2020-06-05 14:58
No
Get Outlook for Android



On Fri, Jun 5, 2020 at 7:40 PM +0530, "Erik Ejlskov Jensen" <notifications@github.com> wrote:















Does the connection appear in Server Explorer?

**Comment by ErikEJ** [comment] 2020-06-05 15:08
# Ok, that explains why you are not seeing it in the drop-down list.

Can you add an connection via Server Explorer?

**Comment by ErikEJ** [comment] 2020-06-05 15:25
I am asking you to try and add one via Server Explorer, please!

**Comment by kuldip1490** [comment] 2020-06-06 07:33
Here is the error after a successful connection:

**Comment by kuldip1490** [comment] 2020-06-06 07:42
racle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12154: TNS:could not resolve the connect identifier specified ---> OracleInternal.Network.NetworkException (0x00002F7A): ORA-12154: TNS:could not resolve the connect identifier specified   at OracleInternal.Network.AddressResolution..ctor(String TNSAlias, SqlNetOraConfig SNOConfig, Hashtable ObTnsHT, String instanceName, ConnectionOption CO)   at OracleInternal.Network.OracleCommunication.Resolve(String tnsAlias, ConnectionOption& CO)   at OracleInternal.ConnectionPool.PoolManager`3.ResolveTnsAlias(ConnectionString cs, Object OC)   at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()   at ErikEJ.SqlCeToolbox.Helpers.EnvDteHelper.GetOracleTableNames(String connectionString, Boolean includeViews) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Helpers\EnvDTEHelper.cs:line 280   at ErikEJ.SqlCeToolbox.Helpers.RepositoryHelper.GetTablesFromRepository(DatabaseInfo dbInfo, Boolean includeViews) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Helpers\RepositoryHelper.cs:line 64   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 117

**Comment by ErikEJ** [comment] 2020-06-06 09:13
I have no clue - does the connection work from Server Explorer?

**Comment by kuldip1490** [comment] 2020-06-06 11:46
Yes, its working from server connection

**Comment by ErikEJ** [comment] 2020-06-06 12:25
Have a look a my code, maybe I am using Oracleconnection incorrectly.

**Comment by kuldip1490** [comment] 2020-06-06 13:23
I am getting missing namespace or reference. Do you have any idea about it?Microsoft.Data.Tool.UtilitesMicrosoft.Data.Tool.Schema.Sql

**Comment by ErikEJ** [comment] 2020-06-06 15:18
I what context are you getting that error?

**Comment by ErikEJ** [comment] 2020-06-06 15:44
Have you tried troubleshooting ora-12154 ?

**Comment by kuldip1490** [comment] 2020-06-08 04:21
I found that TNSname.ora does not exist. In the project, I m getting an error while build. 

![image](https://user-images.githubusercontent.com/22524273/83992327-8e2c0380-a96d-11ea-9029-a24aa8fa00e0.png)

**Comment by ErikEJ** [comment] 2020-06-08 05:33
@kuldip1490 Restore NuGet packages

**Comment by kuldip1490** [comment] 2020-06-08 05:43
Okay, now it's done. So Now, How can I debug your code ?

**Comment by ErikEJ** [comment] 2020-06-08 05:55
I actually did not ask you to debug my code, but that will of course be very helpful, jus follow the readme instructions to debug via F5, and collect as much information as possible about any issues you encounter.

**Comment by kuldip1490** [comment] 2020-06-08 05:57
Thank you

**Comment by ProH4Ck** [comment] 2020-06-08 08:28
I'm testing the implementation and I got error ORA-00904. I made a PR to fix this:

https://github.com/ErikEJ/EFCorePowerTools/pull/401

**Comment by ErikEJ** [comment] 2020-06-08 10:44
@ProH4Ck PR merged, thanks -  @kuldip1490 FYI (get latest master)

**Comment by ProH4Ck** [comment] 2020-06-08 13:13
Finally I let Oracle Developer Tools work in experimental instance 😄 
After the fix, I can select tables from EF Core Power Tool dialog but Entitites are not generated.
The problem is that EF Core scaffolding doesn't supports tables in format (SCHEMA.TABLE). 
You can call it with one or more schemas but in this case all tables inside the schema are created.
Actually the only workaround is pass all schemas and then filter the ScaffoldedModel to create only file specific to table selected in UI...

**Comment by ErikEJ** [comment] 2020-06-08 13:38
Fantastic!

>> The problem is that EF Core scaffolding doesn't supports tables in format (SCHEMA.TABLE).

That sounds like a limitation in the Oracle EF Core provider. Let me investigate - there is some information in the readme pdf for the provider

**Comment by ProH4Ck** [comment] 2020-06-08 13:57
> Fantastic!
> 
> > > The problem is that EF Core scaffolding doesn't supports tables in format (SCHEMA.TABLE).
> 
> That sounds like a limitation in the Oracle EF Core provider. Let me investigate - there is some information in the readme pdf for the provider

I tried hardcoding 2 schemas and 4 tables but 
```
scaffolder.ScaffoldModel(
  reverseEngineerOptions.Dacpac ?? reverseEngineerOptions.ConnectionString,
  dbOptions,
  modelOptions,
  codeOptions);
```

always output all tables in all schemas

**Comment by ErikEJ** [comment] 2020-06-08 15:19
Maybe you could take a step back, and find out how the provider handles the "dotnet  dbcontext scaffold" / Scaffold-Database command?

**Comment by ErikEJ** [comment] 2020-06-08 15:22
This is the docs from the EF Core provider readme:

![image](https://user-images.githubusercontent.com/4169187/84049374-a8390680-a9ac-11ea-8ee2-53e716fefecc.png)

**Comment by ProH4Ck** [comment] 2020-06-09 07:59
> Maybe you could take a step back, and find out how the provider handles the "dotnet dbcontext scaffold" / Scaffold-Database command?

I think I found the problem but since provider is not open-sourced we need to wait Oracle.
Here is the issue opened with full analysis: https://github.com/oracle/dotnet-db-samples/issues/73

**Comment by ErikEJ** [comment] 2020-06-09 08:04
Excellent!

**Comment by ErikEJ** [comment] 2020-06-13 11:26
I will await an update of the EF Core 3 Oracle provider.

**Comment by kuldip1490** [comment] 2020-06-13 11:49
Okay. we are waiting

**Comment by ErikEJ** [comment] 2020-07-18 11:27
Latest daily build contains beta 2 of the Oracle provider, which should fix a number of scaffolding issues: https://github.com/oracle/dotnet-db-samples/issues/73#issuecomment-660308368

**Comment by ErikEJ** [comment] 2020-07-18 11:28
(Need help in getting a list of Oracle "views" as well)

**Comment by ErikEJ** [comment] 2020-09-12 05:22
Latest daily build now contains the 3.1 RTM provider

**Closed by ErikEJ** 2020-09-12 05:22 UTC
Labels: enhancement, reveng
