### ISSUE TITLE
Unable to reverse engineer stored procedure objects

### ISSUE THREAD

**Issue by ngamanning** [ErikEJ/EFCorePowerTools#1238] opened 2021-12-30 00:11 UTC
Before the latest update, the tool was able to create EF models from stored procedures that use temp table. Though there was error in output window, the model class was still created on Reverse Engineering command. This was working in November. 
Now, if the sproc uses temp table, the Reverse Engineering command does not create the model class at all! 

### Further technical details

EF Core version in use: EFCore5

EF Core Power Tools version: 2.5.866

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.11.5

**Comment by ErikEJ** [comment] 2021-12-30 06:50
Duplicate of #1236 - fixed in the latest daily build.

Was a regresssion cuased by adding (optional) support for multiple result sets.

**Comment by ErikEJ** [comment] 2021-12-30 07:01
I have published the latest daily to MarketPlace

**Closed by ErikEJ** 2021-12-30 07:01 UTC

**Comment by ngamanning** [comment] 2021-12-30 17:35
Thank you sir! I reinstalled the extension and I can confirm the latest fix has resolved the issue.
