### ISSUE TITLE
NodaTime conversion Issue

### ISSUE THREAD

**Issue by kenbo017** [ErikEJ/EFCorePowerTools#1613] opened 2022-12-13 04:12 UTC
Describe what is not working as expected.

### Provide steps to reproduce

I am using EF Core version 5.1.4 with .net5.  I just ran the reverse engineering and am now getting an error that I can't convert type
System.DateTime? to NodaTim.LocalDate.  I have not changed any packages I have installed, so I tried to rerun the reverse engineering.  I noticed that the dropdown for the version has only Core 3 as a choice.  Previously, there was Core 5 and Core 6 available as choices.  I'm not sure what happened.  Do I need to install a different Noda Time package (I am using SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime Version 5.0.3).  Its dependency is .net2 so I think I should be okay and it was what I had installed before I just tried to reverse engineer my SQL changes.

I am using VS 2022 Community and SQL Server 15.0.18424.0

**Comment by ErikEJ** [comment] 2022-12-13 06:12
@kenbo017 Just make sure that the advanced option to map NodaTime is checked. 

If the mapping is there, and you get runtime errors, suggest you raise an issue with repro details in the NodaTime repository.

For the EF Core 5 issue, duplicate of #1585

**Comment by kenbo017** [comment] 2022-12-13 21:35
Hello!

Thank you for your quick reply.

The Use Noda Time is selected in the advanced options.  I believe the issue is similar to what was mentioned in the case you gave me the link to.  I tried changing to Core 3 and I ran into the issue with the Syncfusion controls for WPF not working with Core.  I believe I will need to "unwind" back to the latest release so I can continue in .net 5 as my application is a WPF application.  I can reach out to Syncfusion to see if they have options to migrate to Core 3 for their WPF controls.

Regards,


KS


Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.******@***.***>


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain privileged, confidential and/or protected information and is intended only for the review of the party to whom it is addressed. Any unauthorized use or disclosure of the information contained herein may be a violation of federal law. If you have received this transmission in error, please immediately return it to the sender, delete it and destroy it without reading it. Unintended transmission shall not constitute the waiver of the attorney-client or any other privilege.


________________________________

**Comment by ErikEJ** [comment] 2022-12-14 06:24
.NET 5 and EF Core 5 have both been out of support for quite some time. You should upgrade to EF Core 6 and .NET 6.

You can contact me by email to get a link to a build that works with EF Core 5 but is completely unsupported by me.

**Closed by ErikEJ** 2022-12-14 06:25 UTC

**Comment by kenbo017** [comment] 2022-12-14 23:54
Hi Erik,

Thank you so much for your advice!  I upgraded to .NET 7 and EF Core 7 and everything is working again.

Regards,


KS


Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.******@***.***>


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain privileged, confidential and/or protected information and is intended only for the review of the party to whom it is addressed. Any unauthorized use or disclosure of the information contained herein may be a violation of federal law. If you have received this transmission in error, please immediately return it to the sender, delete it and destroy it without reading it. Unintended transmission shall not constitute the waiver of the attorney-client or any other privilege.


________________________________
