### ISSUE TITLE
Error VS 2022

### ISSUE THREAD

**Issue by peretodk** [ErikEJ/EFCorePowerTools#1874] opened 2023-07-13 11:13 UTC
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/108901006/055fdf41-29e5-4877-b178-58ebdbb25daa)

<entry>
    <record>426</record>
    <time>2023/07/13 11:09:22.549</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [EFCorePowerToolsPackage]Source: &apos;EFCorePowerTools&apos; Description: Method not found: &apos;Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()&apos;.&#x000D;&#x000A;System.MissingMethodException: Method not found: &apos;Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()&apos;.&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;InitializeAsync&gt;d__11.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>0x80131513</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by ErikEJ** [comment] 2023-07-13 11:18
Please try the latest build .1535 - and which exact VS version  do you have?

**Comment by jli-lhm** [comment] 2023-07-13 11:30
Also not working for me and I have the latest .1535 build, clicking reverse engineer and nothing happens.

Microsoft Visual Studio Professional 2022 - Version 17.4.1

**Comment by ErikEJ** [comment] 2023-07-13 11:32
@jli-lhm That sound like a different issue! But try to update to 17.5

**Comment by ErikEJ** [comment] 2023-07-13 12:38
@PeterMontgomery777 I am unable to reproduce using VS 17.6, try to update to 17.6.5 (sorry for typo above)

**Comment by PeterMontgomery777** [comment] 2023-07-13 12:40
Thanks for the quick response! I'll try updating VS later this afternoon and let you know.

**Comment by ErikEJ** [comment] 2023-07-13 12:41
I am still trying to figure out what is going on here...

**Comment by peretodk** [comment] 2023-07-13 15:34
Thanks Work with  VS 17.6.5

**Comment by ErikEJ** [comment] 2023-07-14 08:40
@aarnott @madskristensen

Version 17.5.4074 of Microsoft.VSSDK.BuildTools does not include the SDK files in the vsix!
Version 17.5.2164 of Microsoft.VSSDK.BuildTools does includes all the SDK files in the vsix!

**Comment by ErikEJ** [comment] 2023-07-14 08:44
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by AArnott** [comment] 2023-07-14 14:49
@ErikEJ Including copies of DLLs in your VSIX that VS itself ships can absolutely cause problems like this. The CLR may load your DLL instead of (or maybe in addition to, depending on load context) the ones in VS and screw up all kinds of things including things like this. It sounds like you removed them recently, which is great and should be the right way to go.

**Comment by ErikEJ** [comment] 2023-07-14 14:52
@AArnott I did not "remove" them, I downgraded the build Tools version from 17.6 to 17.5 - I assume 17.6 caused them to be included.

**Comment by AArnott** [comment] 2023-07-14 15:25
Well, however you did it, if your new VSIX doesn't include them, that's what counts. If 17.6 VS SDK buildtools 'added' them, that sounds like a serious bug that ... might even be known about internally already. I heard rumors.

**Comment by ErikEJ** [comment] 2023-07-14 15:56
@@AArnott Thanks a lot. If you need help with the 17.6 issue let me know.

**Closed** 2023-07-14 15:56 UTC
Labels: bug

**Comment by Gargaj** [comment] 2024-02-26 13:19
> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

Just for the sake of whoever is googling the same error for a different project and is looking for a fix, the fix was https://github.com/ErikEJ/EFCorePowerTools/commit/2b627a998aaf94e4c1e58f85d82f014412610faa :)

**Comment by BlackbirdSQL** [comment] 2024-03-12 21:51
It seems this thing has reared it's ugly head again in Visual.Studio.SDK 17.9.37000.

**Comment by ErikEJ** [comment] 2024-03-12 21:57
@BlackbirdSQL yes, I reported this here: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/432
