### ISSUE TITLE
EF Core Power Tools CLI enable-on-configuring missing a constructor with no parameters

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#1924] opened 2023-08-23 03:56 UTC
### Provide steps to reproduce a bug

1. Create database using [this script](https://gist.githubusercontent.com/doggy8088/2a2f7075d49b3814d19513426ede3549/raw/ba8c4e7d46597188a17a39de7906d358f18d834d/ContosoUniversity.sql).

2. Create a Console app

    ```
    dotnet new console -n c1
    ```

3. Create Models using [EF Core Power Tools CLI](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efcpt/readme.md)

    ```
    efcpt "Server=(localdb)\MSSQLLocalDB;Database=ContosoUniversity" "Microsoft.EntityFrameworkCore.SqlServer"
    ```

5. Modify `efcpt-config.json` file, set `enable-on-configuring` to `true`.

    ```json
      "code-generation": {
        "enable-on-configuring": true,
    ...
    ```

6. Create Models again

    ```
    efcpt "Server=(localdb)\MSSQLLocalDB;Database=ContosoUniversity" "Microsoft.EntityFrameworkCore.SqlServer"
    ```

7. Check for `Models\ContosoUniversityContext.cs` file.

    **It actually lack of a constructor with no parameters. It's required for `dotnet-ef` and some other design-time tools.**

9. Install two NuGet packages

    ```
    dotnet add package Microsoft.EntityFrameworkCore.Design
    dotnet add package Microsoft.EntityFrameworkCore.SqlServer
    ```

10. Add migration

    ```
    dotnet ef migration add Init
    ```

    Error occurred:

    ```
    Build started...
    Build succeeded.
    Unable to create an object of type 'ContosoUniversityContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
    ```

### Provide technical details

- EF Core Power Tools version: `2.5.1544`

- Exact Visual Studio version: `Visual Studio 2022 17.7.1`

- Database engine: SQL Server

- EF Core version in use: `EF Core 7`

- Is Handlebars templates used: `no`

- Is T4 templates used: `no`

- Is a SQL Server .dacpac used: `no`

**Comment by ErikEJ** [comment] 2023-08-23 05:55
Duplicate of #1737 - by design

**Comment by doggy8088** [comment] 2023-08-23 15:59
Do you have any link related to by design with EF Core 7?

**Comment by ErikEJ** [comment] 2023-08-23 16:05
I think it is related to intro of t4. You can use t4 to bring it back.

**Comment by doggy8088** [comment] 2023-08-24 15:50
At first, I provide a document for you 👉 [Using a constructor with no parameters](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?WT.mc_id=DT-MVP-4015686&tabs=dotnet-core-cli#using-a-constructor-with-no-parameters).

> If the DbContext can't be obtained from the application service provider, the tools look for the derived DbContext type inside the project. Then they try to create an instance using a constructor with no parameters. This can be the default constructor if the DbContext is configured using the OnConfiguring method.

I want to provide steps using `dotnet-ef` compare with `efcpt`.

1. Create database using [this script](https://gist.githubusercontent.com/doggy8088/2a2f7075d49b3814d19513426ede3549/raw/ba8c4e7d46597188a17a39de7906d358f18d834d/ContosoUniversity.sql).

2. Create a Console app

    ```
    dotnet new console -n c1
    cd c1
    ```

3. Add `Microsoft.EntityFrameworkCore.Design` and `Microsoft.EntityFrameworkCore.SqlServer` packages

    ```sh
    dotnet add package Microsoft.EntityFrameworkCore.Design
    dotnet add package Microsoft.EntityFrameworkCore.SqlServer
    ```

3. Create Models using `dotnet ef dbcontext scaffold `

    ```
    dotnet ef dbcontext scaffold "Server=(localdb)\MSSQLLocalDB;Database=ContosoUniversity" "Microsoft.EntityFrameworkCore.SqlServer" -o Models
    ```

5. Check for `Models\ContosoUniversityContext.cs` file.

    **It actually contains a constructor with no parameters. It's vital for `dotnet-ef` and some other design-time tools.**

    ```cs
    using System;
    using System.Collections.Generic;
    using Microsoft.EntityFrameworkCore;

    namespace c1.Models;

    public partial class ContosoUniversityContext : DbContext
    {
        public ContosoUniversityContext()
        {
        }

        public ContosoUniversityContext(DbContextOptions<ContosoUniversityContext> options)
            : base(options)
        {
        }

        ...
    }
    ```

**Comment by ErikEJ** [comment] 2023-08-24 16:22
Thanks a lot! I will have a look

**Comment by ErikEJ** [comment] 2023-08-24 17:09
Looks like a CLI Bug...

**Comment by ErikEJ** [comment] 2023-08-25 06:18
@doggy8088  Hmm.. EF Core 7 reverse engineering does not create the default constructor, are you sure you are using the EF Core 7 tools in your repro above. I think you must use T4 templates or partial classes with EF Core 7 to get the constructor back.

**Comment by doggy8088** [comment] 2023-08-25 06:45
I think so. 😄

**Closed** 2023-08-25 06:56 UTC
Labels: bug, reveng-cli

**Comment by ErikEJ** [comment] 2023-08-25 07:10
I have just published rc.9 to NuGet - thanks for reporting this

**Comment by doggy8088** [comment] 2023-08-25 14:16
I tested. It works perfectly.

**Comment by ErikEJ** [comment] 2023-08-25 14:21
Cool, I will publish a new tool version
