### ISSUE TITLE
Stored Procedure Call with Additional Logic to do validation is not generated correctly

### ISSUE THREAD

**Issue by nssidhu** [ErikEJ/EFCorePowerTools#1120] opened 2021-09-24 00:32 UTC
--This throws runtime error when ID is not passed or is empty, but works well if the ID is passed and Select statement is 
executed. Also the return class is generated correctly
```
CREATE PROCEDURE [dbo].[sp_TEST]
(

        @ID uniqueidentifier,
	@Name varchar(100),
	@ErrorMessage varchar(500) OUTPUT
)
AS
BEGIN

BEGIN TRY  

  
	IF @ID IS NULL OR LTRIM(RTRIM( @ID)) ='' OR  @ID ='00000000-0000-0000-0000-000000000000')
	BEGIN
		 SET @ErrorMessage='Required Parameter ID was not supplied'
		 Return 0
	END

		SELECT Fiel1, Field2,field3,Field4
		FROM [dbo].[TestTable] WHERE [ID] = @ID

		RETURN 1;
END TRY  
BEGIN CATCH 
	 SET @ErrorMessage='Try Catch Error Occured ' + ERROR_MESSAGE();
	
	 --SELECT  
		-- ERROR_NUMBER() AS ErrorNumber  
		--,ERROR_SEVERITY() AS ErrorSeverity  
		--,ERROR_STATE() AS ErrorState  
		--,ERROR_PROCEDURE() AS ErrorProcedure  
		--,ERROR_LINE() AS ErrorLine  
		--,ERROR_MESSAGE() AS ErrorMessage;  
	 Return 0;
END CATCH 
END

```
changing it to this works fine, but if we regenerate the Models from database
It does is not generated correctly  (it is just an empty class with no properties in it)
```
CREATE PROCEDURE [dbo].[sp_TEST]
(

        @ID uniqueidentifier,
	@Name varchar(100),
	@ErrorMessage varchar(500) OUTPUT
)
AS
BEGIN

BEGIN TRY  

  
	IF @ID IS NULL OR LTRIM(RTRIM( @ID)) ='' OR  @ID ='00000000-0000-0000-0000-000000000000')
	BEGIN
		 SET @ErrorMessage='Required Parameter ID was not supplied'
		 THROW 50000,@ErrorMessage,1;
	END

		SELECT Fiel1, Field2,field3,Field4
		FROM [dbo].[TestTable] WHERE [ID] = @ID

		RETURN 1;
END TRY  
BEGIN CATCH 
	 SET @ErrorMessage='Try Catch Error Occured ' + ERROR_MESSAGE();
	
	 --SELECT  
		-- ERROR_NUMBER() AS ErrorNumber  
		--,ERROR_SEVERITY() AS ErrorSeverity  
		--,ERROR_STATE() AS ErrorState  
		--,ERROR_PROCEDURE() AS ErrorProcedure  
		--,ERROR_LINE() AS ErrorLine  
		--,ERROR_MESSAGE() AS ErrorMessage; 
 
	SELECT NULL Fiel1, NULL Field2,NULL field3,NULL Field4
		FROM [dbo].[TestTable] WHERE [ID] = @ID
	 Return 0;
END CATCH 
END

```

**Comment by nssidhu** [comment] 2021-09-24 04:30
Another issue I found is that when Query is using LEFT Join, for some rows the value of those left table columns are Null and it throws error at runtime.
They way I got around is by declare those fields to  Nullable manually in the auto generated class. the problem is that this changes will be lost on next Reverse generation.
Was wondering if all the fields in the class that you auto generate should be nullable by default ?

**Comment by ErikEJ** [comment] 2021-09-24 05:21
Would be great to have one Github issue per issue you find 😄 

Re your first issue: This is by design, due to the limitations of the meta data query used, as described in the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

For the second one, please provide a full repro, so I can have a closer look at the metadata returned for the stored procedure in question. But you may have a point!

**Comment by ErikEJ** [comment] 2021-09-25 07:04
Closing this, please create another issue with a sample for issue 2.

**Closed by ErikEJ** 2021-09-25 07:04 UTC
