### ISSUE TITLE
Save "Use EF Core 3.0" in the efpt.config.json

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#318] opened 2019-12-04 11:47 UTC
The "Use EF Core 3.0" option is not saved to `efpt.config.json` file. I have to click that option every time.

![image](https://user-images.githubusercontent.com/88981/70139912-85145e00-16ce-11ea-8e71-af5eadd922c9.png)

### Steps to reproduce

1. Solution Explorer
2. Right-click on Project node
3. Choose `EF Core Power Tools`
4. Choose `Reverse Engineer`

### Further technical details
EF Core Power Tools version: `2.3.92.0`

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.4.0

**Comment by ErikEJ** [comment] 2019-12-04 12:14
Correct, this is by design. Will default to always have it checked in next release

**Comment by ErikEJ** [comment] 2019-12-29 17:56
Actually, the issue is that the efpt.config.json file is not opened at this point during the process.

**Closed** 2020-04-04 12:54 UTC
