### ISSUE TITLE
The 'EFCorePowerToolsPackage' package did not load correctly VS 2022 Preview

### ISSUE THREAD

**Issue by tfq-git** [ErikEJ/EFCorePowerTools#1059] opened 2021-07-27 06:20 UTC
The context menu shows for reverse engineer but shows error notification saying  -- The 'EFCorePowerToolsPackage' package did not load correctly
It asks to look in some activity log and this is the part I found in activity log
<entry>
    <record>2237</record>
    <time>2021/07/26 06:36:39.977</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [EFCorePowerToolsPackage]Source: &apos;EFCorePowerTools&apos; Description: Could not load file or assembly &apos;EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;InitializeAsync&gt;d__11.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>2238</record>
    <time>2021/07/26 06:36:39.981</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [EFCorePowerToolsPackage]</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

### Steps to reproduce
1. Install EF Core Power Tools 
2. Open Visual Studio 2022 Preview
3. Right-click on project, Select EF Core Power Tools > Reverse Engineer from context

### Further technical details
EF Core Power Tools Version : 2.5.692 & 2.5.717

Database engine: Microsoft SQL Server 2014

Visual Studio version: Visual Studio Community 2022 Preview (64-bit)

**Comment by ErikEJ** [comment] 2021-07-27 06:24
Duplicate of #1046

**Closed by ErikEJ** 2021-07-27 06:24 UTC
