### ISSUE TITLE
EF Core Power Tools fails to load in Visual Studio

### ISSUE THREAD

**Issue by ChuckCross** [ErikEJ/EFCorePowerTools#976] opened 2021-05-12 16:00 UTC
Error dialog box displays:    The 'EFCorePowerToolsPackage' package did not load correctly
Previously was working.  After updating Visual Studio to 16.8.3 and and EF Core Power tools to 2.5, no longer works.  Now receive error dialog.

### Steps to reproduce
Right-click any project using EF Core (previously successfully reverse engineered), select EF Core Power Tools / About.

### Further technical details
EF Core Power Tools version: 2.5 (updated through Visual Studio  May 12, 2021)

From ActivityLog.xml:

[ActivityLog.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6467424/ActivityLog.zip)

</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
  </entry>
  <entry>
    <record>3719</record>
    <time>2021/05/12 15:28:45.023</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [EFCorePowerToolsPackage]Source: &apos;EFCorePowerTools&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.8.3

**Comment by ErikEJ** [comment] 2021-05-12 16:40
Duplicate of #975

**Closed by ErikEJ** 2021-05-12 16:40 UTC
