### ISSUE TITLE
Does not generate field for the geography data type of Azure DB

### ISSUE THREAD

**Issue by nssidhu** [ErikEJ/EFCorePowerTools#442] opened 2020-08-08 01:30 UTC
If a table has Geography field, it does not generate the equivalent Point Property.
I am using EF core 5 preview on ASP.net Core 3.1

**Comment by ErikEJ** [comment] 2020-08-08 06:38
Duplicate of #438 ?

**Comment by ErikEJ** [comment] 2020-08-10 11:45
Closing, feel free to re-open if you still have issues

**Closed** 2020-08-10 12:32 UTC
