### ISSUE TITLE
Make SET FMTONLY work with TVP parameters

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1243] opened 2022-01-13 18:18 UTC
But make it work with TVP first, see repro https://github.com/ErikEJ/EFCorePowerTools/issues/1221

**Comment by CorsairRO** [comment] 2022-04-07 08:11
Hello @ErikEJ 

I have BIG NEWS about that crap... 

Converting MyTVP to nvarchar failing -> It is because SQLCommand doesnt know how to deal with DataTable params.
It just defaults to .ToString() and that is the NVARCHAR that cannot be converted to TVP while running the PROC.

Because the PROC runs FINE in SSMS with FMTONLY ON AND because parameters are TOTALLY ignored by FMTONLY,
**solution that i tested now is executing the SP without any parameters.**
Then it works fine, i can confirm that i have no error from generator AND i have my SP mapped correctly in MyContextStoredProcedurs and the result type and so on ...

**Comment by CorsairRO** [comment] 2022-04-07 08:15
However i think what would be nice addition there, and i am going to look for it will be:

Instead of using DataTable for parameter to go and get that type from DB and generate its class.
Then the proc call from code should not have DataTable but List<MyTVPClass>.
Because this is how TVP works in SQL, the generator should take List<MyTVPClass> and generated a parameter of type DataTable when it builds the parameter list to SP.
Converting List<MyTVP> to DataTable is a trivial job to add and will make much simpler to use these scenarios

**Comment by ErikEJ** [comment] 2022-04-07 08:20
Can you share the "solution that you tested" ??

**Comment by ErikEJ** [comment] 2022-04-07 17:33
@CorsairRO  Your proposed solution does not work for me...

```
CREATE   PROCEDURE [dbo].[MultiSet] (
    @Year DATETIME2(3),
    @ProductValue SMALLMONEY
) AS
BEGIN
    SELECT * FROM Shippers;
	SELECT * FROM Categories;
	SELECT * FROM Customers;
	RETURN 42
END;
GO
```

`Error: Procedure or function 'MultiSet' expects parameter '@Year', which was not supplied.
`

**Comment by ErikEJ** [comment] 2022-04-07 17:44
https://stackoverflow.com/questions/17451825/get-column-information-for-a-user-defined-table-type

**Comment by CorsairRO** [comment] 2022-04-08 06:13
@ErikEJ The solution i proposed has NOTHING to do with Multiple resultsets.
As i removed this feature from my version of the tool ( i dont use it ) i assume you can let it to work as it is today in the tool, installing dapper, bla bla ...

However i have replaced the code for SINGLE Resultset to call SP with FMTONLY ON instead of the bloody sp_get_first_result_set.
Doing just so, it works fine for me now to get resultset from 100% of my SP.
Then when i have tested a TVP as parameter reported by you as not working and the other users, i got the Operand clash nvarchar error specified in the other issue.
Removing parameter passing to SqlCommand that runs the proc with FMTONLY solves totally the problem, and code is generated like it should. 

The only thing that i will consider a real improvement there for people who really uses this in their DB would be nice instead of generating the SP method call in context with a untyped DataTable param, to try to get the real class from the TVP as MyTVPCLass, and replace the parameter as type DataTable with List of MyTVPClass.
When caling the real SP with ExecuteSql List of MyTVPClass can be easily converted to DataTable as DB expects to get for such a parameter.
I will look there if i can help to do such a thing and let you know

**Comment by DavidCAllenMI** [comment] 2022-04-08 15:26
Can you tell me when you will implement this. I have to sprocs using TVP that give the errors when generating:


Unable to get result set shape for PROCEDURE 'dbo.SOFA_QUESTION_CREATE_EF'
Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: nvarchar is incompatible with TVP_SOFA_DEPENDENT
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 84
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 103
ClientConnectionId:eec0235d-447e-45d0-a257-167856713b42
Error Number:206,State:2,Class:16

Unable to get result set shape for PROCEDURE 'dbo.SOFA_QUESTION_UPDATE_EF'
Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: nvarchar is incompatible with TVP_SOFA_DEPENDENT
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 84
   at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 103
ClientConnectionId:eec0235d-447e-45d0-a257-167856713b42
Error Number:206,State:2,Class:16

**Comment by ErikEJ** [comment] 2022-04-08 15:36
>> Can you tell me when you will implement this. I have to sprocs using TVP that give the errors when generating.

Please keep in mind that this is free software that I maintain in my spare time! 

I accept sponsorships and offer support for some sponsors (which could for example be implementing this). 

I will do it when I find time to invistigate and implement a good solution. 

In the meantime you can map this stored procedures manually, you have all the generated code as a good starting point! 

I also accept pull requests 😄

**Comment by DavidCAllenMI** [comment] 2022-04-08 16:00
Not implementing any time soon. Broke my code that was working with the TVP’s just fine until I turned on the multiple results option. I can send you the code for the sprocs to look at. I understand supporting something for free basically. I have several Android apps in the play store and I think I have made $50 in 5 years, but the people around the world that use it love it so….

**Comment by DavidCAllenMI** [comment] 2022-04-08 16:02
Here is the first one:

ALTER PROC [dbo].[SOFA_QUESTION_CREATE_EF]
	@p_sofa_country_question_id UNIQUEIDENTIFIER,
	@p_ques_answer_desc VARCHAR(500),
	@p_depl_id UNIQUEIDENTIFIER,
	@p_ques_answer_type_id UNIQUEIDENTIFIER,
	@p_session_id  UNIQUEIDENTIFIER,  -- '9A12F892-E21B-4740-A64B-0002DD909331'
	@p_sofa_dependents_list TVP_SOFA_DEPENDENT READONLY,	--added for multi dependents details
	@P_Sofa_Country_id UNIQUEIDENTIFIER   --added for multi dependents details

AS
	-- Declare Local Variable
	DECLARE @v_sofa_depl_ques_answer_id  as uniqueidentifier ,
		@v_create_by_user_id  uniqueidentifier,
		@error_number AS INT, 
		@error_message AS NVARCHAR(1000), 
		@error_severity AS INT,
		@now AS DATETIME = GETDATE(),
		@newId AS UNIQUEIDENTIFIER = NEWID();
	
	
	-- Test the session token to validate that the user is a valid user
	EXECUTE SESSION_VERIFY @p_session_id
	IF @@ERROR = 0
 
	-- Get the Created by User Id
		SELECT	@v_create_by_user_id = user_id	FROM dbo.TBL_SESSION	WHERE	session_id = @p_session_id	
		
  		--Get new primary key GUID for 'TBL_SOFA_DEPL_QUESTION_ANSWER' table 		
		SET @v_sofa_depl_ques_answer_id  = @newId

	
		 --Check and raise error message if selected answer is null or blank for SOFA question. 

		IF @p_ques_answer_desc IS  NULL OR  @p_ques_answer_desc ='' 
			BEGIN 
			RAISERROR ('Question answer value is  either NULL or Blank is selected', 16, 1) 
			END

		 -- Check and raise error message if record is already exist with same question and with same deployment.
		
		ELSE IF EXISTS (SELECT 1 FROM dbo.TBL_SOFA_DEPL_QUESTION_ANSWER WHERE SOFA_COUNTRY_QUESTION_ID=@p_sofa_country_question_id  AND DEPL_ID=@p_depl_id) 
		
			BEGIN 
			RAISERROR ('Unique key contraint violation, Duplicate row with same question Id (SOFA_COUNTRY_QUESTION_ID) for same deployment Id (DEPL_ID)', 16, 1) 
			END
		
		ELSE
		BEGIN TRY		
		 BEGIN TRAN
		
		-- Insert sofa question answer record into the TBL_SOFA_DEPL_QUESTION_ANSWER table

		INSERT INTO	dbo.TBL_SOFA_DEPL_QUESTION_ANSWER( 
			SOFA_DEPL_QUES_ANSWER_ID,
			SOFA_COUNTRY_QUESTION_ID,
			QUES_ANSWER_DESC, 
			QUES_ANSWER_TYPE_ID,
			DEPL_ID,
			CREATE_BY_USER_ID) 
			VALUES(
			@v_sofa_depl_ques_answer_id,
			@p_sofa_country_question_id, 
			@p_ques_answer_desc, 
			@p_ques_answer_type_id, 
			@p_depl_id,
			@v_create_by_user_id);
	
	--CR-1554: Start code change for dependents details of Deployed person

	 --Declare local variables
	
		DECLARE @v_Dependent_Ques  UNIQUEIDENTIFIER,
				@v_sofa_question UNIQUEIDENTIFIER
		
		SELECT @v_Dependent_Ques=SOFA_COUNTRY_QUESTION_ID 	FROM dbo.XREF_SOFA_COUNTRY_QUESTION WHERE COUNTRY_ID= @P_Sofa_Country_id AND SOFA_QUESTION_ID='6EED7C47-93B3-442B-BAA5-8D4BAC4101C2';
		SELECT @v_sofa_question=@p_sofa_country_question_id;
		
		
		--Check if added record is Number of dependent question .
		IF @v_sofa_question=@v_Dependent_Ques 
	
	    BEGIN

		DECLARE @Sofa_Dependents_Unique AS TABLE(
			[DEPL_ID] [UNIQUEIDENTIFIER] NOT NULL,
			[SOFA_COUNTRY_QUESTION_ID] [UNIQUEIDENTIFIER] NOT NULL,
			[DEPENDENT_NAME] [VARCHAR](100) NULL,
			[DOB] [DATETIME] NULL,
			[PASSPORT_NMBR] [VARCHAR](20) NULL,
			[SOFA_DEPEND_RELATIONSHIP_ID] [UNIQUEIDENTIFIER] NULL,
			[PASSPORT_COUNTRY_ID] [UNIQUEIDENTIFIER] NULL);

		INSERT INTO @Sofa_Dependents_Unique
		(
		    DEPL_ID,
		    SOFA_COUNTRY_QUESTION_ID,
		    DEPENDENT_NAME,
		    DOB,
		    PASSPORT_NMBR,
		    SOFA_DEPEND_RELATIONSHIP_ID,
		    PASSPORT_COUNTRY_ID
		)
		
	   SELECT DISTINCT  DEPL_ID,
		    SOFA_COUNTRY_QUESTION_ID,
		    DEPENDENT_NAME,
		    DOB,
		    PASSPORT_NMBR,
		    SOFA_DEPEND_RELATIONSHIP_ID,
		    PASSPORT_COUNTRY_ID
		FROM  @p_sofa_dependents_list
	
	--Insert Dependent details record
	INSERT INTO [dbo].[TBL_SOFA_DEPL_PERSON_DEPENDENT]
           ([DEPL_ID]
           ,[SOFA_DEPL_QUES_ANSWER_ID]
           ,[DEPENDENT_NAME]
           ,[DOB]
           ,[PASSPORT_NMBR]
           ,[SOFA_DEPEND_RELATIONSHIP_ID]
           ,[PASSPORT_COUNTRY_ID]
           ,[DEPEND_DETAILS_SOFA_QUESTION_ID]
           ,[CREATE_ON_DT]
           ,[CREATE_BY_USER_ID])
        SELECT [DEPL_ID],
		@v_sofa_depl_ques_answer_id AS SOFA_QUES_ANSWER_ID,
		[DEPENDENT_NAME],
		[DOB],
		[PASSPORT_NMBR],
		[SOFA_DEPEND_RELATIONSHIP_ID],
		[PASSPORT_COUNTRY_ID],
        '5ED5D729-92F9-4EAB-91E4-257C8D2D7AE9' AS DEPEND_SOFA_QUESTION_ID,  --'SOFA Dependents Details' grid question in lk_sofa_question table
		@now AS CREATE_ON_DT,
		@v_create_by_user_id AS CREATE_BY_USER_ID
		FROM  @Sofa_Dependents_Unique--- @p_sofa_dependents_list
    	END
		
		--CR-1554: End Multi dependents changes
		COMMIT TRAN
		END TRY
		BEGIN CATCH
			BEGIN
			SELECT @error_number = ERROR_NUMBER(), @error_message = ERROR_MESSAGE(),@error_severity = ERROR_SEVERITY();
			RAISERROR (@error_message, @error_severity, 1);
			IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
			END
		END CATCH

GO
/****** Object:  StoredProcedure [dbo].[SOFA_QUESTION_UPDATE_EF]    Script Date: 4/8/2022 11:22:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SOFA_QUESTION_UPDATE_EF]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[SOFA_QUESTION_UPDATE_EF] AS' 
END
GO

**Comment by ErikEJ** [comment] 2022-04-08 16:50
Thanks, I already have a repro.

And I have mentioned how to work around the issue.

**Comment by ErikEJ** [comment] 2022-04-09 07:52
@CorsairRO Why did FMTONLY work better for you with just single results?

**Comment by ErikEJ** [comment] 2022-04-09 07:53
@DavidCAllenMI I have identified and designed a fix, and am working on it.

**Comment by DavidCAllenMI** [comment] 2022-04-09 13:00
Our THE man!

**Comment by CorsairRO** [comment] 2022-04-11 05:41
@ErikEJ I didnt even test it with Multiple Resultsets as i am not using them at all. In my stripped tool i have just removed the option as i dont care for it.
However for single resultsets there are some limitations of the sp_describe_first_resultset that i have hit in lots of my SP.
Case1 - Inside the SP i have lots of updates/inserts into tables that have also triggers ( for correct stock calculations ).
The SP's returns me OK if the operation was ok, otherwise an error message for the user to know how to react to it.
Case2 - Inside the SP - Use a temporary table. Vast majority of my sp are like this to optimize the data presented to the user that comes from plenty of tables/views/TVF
Case3 - I have to support SQL2008 as i still have customers of my apps running it. Therefore my test DB is always set to be 2008. sp_describe... came out in SQL 2016 or similar. This is more an incovenience than an issue, because i have to have 2 Test DB one that goes live to customers and one that i update while developping my app.

I see an issue with FMTONLY and multiple resultsets if you have IF this SELECT a,b,c FROM T1 ELSE SELECT a,b,c FROM T2
Then FMT returns 2 resultsets, even if they are the same. In my logic i just keep the first resultset.
This could be an issue if you want to have 2 resultsets let's say, but for the first on you have that IF / ELSE.
Then you will get 3 Resultsets from SP and normally you would like to use only 2 of those.

**Comment by DavidCAllenMI** [comment] 2022-04-11 13:06
Cosmin you are very correct regarding changes that have to be made to even single resultset sprocs. I have entire list of things documented that need to be changed in my projects to get the result set to generate properly with the tool. I did not see all of them as bugs in the tool but as poorly written sprocs.

 

1.	Change temp tables to table variables.
2.	Do not sql functions suc as GetDate(0 in selects. I set a variable to get date and use the variable in the select.
3.	Only have one final select at the end otherwise every one is seen as a separate restultset when multiple option is turned on in the tool. I get around this by doing an insert into a table variable above all the selects and do a final select all on the table variable at the end of the sproc.
4.	I have enable/disable scripts for the triggers of any tables that the tool flags with trigger issues.
5.	Any selects that doing something like select max(create_date) from a table has to have an as column name added.

 

By doing all these things I have been able to get the tool to work perfect with our sprocs as well as I now have it generating multiple resultset for one of ours that actually does return multiple.

 

So my development procedure is:

1.	In SQL Server Manager run this for the sproc I want to use the tool on:

a.	EXEC sp_describe_first_result_set N’dbo.sprocnamehere’ if I get trigger-errors I look at the code and add the trigger to my enable/disable scripts. If I get no result set then I dig into the code and make the changes described above until I get this to work.

2.	Then I run the disable trigger script.
3.	Run the EF tool to gen my stuff
4.	Run the enable script so I don’t leave the db messed up for the other developers.

**Comment by DavidCAllenMI** [comment] 2022-04-11 15:01
I cannot say as I have not seen what the fmtonly option would do at this point. Is it to fix the TVP problem?

At this point everything is working well once I fixed a 5 stored procs to stop doing selects in every begin/end block other than those I have those two tvp issues.  
If you are saying that the fmtonly option will still work with the majority of my sprocs which only return a single result set then yes that would be good, but if I have to select the option to use the describe single for each of them, I have several hundred that I would have to check. I am thinking that you are saying fmtonly would work just fine for the majority of my sprocs though. so what you propose is probably great.

**Comment by ErikEJ** [comment] 2022-04-11 15:09
Fmtonly is the discovery method used currently when multiple result sets are enabled

**Comment by DavidCAllenMI** [comment] 2022-04-11 15:18
Sound awesome then! Thanks so very much for working on this! So this would still leave the TVP issue correct?

**Comment by DavidCAllenMI** [comment] 2022-04-11 15:52
So if you add that option then it will save reworking some of those sprocs with selects in every begin/end which is nice. I can just check those few with the describe first option. My most pressing concern is the TVP issues.

**Comment by CorsairRO** [comment] 2022-04-11 16:07
@DavidCAllenMI - The key point there is 2012. I have to stick for some time at least with 2008.
Issue with UDT as Params ( TVP ) has been fixed by me in my stripped version of the tool and tested and it works fine. Solution is NOT passing any parameters to the FMTONLY call to SP.

Definitively it is not a bug in the tool, just a suggestion that i made there working for ages now with FMTONLY in edmx since EF 4.0 shipped back in 2007 or 2009 i dont even remember. 
I have already tweaked @ErikEJ version in my minitool that now works fantastic to generate all my objects as Observable and all collections to be ObservableCollections. This is a level of customization that i couldnt use via Handlebars, as they just support some basic customizations. For example generating my POCO's with backing fields, and at set to call SetProperty from base class to raise Property changed was one major thing for me. The only way i could do that is by modifying CSharpCommentEntityGenerator and fully customize the code generation.
WPF / Xamarin programmers dont NEED to use 100 levels of same objects sent back and forth. Then manually do the change tracking and so on. In Web is perfectly ok to leave POCO's as they are, and generate business objects, but in WPF what is the point? Adding tons of mapping between lot of complex objects, testing lots of mapping framweorks, failing to update / map a crucial field for the DB and so  on ...

With @ErikEJ tool customized exactly to my needs i can now make a new page in my app in 30 minutes. Including Data Access / ViewModel / View / Validation / Basic CRUD ops on COMPLEX hierarchies of objects with many levels down and so on ...
I;ve even build myself an Application Framework for doing so in all my apps and i am very happy with it. The only missing part for me was EF Core, i was stuck to EF6 because of edmx vs command line useless scaffolding. Erik tool is the missing glue, it is EXTRAORDINARY tool and i am going to help him if he wants with what i can to enhance / adjust it 

Like i said, this might not be needed anymore when EF7 will go back to old plain T4 for customizing these. Anyway knowing now EF Team's approach to that it will still probably require to integrate with Erik's tool to work like it should.
MS guys werent EVER capable of delivering something that works Top to bottom. It needs to be something that doesnt work, and you have to go for a third party / custom implementation.

**Comment by DavidCAllenMI** [comment] 2022-04-12 16:02
Any idea when you might get the change in? I have a sproc that the tool says returns 66 results! It has a bunch of EXECUTEs of other sprocs.

**Comment by ErikEJ** [comment] 2022-04-12 19:07
I hope to fix this issue the coming weekend.

But it will not solve your completely unrelated issue..

**Comment by ErikEJ** [comment] 2022-04-12 19:08
@DavidCAllenMI Are you thinking of #1330?

**Comment by DavidCAllenMI** [comment] 2022-04-12 19:17
Yes I was referring to 1330 not this one. Sorry.

**Comment by ErikEJ** [comment] 2022-04-12 19:27
Please dont ask me for deadlines for something I do unpaid in my spare time.

If you really need this I can share my hourly rate.

**Closed** 2022-04-17 09:11 UTC
Labels: bug, reveng

**Comment by DavidCAllenMI** [comment] 2022-10-11 09:02
Idid not know that it was up to me to set the fmtonly flag. How do I do that?

**Comment by ErikEJ** [comment] 2022-10-11 09:42
@DavidCAllenMI  Please create a new issue with sufficient repro details, and I will assist
