### ISSUE TITLE
Question - Support for Custom Handlebars Generators?

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#1234] opened 2021-12-23 13:03 UTC
Hello again,

First of all, thank you again for the tool and for the answers to all the questions.

I am customizing a lot my generated objects, and i just wanted to ask if and how i can do this with the Power Tools.

I know that Power Tools is using the Hbs's from Handlebars and it works ok, i have tested and now after the latest update it works fine.
Because this is not enough for my requirements for generating objects, i found very nice explanation in the Handlebars project for how i can customize the objects generated, more precisely 7. Full Control: Extend Handlebars Generators

Now, my question is:
If i extend an HbsCSharpEntityTypeGenerator to make it to fit all my requirements form the objects, will Power Tools know how to pick it up somehow?
If yes, can you please be nice to show a quick example of that? I mean where to put/register and stuff.

Real life scenario usage - generate also business objects in another assembly and make them Observable and Validatable and so on ...
Tag business objects with some custom attributes that i would like to have based on Metadata from the context, and so on ...

Thank you very much for the answers.

As this is very important feature for me before moving any single project to EF Core, and the feature is not there, please let me know if i can help somehow with trying to implement such thing. In the end i see it as a minor change, like wherever the scaffolding is picking the Handlebars Generators to look in the same assembly and if a custom one is found, use that one. Similar to how EF DBContext automatically picks SqlAzureExecutionStrategy from a class from the aassembly

### Steps to reproduce

Not issue, just a question

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: Latest

Database engine: SQL Server

Visual Studio version: 17.0.4

**Comment by ErikEJ** [comment] 2021-12-23 14:28
Somewhat of a duplicate of #427

As stated there a PR would be considered.

But it is essentially not how Power Tools is designed.

Also, maybe you should stand back and consider if you should just treat your EF Core classes as plain table classes, and create your business classes on top?

**Comment by CorsairRO** [comment] 2021-12-23 14:44
hello, ok, thank you very much for the answer there.

- Not how Power Tools is designed - By adding handlebars support the tool got closer to edmx .tt customizing generation of classes. With my proposed addition will have the same degree of customization possibilities and nobody will miss anymore the edmx.

- Stand back and create business classes on top. This is exactly why i want to use handlebars to AUTO generate those and also add some basic information to them directly from ctx.Metadata.

- PR would be considered - OK, please let me know if i can look there and hep with anything.
I see in #427 that you say it should be considered only to be optional and not automatic. How i was suggesting was if there is and class in the assembly that extends from HbsEntityGenerator then use that one, otherwise use the normal one.
So it is as optional as you dont have a custom one, then no feature. Put such a class, automatically have the feature at regenerating objects.

Sorry for being so long and keeping you away from the Danish Christmas there ... Enjoy the marzipan cakes there...

**Comment by CorsairRO** [comment] 2021-12-23 14:44
and some Aquavit :)

**Comment by ErikEJ** [comment] 2021-12-23 15:31
Yes, implementing #427 would probably enable this - what I mean by optional is that this feature should only be enabled if the user opts in to do so by using Handlebars) - and it should handle assembly load failures gracefully (by reporting any issues with loading back and the continue)

**Comment by CorsairRO** [comment] 2021-12-23 15:48
hehe, yes, definitively agree that it should just silently ignore all the errors by just reporting them and continue

**Comment by ErikEJ** [comment] 2022-01-09 07:54
Moving ti Backlog iteration, a PR for this will still be considered

**Closed by ErikEJ** 2022-01-09 07:54 UTC
Labels: question

**Comment by CorsairRO** [comment] 2022-01-10 09:56
Hello,

sorry to bother you again on that topic.

I have downloaded a copy of your code and try to play with a possible implementation of this feature.

I am pretty advanced with it now, and of course i will post the changes that i am going to make in my copy so that you can review it and decide if you add it or not to the tool. 

I have made it to apply to Entity Type objects by ( RevEng.Core -> ServiceProviderBuilder )

if ( MyDiscoveredClassGenerator != null )
               serviceCollection.AddSingleton<ICSharpEntityTypeGenerator, MyDiscoveredClassGenerator 
This works fine, BUT, it doesnt apply to the objects from SP Resultset Objects.

I have tried to add a MySqlServerDesignTimeServices for example in the same file, in section
// Add database provider services for SQLServer
var provider = new MyDesignTimeServices();

And My Design Time services class.
public class MySqlServerDesignTimeServices : SqlServerDesignTimeSerices {

         public override void ConfigureDesignTimeServices( IServiceCollection serviceCollection ) {
		base.ConfigureDesignTimeServices( serviceCollection );
                if ( MyDiscoveredClassGenerator != null ) 
		           serviceCollection.AddSingleton<ICSharpEntityTypeGenerator , MyDiscoveredClassGenerator>( );
               else 
		           serviceCollection.AddSingleton<ICSharpEntityTypeGenerator , CommentCSharpEntityTypeGenerator>( );
	}

}

Unfortunately i get nowhere, the generation works, no errors thrown, but it just refuses to use the MyClassGenerator for SP Resultset objects. 
It refuses also the default CommentCSharpEntityTypeGenerator as i have added a custom comment there to test that works fine for Entities, but not for SP Resultset Objects.

Thank you,
and sorry to bother you again...

**Comment by ErikEJ** [comment] 2022-01-10 10:03
Handlebars has no knowledge of your stored procedure result sets
