### ISSUE TITLE
Entity Mapping Classes

### ISSUE THREAD

**Issue by OleAdmin** [ErikEJ/EFCorePowerTools#259] opened 2019-09-25 21:36 UTC
Thank you for this tool.  It is a great and much needed tool.  In the old power tools for EF6, reverse engineering was creating separate Entity and Mapping Classes.  But now there are only two options 1) to create the entity attributes or 2) to directly include the mappings in the context object as modelBuilder for the entity. I like to keep entities as pure poco classes and let the mapping class define the mappings and constraints for the database. I have several tables and the option 2 above generates a huge context class and it looks so ugly.  Am I missing something here?  was there a good reason to omit the option to create mappings as a separate class?

**Comment by ErikEJ** [comment] 2019-09-26 16:21
Duplicate of #100 - it is not something that the EF Core Scaffolding supports at the moment.

**Closed by ErikEJ** 2019-09-26 16:21 UTC
