### ISSUE TITLE
Reverse Engineer blocked by new SqlClient provider?

### ISSUE THREAD

**Issue by lbeck-cfcal** [ErikEJ/EFCorePowerTools#1770] opened 2023-04-19 14:01 UTC
### Provide steps to reproduce

- Right click on project > EF Core Power Tools > Reverse Engineer
- Define valid connection (proved by Test Connection)
- Click on OK
- Expected: window with tables displayed
- Observed: error popup "Unable to add connection, maybe the provider is not supported: Unable to cast object 'System.DBNull' to type 'System.String'"

### Provide technical details

- EF Core version in use: 3
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1372
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022 v17.5.3

**Comment by lbeck-cfcal** [comment] 2023-04-19 14:02
Solved by installing the previous version (v2.5.1338)

**Comment by ErikEJ** [comment] 2023-04-19 15:18
@lbeck-cfcal This is due to the fact that the connection dialog defaults to the new SqlClient provider in VS 17.5. You can pikc the old one instead and continue using the latest build.

**Comment by RenanCarlosPereira** [comment] 2023-04-19 15:30
im having this error when I try to add a new connection to SQL server, not sure how can I go back to the previous version. 

@ErikEJ could you help me?

![image](https://user-images.githubusercontent.com/13982555/233125294-4e421f1f-f1a0-4ead-9428-0341c14f21fd.png)

**Comment by ErikEJ** [comment] 2023-04-19 15:43
I will try to repro and debug

**Comment by ErikEJ** [comment] 2023-04-19 15:44
@RenanCarlosPereira are you also using EF Core 3.1 ?

**Comment by FlorianGuillou** [comment] 2023-04-19 15:47
Hello,

I have exactly the same issue.
Can you tell me how to go back to the previous version in visual studio ?

Thanks =)

**Comment by ErikEJ** [comment] 2023-04-19 15:48
@FlorianGuillou are you using EF Core 3.1?

**Comment by ErikEJ** [comment] 2023-04-19 15:49
I suspect this is a bug and I will look into a fix today

**Comment by FrqSalah** [comment] 2023-04-19 15:53
Note that when you generate your connection at least once with the 1338 version, you can use the last version without problem.

**Comment by FlorianGuillou** [comment] 2023-04-19 15:53
> @FlorianGuillou are you using EF Core 3.1?

Target FrameWork: .Net6.0
Entity FrameWork Core Version: 6.0.10

This is what I found.

Thanks for your help!

**Comment by RenanCarlosPereira** [comment] 2023-04-19 15:53
@ErikEJ No, Im using dot net 6.0

**Comment by ErikEJ** [comment] 2023-04-19 15:56
I need more explicit repro steps please

**Comment by RenanCarlosPereira** [comment] 2023-04-19 16:01
Basically, if you open a brand new console application, visual studio and right click in the EF Core Power tools menu, and try to add a connection to a database by selecting the reverse engineer it will reproduce the issue.
On that screen putting your server (connection string) works fine also when you click test connection. 
Once you click OK on that screen, you got the error. 

hope that helps...

let me know if you want me to help you with that, we can get in a call or something =)

**Comment by FlorianGuillou** [comment] 2023-04-19 16:04
> Solved by installing the previous version (v2.5.1338)

How did you do it ?
Thanks

**Comment by ErikEJ** [comment] 2023-04-19 16:05
I have located a potential bug, and am working on a fix due in minutes, not hours.

In the meantime you can create the connection in Server Explorer as a workaround.

**Comment by FlorianGuillou** [comment] 2023-04-19 17:37
It worked !
Thanks for quick answer!

**Comment by ErikEJ** [comment] 2023-04-19 17:49
@FlorianGuillou thanks for the heads up!

**Comment by ErikEJ** [comment] 2023-04-19 18:03
@RenanCarlosPereira did you install buld 1377?

**Comment by RenanCarlosPereira** [comment] 2023-04-19 18:17
yes, its there in the streenshot

**Comment by ErikEJ** [comment] 2023-04-19 18:21
@RenanCarlosPereira Suspecting you need a VS restart.

**Comment by RenanCarlosPereira** [comment] 2023-04-20 09:47
hey @ErikEJ  sorry for the delay, I restart my machine and still getting the same problem. 
it's not affecting me because I used **Server Explorer** so all good, but in the EF core power tools menu, it's still giving me this error.

some details about my version: 

![image](https://user-images.githubusercontent.com/13982555/233327654-9c03a8e9-ea03-49d6-825e-b5c07be44a44.png)
![image](https://user-images.githubusercontent.com/13982555/233328854-9c80b462-0b34-4fae-9612-6219a6a7141c.png)

**Comment by ErikEJ** [comment] 2023-04-20 09:52
Are you setting any special options when adding the connection?

What access does the account you use for access have in the database?

**Comment by ErikEJ** [comment] 2023-04-20 09:56
Ah, my fix was wrong!

**Comment by ErikEJ** [comment] 2023-04-20 10:01
@RenanCarlosPereira  This query against your database returns "NULL" - not sure why:

     SELECT LOWER(@@servername) + '.' + DB_NAME() + '.' + SCHEMA_NAME()

**Comment by ErikEJ** [comment] 2023-04-20 10:18
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Closed by ErikEJ** 2023-04-20 10:18 UTC

**Comment by ErikEJ** [comment] 2023-04-20 10:26
Note to self: @@SERVERNAME can easiliy return null!

**Comment by RenanCarlosPereira** [comment] 2023-04-20 10:46
hey @ErikEJ  its working now, as expected, thanks 😀

**Comment by ErikEJ** [comment] 2023-04-20 10:50
@RenanCarlosPereira Cool, and thanks for your patience
