### ISSUE TITLE
Unable to connect to database with SQL authentication that has special characters in the password

### ISSUE THREAD

**Issue by ericccGit** [ErikEJ/EFCorePowerTools#575] opened 2020-11-12 18:46 UTC
I have am dealing with a database that only support SQL authentication and the password I was given has the special characters '$' and ';'. When using scaffold-dbcontext the only workaround that worked for me was to wrap the data-source in single-quotes and the password in double quotes:

Scaffold-DbContext 'Data Source=whatever.net,1433;Initial Catalog=whatEverDb;User Id=MyUserId;Password="dumbPas$word;";' ...

 However I want to use EFPT to do some column renaming, but I cannot connect through the EFPT GUI as the password is presumably not being sanitized in a way that allows special characters.

### Steps to reproduce
1. Create a test database in MS-SQL-Server with a SQL authenticated password like 'dumbPas$word;'. 
2. Try connecting through Reverse-Engineering Menu. Should be unable to connect. 

### Further technical details
EF Core Power Tools version: 2.5.277

Database engine: SQL Server 

Visual Studio version: Visual Studio 2019 16.7.7

**Comment by ErikEJ** [comment] 2020-11-13 07:00
I am not able to reproduce with the provided example password, please provide more detailed repro steps.

**Comment by ErikEJ** [comment] 2020-11-13 13:23
I was finally able to reproduce, I believe this was fixed in the latest daily build, see https://github.com/ErikEJ/EFCorePowerTools/pull/578

**Closed** 2020-11-13 13:23 UTC

**Comment by ericccGit** [comment] 2020-11-13 16:29
@ErikEJ It looks to be working now, thanks!

**Comment by ErikEJ** [comment] 2020-11-13 16:30
Thanks for confirming!
