### ISSUE TITLE
EFCorePowerTools - VS 2022 - NET 6

### ISSUE THREAD

**Issue by EnesTUTUNCU** [ErikEJ/EFCorePowerTools#1434] opened 2022-06-21 11:47 UTC
Dear Mr Erik,

First of all, thank you very much to reply my comment in visualstudio.com.

I've switched to another computer and that is Windows 11.

I moved my all solution to that OS and then, i upgraded my all solution's projects from .net core 3.1 to .net 6.

When i try to reverse engineer after right-click to related project in my solution, i choose EF Core 6.

Actually i tried all choose options in selection box (EF Core3, 5, 6) but none of them help me.

I've been getting that error in the following.

---
**System.InvalidOperationException: Table list error: 
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Users\intranet\AppData\Local\Temp\efreveng6.2.5.1007.0\efreveng60.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Users\intranet\AppData\Local\Temp\efreveng6.2.5.1007.0\efreveng60.dll'

   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas, bool mergeDacpacs)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)**
---

Please help me to resolve this issue.

By the way, i'm writing all necessary informations to below.

- OS = Windows 11
- OS Bit = 64Bit / ARM64
- Visual Studio = 2022
- Packages
- - Microsoft.EntityFrameworkCore (6.0.6)
- - Microsoft.EntityFrameworkCore.Relational (6.0.6)
- - Microsoft.EntityFrameworkCore.SqlServer (6.0.6)
- - Microsoft.EntityFrameworkCore.Tools (6.0.6)

Also attaching several screenshots which may help you.

![2](https://user-images.githubusercontent.com/34237963/174791795-a0aec322-9309-40aa-b383-2e87708c4f26.png)
![1](https://user-images.githubusercontent.com/34237963/174791800-6eaf2104-21c2-440b-8525-449ebdc179a2.png)

Thanks in advance,

Regarding,

Enes

**Comment by ErikEJ** [comment] 2022-06-21 13:58
Possible duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/1141#issuecomment-945709906

**Closed** 2022-06-22 05:28 UTC
