### ISSUE TITLE
Customize (re)naming convention of navigation properties

### ISSUE THREAD

**Issue by michaelkollmann** [ErikEJ/EFCorePowerTools#647] opened 2020-12-09 20:54 UTC
I'm using EF Core Power Tools to reverse engineer my data model from a .dacpac file.
Everything works fine so far and I'm really enjoying it!

The one thing that does not fit in with my environment is the naming of the navigation properties in the models.
For example, having a foreign key property named "IdSensor" gets turned into "IdSensorNavigation".
I however would much prefer the navigation property to be named "Sensor" without the "Id" prefix and the "Navigation" suffix.

I looked into the Handlebars customization, as well as the custom renaming with the efpt.renaming.json file but I didn't find any way to change this behavior.

Is there any way for me to change this behavior?

Thanks! 

### Further technical details
EF Core Power Tools version: 2.5.277

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.8.0

**Comment by ErikEJ** [comment] 2020-12-10 06:07
Duplicate of #211

**Closed by ErikEJ** 2020-12-10 06:07 UTC
