### ISSUE TITLE
Unable to get result set shape for PROCEDURE 'dbo.Department_Delete'

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#1381] opened 2022-05-05 17:28 UTC
Describe what is not working as expected.

### Steps to reproduce

1. Create database from this script: https://gist.githubusercontent.com/doggy8088/2a2f7075d49b3814d19513426ede3549/raw/56926225027def21c627dd6391ab4866957ca5ac/ContosoUniversity.sql

2. Create new project and use Reverse Engineer to generate classes including all **Stored Procedures**.

3. You will see errors in the Output window.
    
    ```txt
    Unable to get result set shape for PROCEDURE 'dbo.Department_Delete'
    Microsoft.Data.SqlClient.SqlException (0x80131904): Implicit conversion from data type nvarchar to timestamp is not allowed. Use the CONVERT function to run this query.
       at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
       at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
       at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
       at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
       at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
       at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
       at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
       at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module, Boolean singleResult) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 90
       at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetResultElementLists(SqlConnection connection, Routine module, Boolean multipleResults, Boolean useLegacyResultSetDiscovery) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 62
       at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25
    ClientConnectionId:da352c90-8d89-4478-8993-4fccda4ea117
    Error Number:257,State:3,Class:16
    
    Unable to get result set shape for PROCEDURE 'dbo.Department_Update'
    Microsoft.Data.SqlClient.SqlException (0x80131904): Implicit conversion from data type nvarchar to timestamp is not allowed. Use the CONVERT function to run this query.
       at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
       at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
       at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
       at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
       at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
       at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
       at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
       at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetAllResultSets(SqlConnection connection, Routine module, Boolean singleResult) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 90
       at RevEng.Core.Procedures.SqlServerStoredProcedureModelFactory.GetResultElementLists(SqlConnection connection, Routine module, Boolean multipleResults, Boolean useLegacyResultSetDiscovery) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureModelFactory.cs:line 62
       at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25
    ClientConnectionId:da352c90-8d89-4478-8993-4fccda4ea117
    Error Number:257,State:3,Class:16
    ```

### Further technical details

EF Core version in use: `EF Core 6`

Is Handlebars used: `no`

EF Core Power Tools version: `2.5.977.0`

Database engine: `SQL Server`

Visual Studio version: `Visual Studio 2022`

**Comment by ErikEJ** [comment] 2022-05-05 18:56
Duplicate of #1380

**Comment by ErikEJ** [comment] 2022-05-06 06:23
Fixed in latest daily build, please let me know if that solves the issue (not using any workarounds)

**Closed** 2022-05-06 06:22 UTC

**Comment by doggy8088** [comment] 2022-05-06 18:31
I tested. It works great! 👍

**Comment by mustafaelshobaky** [comment] 2022-07-06 20:03
This bug is happening again after the last update on 2 July 2022.
I'm getting the following error in the output window. That didn't use to happen before the update.

```
Unable to get result set shape for PROCEDURE 'dbo.Proc_AdjustMemberBalance'.
Invalid object name '#claims'.
```

It doesn't like my temp table very much.

I'm creating the temp table on the fly like that
```
SELECT 
		sa_reclaimdet.*,
		sa_reclaim.SA_RSTATUS,SA_CCODE 
	INTO 
		#claims
	FROM 
		sa_reclaimdet,
		sa_reclaim
	WHERE 
		sa_reclaimdet.sa_rcode=sa_reclaim.sa_rcode AND 
		contract_id=@Contract_ID AND 
		SA_EMPID=@Member_ID	AND 
		SA_RSTATUS <> 'C'
```

Further technical details
EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.1041

Database engine: SQL Server

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment] 2022-07-07 05:14
@mustafaelshobaky please don't add to closed issues.

This error was always there, it was just not communicated back previously. 

You will have to refactor your stored proc in create the result set shape yourself as described in the wiki.
