### ISSUE TITLE
Strange Behavior During Reverse Engineering

### ISSUE THREAD

**Issue by jcantrel** [ErikEJ/EFCorePowerTools#1454] opened 2022-07-15 18:38 UTC
I have a set of tables, with one primary table and then a series of sub tables that share a primary key, when I run a reverse engineer on the database the foreign keys in the primary table get named very strangely. I am using the newest version and EF Core 6.

The Table SQL:
```
CREATE TABLE [dbo].[ClientUpdates_Clients] (
    [ClientID]             INT           IDENTITY (1, 1) NOT NULL,
    [ClientCode]           NCHAR (5)     NOT NULL,
    [ClientName]           VARCHAR (30)  NOT NULL,
    [ContactName]          VARCHAR (50)  NULL,
    [ContactPosition]      VARCHAR (50)  NULL,
    [ContactInfo]          VARCHAR (50)  NULL,
    [Revision]             BIT           NOT NULL,
    [CreatedUsername]      VARCHAR (50)  NOT NULL,
    [CreatedDatetime]      DATETIME2 (7) NOT NULL,
    [LastModifiedUsername] DATETIME      NOT NULL,
    [LastModifiedDatetime] DATETIME2 (7) NOT NULL,
    [Canceled]             BIT           NOT NULL,
    [CancelUsername]       VARCHAR (50)  NOT NULL,
    [CancelDatetime]       DATETIME2 (7) NOT NULL,
    [Completed]            BIT           NOT NULL,
    [CompleteUsername]     VARCHAR (50)  NOT NULL,
    [CompleteDatetime]     DATETIME2 (7) NOT NULL,
    PRIMARY KEY CLUSTERED ([ClientID] ASC),
    CONSTRAINT [FK_ClientUpdatesClient_Contracting] FOREIGN KEY ([ClientID]) REFERENCES [dbo].[ClientUpdates_ContractingSections] ([ContractingID]),
    CONSTRAINT [FK_ClientUpdatesClient_Sales] FOREIGN KEY ([ClientID]) REFERENCES [dbo].[ClientUpdates_SalesSections] ([SalesID]),
    CONSTRAINT [FK_ClientUpdatesClient_Billing] FOREIGN KEY ([ClientID]) REFERENCES [dbo].[ClientUpdates_BillingSections] ([BillingID]),
    CONSTRAINT [FK_ClientUpdatesClient_Charting] FOREIGN KEY ([ClientID]) REFERENCES [dbo].[ClientUpdates_ChartingSections] ([ChartingID]),
    CONSTRAINT [FK_ClientUpdatesClient_Courier] FOREIGN KEY ([ClientID]) REFERENCES [dbo].[ClientUpdates_CourierSections] ([CourierID]),
    CONSTRAINT [FK_ClientUpdatesClient_Organization] FOREIGN KEY ([ClientID]) REFERENCES [dbo].[ClientUpdates_OrganizationSections] ([OrganizationID]),
    CONSTRAINT [FK_ClientUpdatesClient_Specimen] FOREIGN KEY ([ClientID]) REFERENCES [dbo].[ClientUpdates_SpecimenSections] ([SpecimenID])
);
```
The C# output:

```

public partial class ClientUpdatesClient
    {
        public ClientUpdatesClient()
        {
            ClientUpdatesAddresses = new HashSet<ClientUpdatesAddress>();
            ClientUpdatesPhoneNumbers = new HashSet<ClientUpdatesPhoneNumber>();
        }

        public int ClientId { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string ContactName { get; set; }
        public string ContactPosition { get; set; }
        public string ContactInfo { get; set; }
        public bool Revision { get; set; }
        public string CreatedUsername { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime LastModifiedUsername { get; set; }
        public DateTime LastModifiedDatetime { get; set; }
        public bool Canceled { get; set; }
        public string CancelUsername { get; set; }
        public DateTime CancelDatetime { get; set; }
        public bool Completed { get; set; }
        public string CompleteUsername { get; set; }
        public DateTime CompleteDatetime { get; set; }

        public virtual ClientUpdatesBillingSection Client { get; set; }
        public virtual ClientUpdatesContractingSection Client1 { get; set; }
        public virtual ClientUpdatesCourierSection Client2 { get; set; }
        public virtual ClientUpdatesOrganizationSection Client3 { get; set; }
        public virtual ClientUpdatesSalesSection Client4 { get; set; }
        public virtual ClientUpdatesSpecimenSection Client5 { get; set; }
        public virtual ClientUpdatesChartingSection ClientNavigation { get; set; }
        public virtual ICollection<ClientUpdatesAddress> ClientUpdatesAddresses { get; set; }
        public virtual ICollection<ClientUpdatesPhoneNumber> ClientUpdatesPhoneNumbers { get; set; }
    }

```

**Comment by ErikEJ** [comment] 2022-07-16 12:16
I am not sure there is anything strange here other than the fact that your primary key is foreign key for 5 tables.

Seems like a duplicate of #211

**Closed** 2022-07-18 06:53 UTC
