### ISSUE TITLE
Why a "BIT NOT NULL" is represented as "bool?" in C# ?

### ISSUE THREAD

**Issue by marcscheuner** [ErikEJ/EFCorePowerTools#899] opened 2021-04-03 05:40 UTC
I have a SQL Server 2017+ database table which contains a "flag" column called "IsActive" of type "BIT" and it's defined as "NOT NULL" and has a default constraint. 

So from my point of view - this can never ever be NULL - no chance.

However, when doing a Reverse Engineering with EF Core Power Tools, it gets represented in the C# class as a "bool? IsActive". 

Why? That doesn't seem necessary to me - and the property even gets the "[Required]" data annotation, too - so why "bool?" ?? Wouldn't just "bool" be good enough and be more accurate to the situation?

![IsActive_flag_SQLServer](https://user-images.githubusercontent.com/2045391/113469679-d4e47000-944f-11eb-8170-0cf9e98bb3ff.jpg)

![IsActiveProperty_CSharp](https://user-images.githubusercontent.com/2045391/113469680-d57d0680-944f-11eb-9ef1-6535d551537e.jpg)

**Comment by ErikEJ** [comment] 2021-04-03 06:10
It is actually [by design](https://github.com/ErikEJ/EFCorePowerTools/issues/245#issuecomment-520488843) - but you can use the [advanced option](https://github.com/ErikEJ/EFCorePowerTools/issues/160#issuecomment-748051295) to "fix" it.

**Comment by ErikEJ** [comment] 2021-04-03 06:12
Duplicate of #160

**Comment by ErikEJ** [comment] 2021-04-03 06:12
Duplicate of #160

**Closed by ErikEJ** 2021-04-03 06:12 UTC
