### ISSUE TITLE
Reverse Engineer and Oracle

### ISSUE THREAD

**Issue by gardner711** [ErikEJ/EFCorePowerTools#171] opened 2019-01-18 23:19 UTC
It doesn't look like you support Oracle as a provider for the Reverse Engineer function. Love the feature, use it everywhere from SQL and existing database or database first approach. Can you add Oracle support?

### Steps to reproduce
Add an Oracle connection in VS
Right click project select Reverse Engineer
Oracle connection does not appear in the drop down

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: Oracle

Visual Studio version: Visual Studio 2017 15.9

**Comment by ErikEJ** [comment] 2019-01-19 07:51
This is a duplicate of #17

**Closed by ErikEJ** 2019-01-19 07:51 UTC
