### ISSUE TITLE
Exception when calling stored procedure.

### ISSUE THREAD

**Issue by charanpasham** [ErikEJ/EFCorePowerTools#982] opened 2021-05-14 21:53 UTC
Describe what is not working as expected.
When executing the stored procedure, it says my dbContext connection is closed. (Getting this InvalidOperationException exception in DbContextExtension.cs) (SqlQueryAsync<T>) method.
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
So, I added all [dbo], [views], [stored procedure dbo's]. It generated me DbContext. I am getting data from the database tables but not from the stored procedure.
### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.649
Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)
SQL Server
Visual Studio version: (e.g. Visual Studio 2019 16.9)
Visual Studio 16.9

**Comment by ErikEJ** [comment] 2021-05-15 05:43
The methods are Async, are you calling them correctly?

Maybe duplicate of #966 ?

**Comment by ErikEJ** [comment] 2021-05-15 12:43
Ping?

**Comment by charanpasham** [comment] 2021-05-16 14:46
Sorry for the late reply. Yes, I am calling them correctly I think. This is my code. 
` public List<pdfFields> GetMappings(int carrierId, int confId, out List<int> pagesToExclude)
        {
            pagesToExclude = new List<int>();
            List<int> pages = pagesToExclude;

            DataHelper.DoInDataScope(async ctxBase =>
            {
                var cName = BaseContext.Carrier.First(x => x.id ==  id).dbName;
                 var formDataResponse =
                    await BaseContext.Procedures.ApplicationSubmissionSummaryAsync(confId, cName, null);
                var formData = formDataResponse.ToList();
            }, "none");

            return formData;
        }`

**Comment by charanpasham** [comment] 2021-05-16 15:42
![image](https://user-images.githubusercontent.com/32817111/118403282-c76bf980-b63b-11eb-8456-5067f83b3caa.png)

This is where it is throwing this error.

**Comment by ErikEJ** [comment] 2021-05-16 18:54
If you want help you need to share a runnable project, not fragments of code.

**Comment by charanpasham** [comment] 2021-05-16 19:50
I think I figured it out. I am not instantiating the context through DI, instead doing (new DbContext()). When I added the dependency through AddDbContext in startup.cs, it worked for me.

**Closed** 2021-05-17 11:47 UTC
