### ISSUE TITLE
Use Regex For Renaming Navigations Across All Tables

### ISSUE THREAD

**Issue by tafs7** [ErikEJ/EFCorePowerTools#848] opened 2021-03-12 21:01 UTC
Would be nice to allow renaming with regex patterns to be used for all navigations?

For example, every time we see a navigation property that would be generated as this:

`public virtual Payor PayorCompany { get; set; }`

instead we rename to simply this:
`public virtual Payor Payor { get; set; }`

We can do this one-by-one in the `efpt.renaming.json` file for each table in the `"Tables[]"` array, like this:
```jsonc
[
    {
      "SchemaName": "dbo",
      "Tables": [
        {
          "Name": "Table1",
          "Navigations": [
            {
              "Name": "PayorCompany",
              "NewName": "Payor"
            }
          ],
          "NewName": null
        },
        {
          "Name": "Table2",
          "Navigations": [
            {
              "Name": "PayorCompany",
              "NewName": "Payor"
            }
          ],
          "NewName": null
        },
       //.....  repeat for each table where this might apply.....
      ]
   }
]
```

But ideally we could tell the EPT via config to apply that renaming rule for EVERY table similarly to the table renaming regex feature.

**Comment by ErikEJ** [comment] 2021-03-13 07:41
Happy to receive a well tested PR for this proposal!

**Comment by sm15455** [comment] 2021-03-13 11:25
@ErikEJ do you think we can create a UI to edit regex settings in renaming? I was also thinking about a UI for renaming navigation properties but I don't know if we have them before code generation.

**Comment by ErikEJ** [comment] 2021-03-13 12:15
Yes, I suppose we could add an "Advanced" dialog to do that, a maybe include regex validation.

**Comment by ErikEJ** [comment] 2021-03-13 12:18
The issue is that we do not know the names of navigations at this point, so it is very hard to do....

**Comment by sm15455** [comment] 2021-03-13 16:45
> 
> 
> The issue is that we do not know the names of navigations at this point, so it is very hard to do....

The database model returned by the call to IDatabaseModelFactory.Create contains foreign keys. Maybe we can work on that adding the Navigation suffix to the foreign key property. Don't know if it adds value though.

**Comment by ErikEJ** [comment] 2021-03-13 17:02
It is not as simple as that, sadly.

**Comment by ErikEJ** [comment] 2021-05-02 07:09
Closing as the feature is removed (for now)

**Closed by ErikEJ** 2021-05-02 07:09 UTC
Labels: enhancement, reveng
