### ISSUE TITLE
Compare DBContext to database - error

### ISSUE THREAD

**Issue by jstachera** [ErikEJ/EFCorePowerTools#817] opened 2021-02-26 10:35 UTC
The option 'Compare DBContext to database' for postgresql 10.12 for C# console project targeting .NET Core 5.0 is throwing exception as below.

### Steps to reproduce
I got following error:
```
1>------ Build started: Project: FakeTitleMaker, Configuration: Debug Any CPU ------
1>FakeTitleMaker -> C:\Users\stacherj\source\repos\FakeTitleMaker\FakeTitleMaker\bin\Debug\net5.0\FakeTitleMaker.dll
========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

System.ArgumentException: warn: 2/26/2021 11:29:24.629 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: 2/26/2021 11:29:24.814 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Entity Framework Core 5.0.3 initialized 'TMDBContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: SensitiveDataLoggingEnabled 
Error:
System.InvalidOperationException: Your database provider isn't built into EfCore.SchemaCompare. This means you need to
use the CompareEfWithDb<T> method which takes in a design time class for your database. e.g.
comparer.CompareEfWithDb<NpgsqlDesignTimeServices>(context) for a Npgsql PostgreSql database provider.
Also look at the documentation in the EfCore.SchemaCompare README file
   at EfSchemaCompare.Internal.DesignProvider.GetDesignTimeService(DbContext context)
   at EfSchemaCompare.CompareEfSql.CompareEfWithDb(String configOrConnectionString, DbContext[] dbContexts)
   at Modelling.EfCoreCompareBuilder.GetCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\EFCorePowerTools\src\GUI\efpt50.core\EFCoreCompareBuilder.cs:line 53
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 36

Parameter name: processResult
   at EFCorePowerTools.Handlers.Compare.CompareHandler.<GetComparisonResultAsync>d__4.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\Compare\CompareHandler.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EFCorePowerTools.Handlers.Compare.CompareHandler.<HandleComparisonAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\Compare\CompareHandler.cs:line 111
```

### Further technical details
EF Core Power Tools version: 2.5.537.0

Database engine: postgresql 10.12.

Visual Studio version: Visual Studio 2019 16.8.5

**Comment by ErikEJ** [comment] 2021-02-26 10:40
Duplicate of #810

**Closed by ErikEJ** 2021-02-26 10:40 UTC
