### ISSUE TITLE
Error on reverse engineering

### ISSUE THREAD

**Issue by tkardaridis** [ErikEJ/EFCorePowerTools#2203] opened 2024-03-01 13:14 UTC
Hi, I am trying to reverse engineer my database and I am getting the following error.

System.NullReferenceException: Object reference not set to an instance of an object.
   at RevEng.Core.ReverseEngineerScaffolder.AppendSchemaFoldersAndNamespace(IModel databaseModel, ScaffoldedModel scaffoldedModel, Boolean useSchemaFolders, Boolean useSchemaNamespaces, IEnumerable`1 schemas) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 345
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 460
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 78

Is there anyway to find the cause of the problem in the database?

- EF Core Power Tools version: 2.6.165

- Exact Visual Studio version: Visual Studio 2022 17.9.2

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: yes just to change the inherited dbcontext to a custom dbcontext class.

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment] 2024-03-01 13:21
Duplicate of #2110 ? I think adding Handlebars to the experimental mix breaks stuff

**Comment by ErikEJ** [comment] 2024-03-04 07:10
At any rate I need a full schema and settings in order to help you, and that was not provided.

**Closed by ErikEJ** 2024-03-04 07:10 UTC
Labels: question
