### ISSUE TITLE
Unable to Reverse Engineer tables that have a Unique Constraint on a computed column from a database project

### ISSUE THREAD

**Issue by cbrianball** [ErikEJ/EFCorePowerTools#208] opened 2019-04-23 18:57 UTC
I receive an error when reverse engineering a database whenever I included a table that has a unique constraint on a persisted computed column.

I understand that computed columns cannot be derived from the dacpac file, so the tools probably aren't able to locate the column in the metadata for the unique constraint, but ideally this shouldn't cause the entire reverse engineer process to error out (maybe throw a warning?).

### Steps to reproduce
1. Create a new database project in Visual Studio
2. Create a new table with a persisted computed column that has a unique constraint
3. Create a new C# project in Visual Studio
4. Reverse engineer the table from the database project

The Build Output has the following stack trace:
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at ReverseEngineer20.SqlServerDacpacDatabaseModelFactory.GetUniqueConstraints(TSqlTable table, DatabaseModel dbModel)
   at ReverseEngineer20.SqlServerDacpacDatabaseModelFactory.Create(String dacpacPath, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 193
```

### Further technical details
EF Core Power Tools version: 2.2.12

Database engine: N/A (using SSDT Database project in Visual Studio)

Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment] 2019-04-23 19:07
Can you provide a sample SQL script for the table?

**Comment by cbrianball** [comment] 2019-04-23 20:02
Here's an example script:

````
CREATE TABLE [dbo].[Foo]
(	
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[AlternateKey] INT NULL,
	[UniqueId] AS ISNULL(ISNULL(AlternateKey, Id), 0),
	CONSTRAINT [My_Constraint] UNIQUE(UniqueId),
)
````

Here's a VS2019 project that uses the script and demonstrates the issue. If you try to use EF Power Tools on the App project and point to the DB project and select dbo.Foo table, you will see the error in the output window.

[EFPowerToolsIssue208.zip](https://github.com/ErikEJ/EFCorePowerTools/files/3109360/EFPowerToolsIssue208.zip)

**Comment by ErikEJ** [comment] 2019-04-24 05:40
Thanks for reporting this, fixed in the latest daily build

**Closed** 2019-04-24 05:40 UTC

**Comment by cbrianball** [comment] 2019-04-25 01:01
Thanks, I'll pull from the daily build to test. How often do you publish to the market place?

**Comment by godfrey-tech** [comment] 2021-11-10 09:55
Hi folks 
Having issue with EF Core Power tool, is unable to generate class with the below basis calculation  
 [Test1] smallint,
 [Test2] smallint,
 [Results] As Test1 * Test2,
 
 It only generate the below 
  public short? Test1 { get; set; }
  public short? Test2 { get; set; }

**Comment by ErikEJ** [comment] 2021-11-10 11:25
From a dacpac?

**Comment by godfrey-tech** [comment] 2021-11-10 11:27
Yes

**Comment by ErikEJ** [comment] 2021-11-10 13:54
@godfrey-tech By design: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-database-project-dacpac-mapping
