### ISSUE TITLE
Add support for IBM IDS(Informix Data Servers 11.5 and late) 

### ISSUE THREAD

**Issue by iliev72** [ErikEJ/EFCorePowerTools#285] opened 2019-10-14 12:48 UTC
It's possible to add support for Informix Server 11.5 and late version ?!

**Comment by ErikEJ** [comment] 2019-10-14 13:01
Potentially, see https://github.com/ErikEJ/EFCorePowerTools/issues/17 for requirements

**Comment by jespersh** [comment] 2019-10-14 13:04
Anyone who wants to have fun with it, see to get the DDEX part installed: https://stackoverflow.com/questions/33328429/how-to-find-informix-datasource-in-visual-studio-to-connect-to

Looks complicated and licensed although a trial is available.

**Comment by ErikEJ** [comment] 2019-10-14 17:29
Is there an Informix EF Core provider??

**Comment by iliev72** [comment] 2019-10-14 17:44
yes :)
https://www.ibm.com/developerworks/community/forums/html/topic?id=18f76739-2637-466f-ae43-2558ca93db94&ps=100

**Comment by ErikEJ** [comment] 2019-10-15 10:00
Duplicate of #288

**Closed by ErikEJ** 2019-10-15 10:00 UTC
Labels: enhancement, reveng
