### ISSUE TITLE
Method not found: AddHandlebarsScaffolding 

### ISSUE THREAD

**Issue by cagacu** [ErikEJ/EFCorePowerTools#35] opened 2018-05-29 13:36 UTC
Hello,
After yesterday, -i am not sure if it is about update- i started get following error. I am trying to run power tool on .net core class library.

System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 154

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

### Further technical details
.NET Core 2.0

Visual Studio  : 15.7.2

EF Power Tool version : 
_Version 1.0.603.0
SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes_

#

**Comment by ErikEJ** [comment] 2018-05-29 15:28
I believe this is fixed in the latest daily build, would be very grateful if you could confirm (as I am not able to reproduce) https://github.com/ErikEJ/EFCorePowerTools/wiki

**Comment by cagacu** [comment] 2018-05-30 11:28
Thank you for answer.

Today, my error has changed. I am getting this error;
By the way, i installed latest version of this nuget packages;
Microsoft.AspNetCore.All v2.08
Microsoft.EntityFrameworkCore v2.10
Microsoft.EntityFrameworkCore.Design v2.10
Microsoft.EntityFrameworkCore.SqlServer v2.10
Microsoft.Extensions.DependencyInjection v2.10
Microsoft.Extensions.DependencyInjection.Abstraction v2.10


System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'.
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext()

**Comment by ErikEJ** [comment] 2018-05-30 11:30
Again, I am not able to reproduce - please tell me:
Visual Studio version, Windows version, and share a repro project with me if possible

**Comment by ErikEJ** [comment] 2018-06-03 14:51
Closing as additional information not received - feel free to re-open if you can provide addítional info

**Closed by ErikEJ** 2018-06-03 14:51 UTC
