### ISSUE TITLE
POCO Advanced settings

### ISSUE THREAD

**Issue by pomella** [ErikEJ/EFCorePowerTools#1646] opened 2023-01-04 08:47 UTC
Is it possible to reintroduce the POCO advanced settings?
I'm working with entities without navigation properties and with the new version is very hard to discover the right way to properly remove navigation properties using T4 or Handlebars.

### Provide steps to reproduce

1. Run reverse engineering
2. choose a local DB connection (with at least two related tables)
3. select some tables with relations
4. in the main rev eng window let default settings (no template generation)
5. click on Advance button
6. The POCO group box is not available and is not possible to che the option "Remove navigation properties from entities"

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: yes & no (I tried with both)

- EF Core Power Tools version: the last downloaded on 2023 01 03

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 Enterprise

**Comment by ErikEJ** [comment] 2023-01-04 09:17
See [this](https://github.com/ErikEJ/EFCorePowerTools/issues/1639#issuecomment-1368934499)

Duplicate of #1639

**Comment by pomella** [comment] 2023-01-04 09:34
Thank you for the reply.
But let me say that a checkbox is more easy than a template implementation. But you have the whole vision of this project, so I can only thank you for the great job and support. I'm going to study the T4 implementation following your example, with the hope in the future you can resolve all the issues regarding the POCO implementation in the advanced dialog and restore this feature ... :-)

Thanks

**Comment by ErikEJ** [comment] 2023-01-04 09:43
I appreciate the pain of losing an experimental feature - but as noted in the other issues, this was a half baked feature that did not fit the bill for all POCO requirements. And yes, this prejects main focus is EF Core, not generation of POCO classes for use with other providers.

If you encounter issues adding the sample POCO template, please let me know, and I will follow up with advice or maybe a blog post.

**Comment by ErikEJ** [comment] 2023-01-04 09:52
I think I will add an template option so it is easy to get started with a POCO entity template.

**Comment by pomella** [comment] 2023-01-04 10:09
I appreciate your proposal. 
I'll try to better explain my use case if it can help:

I used the checkbox "No Navigation" to prevent the generation of navigation properties. This is a must for my project because I must expose models as results of my NET CORE 6.0 Web API calls. If I leave the navigation properties, the API and swagger throw exceptions caused by the loop in the json serialization.
For this reason I found the "No Navigation" option very usefull because the result is to generate entities without navigation properties.

Thank you again for your interest
So I'm not really interested on POCO entities but

**Comment by ErikEJ** [comment] 2023-01-04 10:17
>> If I leave the navigation properties, the API and swagger throw exceptions caused by the loop in the json serialization.

You can configure your json serializer to avoid this.

**Closed** 2023-01-04 11:01 UTC
Labels: question

**Comment by ErikEJ** [comment] 2023-01-04 11:04
I have added a new template option: C# - T4 (POCO)

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
