### ISSUE TITLE
System.ArgumentException: Error: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0

### ISSUE THREAD

**Issue by kaluznyt** [ErikEJ/EFCorePowerTools#98] opened 2018-09-30 20:33 UTC
Describe what is not working as expected.

### Steps to reproduce
Click "Add DbContext Model as Diagram" on a project containing a simple DbContext class containing 3 DbSets with simple entities

### Further technical details
EF Core Power Tools version: 1.0.643.0

Database engine: SQL Server Express 

Visual Studio version: Visual Studio 2017 15.8.2

When trying to use the "Add DbContext as Diagram" I'm getting the following:

```
System.ArgumentException: Error:
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl)
   at ReverseEngineer20.EfCoreModelBuilder.GenerateDebugView(String outputPath)
   at ReverseEngineer20.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49
```

Assuming it's trying to use 2.0.0.0 version of entityframeworkcore while I have 2.1.3 installed. Is it an issue or am I missing something ?

Thanks for any clues for have it working. 

Cheers
Tomasz

**Comment by ErikEJ** [comment] 2018-10-01 06:42
Duplicate of #97 - could you please try out the latest daily build?

**Comment by ErikEJ** [comment] 2018-10-06 06:58
Fixed in latest released version

**Closed by ErikEJ** 2018-10-06 06:58 UTC
